// SPDX-License-Identifier: Apache-2.0
import type { DatabaseSync } from 'node:sqlite';
import { newId, WriterError, workflowHash as hash, validateWorkflowConfig, validateWorkflowBudget, stageTasks, workflowStage,
  buildMemoryPlan, normalizeMemoryOptions, memoryText, validateWorkflowOutput, renderWorkflowDraft } from '@writer-agent/core';
import type { WorkflowConfig, WorkflowRun, WorkflowCapture, WorkflowBudget, WorkflowGrant, WorkflowAttempt,
  WorkflowArtifact, WorkflowLease, WorkflowKind, IntentVersion, MemoryPacket, WorkflowContentRequest, OutlineOutput, DraftOutput } from '@writer-agent/core';
import type { Workspace } from './index.js';
const TTL=45000;
const now=()=>new Date().toISOString();
const fault=(code:'WORKFLOW_INVALID'|'WORKFLOW_BUSY'|'WORKFLOW_PERMISSION'|'WORKFLOW_BUDGET'|'WORKFLOW_UNKNOWN'|'STALE_REVISION',message:string):never=>{throw new WriterError(code,message);};
function unpack<T>(row:Record<string,unknown>|undefined):T {
  if(!row)throw new WriterError('NOT_FOUND','Workflow record not found.');
  if(typeof row.payload!=='string'||typeof row.payload_hash!=='string'||hash(JSON.parse(row.payload))!==row.payload_hash)throw new WriterError('CORRUPT_DATA','Workflow record failed integrity validation.');
  return JSON.parse(row.payload) as T;
}
const sum=(a:WorkflowBudget,b:WorkflowBudget):WorkflowBudget=>({models:a.models+b.models,searches:a.searches+b.searches,fetches:a.fetches+b.fetches,activeMs:a.activeMs+b.activeMs});
/** All methods are host capabilities. No model or source receives this store. */
export class WorkflowStore {
  constructor(private readonly db:DatabaseSync,private readonly ready:()=>void,private readonly tx:<T>(fn:()=>T)=>T,private readonly host:Workspace){}
  private read<T>(table:string,id:string):T {this.ready();memoryText(id,200);return unpack<T>(this.db.prepare(`SELECT payload,payload_hash FROM ${table} WHERE id=?`).get(id));}
  private insert(table:string,id:string,value:unknown,columns:Record<string,string>={}){
    const keys=['id',...Object.keys(columns),'payload','payload_hash'];this.db.prepare(`INSERT INTO ${table}(${keys.join(',')}) VALUES(${keys.map(()=>'?').join(',')})`).run(id,...Object.values(columns),JSON.stringify(value),hash(value));
  }
  private event(runId:string,action:string,detail:unknown){this.insert('workflow_events',newId('wfevent'),{action,detail,createdAt:now()},{run_id:runId});}
  private write(run:WorkflowRun){run.updatedAt=now();this.db.prepare('UPDATE workflow_runs SET payload=?,payload_hash=?,version=version+1 WHERE id=?').run(JSON.stringify(run),hash(run),run.id);}
  private attemptWrite(a:WorkflowAttempt){this.db.prepare('UPDATE workflow_attempts SET payload=?,payload_hash=? WHERE id=?').run(JSON.stringify(a),hash(a),a.id);}
  run(id:string):WorkflowRun{const r=this.read<WorkflowRun>('workflow_runs',id);validateWorkflowConfig(r.config);if(r.id!==id)throw new WriterError('CORRUPT_DATA','Wrong run identity.');return r;}
  list():WorkflowRun[]{this.ready();return this.db.prepare('SELECT id FROM workflow_runs ORDER BY rowid DESC LIMIT 200').all().map(r=>this.run(String(r.id)));}
  artifact(id:string):WorkflowArtifact{return this.read('workflow_artifacts',id);}
  artifacts(id:string):WorkflowArtifact[]{this.run(id);return this.db.prepare('SELECT payload,payload_hash FROM workflow_artifacts WHERE run_id=? ORDER BY seq').all(id).map(r=>unpack(r));}
  find(id:string,key:string):WorkflowArtifact|null {this.ready();const row=this.db.prepare('SELECT payload,payload_hash FROM workflow_artifacts WHERE run_id=? AND step_key=?').get(id,key);return row?unpack(row):null;}
  attempts(id:string):WorkflowAttempt[]{this.run(id);return this.db.prepare('SELECT payload,payload_hash FROM workflow_attempts WHERE run_id=? ORDER BY seq').all(id).map(r=>unpack(r));}
  events(id:string):unknown[]{this.run(id);return this.db.prepare('SELECT payload,payload_hash FROM workflow_events WHERE run_id=? ORDER BY seq').all(id).map(r=>unpack(r));}
  grant(id:string):WorkflowGrant{return this.read('workflow_grants',id);}
  usage(id:string,grantId?:string):WorkflowBudget{
    const a=this.attempts(id).filter(a=>!grantId||a.grantId===grantId);
    const row=grantId?this.db.prepare('SELECT active_ms n FROM workflow_grants WHERE id=? AND run_id=?').get(grantId,id):this.db.prepare('SELECT COALESCE(SUM(active_ms),0) n FROM workflow_grants WHERE run_id=?').get(id);
    return {models:a.filter(x=>x.kind==='model').length,searches:a.filter(x=>x.kind==='search').length,fetches:a.filter(x=>x.kind==='fetch').length,activeMs:Number(row?.n??0)};
  }
  private free(id:string){const row=this.db.prepare('SELECT owner,expires_at FROM workflow_runs WHERE id=?').get(id);if(row?.owner!==null){fault('WORKFLOW_BUSY','Task has an execution lease. If its worker exited, wait 45 seconds and explicitly recover it.');}}
  private capture(id:string,c:WorkflowConfig):WorkflowCapture {
    const doc=c.documentId?this.host.currentRevision(c.documentId):null;
    const sources=[...this.host.sources.context(c.selection)];
    const changes=c.changeIds.map(id=>{const a=this.host.getChange(id);if(a.documentId!==c.documentId||a.status!=='pending')fault('WORKFLOW_INVALID','Select current pending changes in this document.');return {id,hash:hash(a)};});
    let writing:MemoryPacket|null=null,review:MemoryPacket|null=null,writingCapture=null,reviewCapture=null,guidanceStamp:string;
    if(doc){const a=this.host.memory.plan(doc.documentId,'revise',c.memoryOptions),b=this.host.memory.plan(doc.documentId,'review',c.memoryOptions);if(a.conflicts.length||b.conflicts.length)throw new WriterError('GUIDANCE_CONFLICT','Resolve writing/review guidance conflicts before authorizing.');writing=a.capture.packet;review=b.capture.packet;writingCapture=a.capture;reviewCapture=b.capture;guidanceStamp=hash([a.capture.stamp,b.capture.stamp]);}
    else {
      const profile=c.profileId?this.host.memory.profile(c.profileId):null;
      // Reuse the pure guidance selector with run-owned IDs, never create a fake manuscript/revision.
      const intent:IntentVersion|null=c.intent?{id:`run-intent:${id}`,documentId:`run:${id}`,baseRevisionId:'not-a-document',parentId:null,card:c.intent,origin:'manual',runId:null,createdAt:''}:null;
      const plans=(['revise','review'] as const).map(task=>buildMemoryPlan({documentId:`run:${id}`,task,options:{...c.memoryOptions,language:c.language},intent,profile,preferences:profile?this.host.memory.preferences(profile.id):[],bindingId:profile?.id??null,activeIntentEvent:hash(c.intent),importantClaims:[]}));
      if(plans.some(p=>p.conflicts.length))throw new WriterError('GUIDANCE_CONFLICT','Resolve run-owned guidance conflicts first.');
      writing=plans[0]!.capture.packet;review=plans[1]!.capture.packet;guidanceStamp=hash(plans.map(p=>p.capture.stamp));
    }
    let analysisStamp:string|null=null;
    if(c.template==='review-changes')analysisStamp=hash(this.host.analysis.prepare(c.documentId!,'semantic-review',{instruction:c.goal,changeIds:c.changeIds,documentScope:true,selection:c.selection,memoryOptions:c.memoryOptions}));
    return {documentId:c.documentId,revisionId:doc?.id??null,snapshot:doc?.snapshot??null,changes,sources,writing,review,writingCapture,reviewCapture,guidanceStamp,analysisStamp};
  }
  assertFresh(run:WorkflowRun):void{if(hash(this.capture(run.id,run.config))!==hash(run.capture))fault('STALE_REVISION','Document, selected changes or applicable guidance changed. Refresh and reauthorize this task; saved outputs remain historical.');}
  create(input:WorkflowConfig):WorkflowRun{
    this.ready();validateWorkflowConfig(input);const c=structuredClone(input),id=newId('run');normalizeMemoryOptions(c.memoryOptions);
    return this.tx(()=>{const capture=this.capture(id,c);const run:WorkflowRun={id,config:c,capture,fingerprint:hash({config:c,capture}),epoch:1,state:'waiting-approval',stage:workflowStage(c.template),outlineId:null,selectedOutlineId:null,candidateIds:[],reportIds:[],grantId:null,adoptedDocumentId:null,notice:'Authorize the displayed stage to begin; no external request has been sent.',createdAt:now(),updatedAt:now()};this.insert('workflow_runs',id,run);this.event(id,'created',{fingerprint:run.fingerprint});return run;});
  }
  refresh(id:string,config?:WorkflowConfig):WorkflowRun{return this.tx(()=>{const r=this.run(id);this.free(id);if(r.adoptedDocumentId||['completed','cancelled'].includes(r.state))fault('WORKFLOW_INVALID','A closed run cannot be retargeted. Create a new explicit task.');const c=structuredClone(config??r.config);validateWorkflowConfig(c);const u=this.usage(id);if(['models','searches','fetches','activeMs'].some(k=>u[k as keyof WorkflowBudget]>c.budget[k as keyof WorkflowBudget]))fault('WORKFLOW_BUDGET','New budget cannot be below attempts/time already spent.');r.config=c;r.capture=this.capture(id,c);r.fingerprint=hash({config:c,capture:r.capture});r.epoch++;r.grantId=null;r.selectedOutlineId=null;r.outlineId=null;r.candidateIds=[];r.reportIds=[];r.stage=workflowStage(c.template);r.state='waiting-approval';r.notice='Inputs refreshed; reauthorize. Public search/fetch caches remain reusable only for matching request keys.';this.write(r);this.event(id,'refreshed',{epoch:r.epoch,fingerprint:r.fingerprint});return r;});}
  setBudget(id:string,budget:WorkflowBudget):WorkflowRun{return this.tx(()=>{const r=this.run(id);this.free(id);if(['completed','cancelled'].includes(r.state))fault('WORKFLOW_PERMISSION','Closed task budgets cannot be changed.');validateWorkflowBudget(budget);const spent=this.usage(id);for(const k of ['models','searches','fetches','activeMs'] as const)if(budget[k]<spent[k])fault('WORKFLOW_BUDGET','Budget cannot be less than already spent attempts/time.');r.config.budget=structuredClone(budget);r.fingerprint=hash({config:r.config,capture:r.capture});r.grantId=null;r.state='waiting-approval';r.notice='Budget changed by author. Reauthorize this stage; saved matching results remain available.';this.write(r);this.event(id,'budget-changed',{budget});return r;});}
  compare(id:string,beforeId:string,afterId:string){const r=this.run(id),a=this.artifact(beforeId),b=this.artifact(afterId);for(const x of [a,b])if(x.runId!==r.id||!['draft','draft-revision'].includes(x.type))fault('WORKFLOW_INVALID','Choose two draft artifacts of the same task.');const av=a.value as {output:DraftOutput},bv=b.value as {output:DraftOutput};const before=av.output.markdown,after=bv.output.markdown;let prefix=0;while(prefix<Math.min(before.length,after.length)&&before[prefix]===after[prefix])prefix++;if(prefix>0&&prefix<before.length&&/[\uDC00-\uDFFF]/.test(before[prefix]!))prefix--;let suffix=0;while(suffix<Math.min(before.length-prefix,after.length-prefix)&&before[before.length-1-suffix]===after[after.length-1-suffix])suffix++;if(suffix>0&&/[\uDC00-\uDFFF]/.test(before[before.length-suffix]!))suffix--;return {kind:'mechanical-candidate-comparison',notSemanticVerdict:true,beforeArtifactId:a.id,afterArtifactId:b.id,historical:a.epoch!==r.epoch||b.epoch!==r.epoch||!r.candidateIds.includes(a.id)||!r.candidateIds.includes(b.id),sameText:before===after,before,after,span:{startUtf16:prefix,beforeEndUtf16:before.length-suffix,afterEndUtf16:after.length-suffix,removed:before.slice(prefix,before.length-suffix),inserted:after.slice(prefix,after.length-suffix)}};}
  preview(id:string,limits?:WorkflowBudget){
    const r=this.run(id);this.assertFresh(r);const spent=this.usage(id),max=r.config.budget;
    const defaults:WorkflowBudget={models:Math.min(r.stage==='audit'?1:r.stage==='research'?3:3,max.models-spent.models),searches:r.stage==='research'&&r.config.research==='web'?Math.min(3,max.searches-spent.searches):0,fetches:r.stage==='research'&&r.config.research==='web'?Math.min(5,max.fetches-spent.fetches):0,activeMs:Math.max(100,max.activeMs-spent.activeMs)};
    const quota=limits??defaults;validateWorkflowBudget(quota);
    for(const k of ['models','searches','fetches','activeMs'] as const)if(quota[k]>max[k]-spent[k])fault('WORKFLOW_BUDGET','Stage limits exceed the remaining task budget.');
    if(r.stage!=='research'&&(quota.searches||quota.fetches)||r.config.research==='selected'&&(quota.searches||quota.fetches))fault('WORKFLOW_PERMISSION','This stage has no search/fetch permission.');
    const summary={runId:id,template:r.config.template,templateVersion:1,stage:r.stage,fingerprint:r.fingerprint,outlineId:r.selectedOutlineId,outline:r.selectedOutlineId?this.artifact(r.selectedOutlineId).value:null,
      allowedTasks:stageTasks(r.stage),limits:quota,spent,model:r.config.model,search:r.config.research==='web'?{provider:'tavily',endpoint:'https://api.tavily.com/search',keyEnv:r.config.searchKeyEnv,publicBrief:r.config.publicBrief,domains:r.config.domains,timeRange:r.config.timeRange,depth:'basic',maxResults:5}:null,
      selection:r.capture,goal:r.config.goal,autoRevision:r.config.autoRevision,
      notice:'Stage consent permits the displayed bounded sequence, not manuscript approval or memory activation. Only publicBrief goes to query planning. Search snippets are discoveries, not page snapshots. Fees may be unknown.'};
    return {fingerprint:hash(summary),summary,limits:quota};
  }
  authorize(id:string,previewHash:string,limits?:WorkflowBudget):WorkflowGrant{return this.tx(()=>{
    const r=this.run(id);this.free(id);if(['completed','cancelled'].includes(r.state))fault('WORKFLOW_PERMISSION','This run is already closed.');const p=this.preview(id,limits);if(p.fingerprint!==previewHash)fault('STALE_REVISION','Authorization preview changed; inspect it again.');
    const grant:WorkflowGrant={id:newId('grant'),runId:id,stage:r.stage,fingerprint:r.fingerprint,outlineId:r.selectedOutlineId,limits:p.limits,allowedTasks:stageTasks(r.stage),summary:p.summary,createdAt:now()};this.insert('workflow_grants',grant.id,grant,{run_id:id});r.grantId=grant.id;r.state='ready';r.notice='Stage authorized; explicit run/continue starts execution.';this.write(r);this.event(id,'authorized',{grantId:grant.id,previewHash});return grant;
  });}
  private checkGrant(r:WorkflowRun){if(!r.grantId)fault('WORKFLOW_PERMISSION','No active stage approval.');const g=this.grant(r.grantId!);if(g.fingerprint!==r.fingerprint||g.stage!==r.stage||g.outlineId!==r.selectedOutlineId)fault('WORKFLOW_PERMISSION','Stage approval is stale.');return g;}
  acquire(id:string,clock=Date.now()):WorkflowLease{return this.tx(()=>{
    const r=this.run(id);this.assertFresh(r);this.checkGrant(r);if(['completed','cancelled','waiting-approval'].includes(r.state))fault('WORKFLOW_PERMISSION','Task is waiting for approval or already closed.');
    const row=this.db.prepare('SELECT owner,generation FROM workflow_runs WHERE id=?').get(id)!;
    if(row.owner!==null)fault('WORKFLOW_BUSY','Another worker owns this run, or an expired worker needs explicit recovery.');
    if(this.attempts(id).some(a=>a.status==='dispatched'||a.status==='reserved'||a.status==='outcome-unknown'))fault('WORKFLOW_UNKNOWN','An unfinished request needs explicit recovery/retry; it will not be resent silently.');
    const lease={runId:id,owner:newId('worker'),generation:Number(row.generation)+1};this.db.prepare('UPDATE workflow_runs SET owner=?,generation=?,expires_at=?,accounted_at=? WHERE id=?').run(lease.owner,lease.generation,clock+TTL,clock,id);r.state='running';this.write(r);this.event(id,'acquired',{generation:lease.generation});return lease;
  });}
  private lock(lease:WorkflowLease,clock=Date.now()){const row=this.db.prepare('SELECT owner,generation,expires_at,accounted_at FROM workflow_runs WHERE id=?').get(lease.runId);if(!row||row.owner!==lease.owner||row.generation!==lease.generation||Number(row.expires_at)<clock)fault('WORKFLOW_BUSY','Execution lease lost; this worker cannot save results.');return row;}
  private charge(id:string,clock:number){const row=this.db.prepare('SELECT expires_at,accounted_at FROM workflow_runs WHERE id=?').get(id)!;const r=this.run(id);if(r.grantId){const until=Math.min(clock,Number(row.expires_at)),elapsed=Math.max(0,until-Number(row.accounted_at));this.db.prepare('UPDATE workflow_grants SET active_ms=active_ms+? WHERE id=?').run(elapsed,r.grantId);this.db.prepare('UPDATE workflow_runs SET accounted_at=? WHERE id=?').run(until,id);}}
  pulse(lease:WorkflowLease,clock=Date.now()):void{
    const within=this.tx(()=>{this.lock(lease,clock);this.charge(lease.runId,clock);const r=this.run(lease.runId),g=this.checkGrant(r);this.db.prepare('UPDATE workflow_runs SET expires_at=? WHERE id=?').run(clock+TTL,r.id);return this.usage(r.id).activeMs<r.config.budget.activeMs&&this.usage(r.id,g.id).activeMs<g.limits.activeMs;});
    if(!within)fault('WORKFLOW_BUDGET','Active execution time budget reached; author waiting time is not counted.');
  }
  reserve(lease:WorkflowLease,key:string,kind:WorkflowKind,task:string,request:unknown):WorkflowAttempt{return this.tx(()=>{
    this.lock(lease);const r=this.run(lease.runId);this.assertFresh(r);const g=this.checkGrant(r);if(kind!==(task==='search'?'search':task==='fetch'?'fetch':'model'))fault('WORKFLOW_PERMISSION','Wrong budget category for task.');if(!g.allowedTasks.includes(task))fault('WORKFLOW_PERMISSION','Task is outside the approved template stage.');
    if(['draft-revision','revise-proposal'].includes(task)&&!r.config.autoRevision)fault('WORKFLOW_PERMISSION','The author did not permit an automatic revision.');
    if(['draft-revision','revise-proposal'].includes(task)&&this.attempts(r.id).some(a=>a.task===task&&a.status==='completed'))fault('WORKFLOW_BUDGET','The one automatic revision for this task is already consumed. Start an explicit new task for another round.');
    if(this.find(r.id,key))fault('WORKFLOW_INVALID','Step already has a saved result; reuse it.');
    if(this.attempts(r.id).some(a=>a.key===key&&a.status!=='retry-approved'))fault('WORKFLOW_UNKNOWN','A previous attempt requires an explicit retry decision.');
    const unit={models:kind==='model'?1:0,searches:kind==='search'?1:0,fetches:kind==='fetch'?1:0,activeMs:0};
    const taskUse=sum(this.usage(r.id),unit),stageUse=sum(this.usage(r.id,g.id),unit);for(const k of ['models','searches','fetches','activeMs'] as const)if(taskUse[k]>r.config.budget[k]||stageUse[k]>g.limits[k])fault('WORKFLOW_BUDGET','Task/stage budget exhausted. Raise limits explicitly and reauthorize.');
    if(Buffer.byteLength(JSON.stringify(request))>6_000_000)fault('WORKFLOW_INVALID','Step input exceeds its byte bound.');
    const a:WorkflowAttempt={id:newId('attempt'),runId:r.id,grantId:g.id,key,kind,task,inputHash:hash(request),status:'reserved',request:structuredClone(request),artifactId:null,errorCode:null,usage:null,startedAt:Date.now(),finishedAt:null,generation:lease.generation};
    this.insert('workflow_attempts',a.id,a,{run_id:r.id,grant_id:g.id,step_key:key});return a;
  });}
  dispatched(lease:WorkflowLease,id:string):void{this.tx(()=>{this.lock(lease);const r=this.run(lease.runId);this.assertFresh(r);this.checkGrant(r);const a=this.read<WorkflowAttempt>('workflow_attempts',id);if(a.runId!==r.id||a.generation!==lease.generation||a.status!=='reserved')fault('WORKFLOW_INVALID','Invalid dispatch transition.');a.status='dispatched';this.attemptWrite(a);});}
  complete(lease:WorkflowLease,id:string,type:string,value:unknown,parentIds:string[]=[],usage:WorkflowAttempt['usage']=null,effect?:(value:unknown)=>unknown):WorkflowArtifact{return this.tx(()=>{
    this.lock(lease);const r=this.run(lease.runId);this.assertFresh(r);this.checkGrant(r);const a=this.read<WorkflowAttempt>('workflow_attempts',id);
    if(a.runId!==r.id||a.generation!==lease.generation||!['dispatched','completed'].includes(a.status))fault('WORKFLOW_INVALID','Invalid completion transition.');
    if(a.status==='completed')return this.artifact(a.artifactId!);
    for(const p of parentIds)if(this.artifact(p).runId!==r.id)fault('WORKFLOW_INVALID','Cross-run artifact reference.');
    const result=effect?effect(value):value;if(Buffer.byteLength(JSON.stringify(result))>6_000_000)fault('WORKFLOW_INVALID','Artifact too large.');
    const art:WorkflowArtifact={id:newId('artifact'),runId:r.id,key:a.key,type,inputHash:a.inputHash,parentIds,value:result,createdAt:now(),origin:a.kind==='model'?'model':'host',epoch:r.epoch};this.insert('workflow_artifacts',art.id,art,{run_id:r.id,step_key:a.key});a.artifactId=art.id;a.status='completed';a.finishedAt=Date.now();a.usage=usage;this.attemptWrite(a);this.event(r.id,'step-completed',{attemptId:id,artifactId:art.id,type});return art;
  });}
  fail(lease:WorkflowLease,id:string,code:string,unknown:boolean):void{this.tx(()=>{this.lock(lease);const a=this.read<WorkflowAttempt>('workflow_attempts',id);if(a.runId!==lease.runId||a.generation!==lease.generation||!['reserved','dispatched'].includes(a.status))return;
    a.status=unknown&&a.status==='dispatched'?'outcome-unknown':'failed';a.errorCode=/^[A-Z0-9_]{1,80}$/.test(code)?code:'STEP_FAILED';a.finishedAt=Date.now();this.attemptWrite(a);this.event(a.runId,'step-stopped',{attemptId:id,status:a.status,code:a.errorCode});});}
  checkpoint(lease:WorkflowLease,update:Partial<Pick<WorkflowRun,'state'|'stage'|'outlineId'|'candidateIds'|'reportIds'|'notice'>>):WorkflowRun{return this.tx(()=>{this.lock(lease);const r=this.run(lease.runId);this.assertFresh(r);Object.assign(r,update);this.write(r);return r;});}
  release(lease:WorkflowLease,state:WorkflowRun['state']='paused',notice='Progress saved.'):void{this.tx(()=>{const row=this.db.prepare('SELECT owner,generation FROM workflow_runs WHERE id=?').get(lease.runId);if(row?.owner!==lease.owner||row.generation!==lease.generation)return;
    this.charge(lease.runId,Date.now());const r=this.run(lease.runId);if(r.state==='running'){r.state=state;r.notice=notice;this.write(r);}this.db.prepare('UPDATE workflow_runs SET owner=NULL,expires_at=0,accounted_at=0 WHERE id=?').run(r.id);});}
  recover(id:string,clock=Date.now()):void{this.tx(()=>{const r=this.run(id),row=this.db.prepare('SELECT owner,expires_at FROM workflow_runs WHERE id=?').get(id)!;if(row.owner!==null&&Number(row.expires_at)>=clock)fault('WORKFLOW_BUSY','Worker lease is still alive. Stop/wait rather than steal it.');
    if(row.owner!==null)this.charge(id,clock);for(const a of this.attempts(id)){if(a.status==='dispatched'){a.status='outcome-unknown';a.errorCode='INTERRUPTED_AFTER_DISPATCH';a.finishedAt=clock;this.attemptWrite(a);}else if(a.status==='reserved'){a.status='failed';a.errorCode='NOT_SENT';a.finishedAt=clock;this.attemptWrite(a);}}
    this.db.prepare('UPDATE workflow_runs SET owner=NULL,generation=generation+1,expires_at=0,accounted_at=0 WHERE id=?').run(id);if(!['completed','cancelled'].includes(r.state)){r.state='paused';r.notice='Recovered locally. Unknown/failed attempts require an explicit retry decision, and budgets are not reset.';this.write(r);}this.event(id,'recovered',{});
  });}
  retry(id:string,attemptId:string,acknowledgeDuplicate:boolean):void{this.tx(()=>{this.run(id);this.free(id);const a=this.read<WorkflowAttempt>('workflow_attempts',attemptId);if(a.runId!==id||!['failed','outcome-unknown'].includes(a.status))fault('WORKFLOW_INVALID','Choose a failed/unknown attempt from this run.');if(a.status==='outcome-unknown'&&!acknowledgeDuplicate)fault('WORKFLOW_UNKNOWN','The service may have already processed/charged this request. Explicit duplicate-call acknowledgement is required.');const old=a.status;a.status='retry-approved';this.attemptWrite(a);this.event(id,'retry-approved',{attemptId,previousStatus:old,possibleDuplicate:old==='outcome-unknown'});});}
  pause(id:string,cancel=false):void{this.tx(()=>{const r=this.run(id);if(['completed','cancelled'].includes(r.state))return;this.charge(id,Date.now());for(const a of this.attempts(id))if(['reserved','dispatched'].includes(a.status)){a.status=a.status==='dispatched'?'outcome-unknown':'failed';a.errorCode='AUTHOR_STOP';this.attemptWrite(a);}this.db.prepare('UPDATE workflow_runs SET owner=NULL,generation=generation+1,expires_at=0,accounted_at=0 WHERE id=?').run(id);r.grantId=null;r.state=cancel?'cancelled':'waiting-approval';r.notice='Stage permission revoked. Saved artifacts remain; no background work is scheduled.';this.write(r);this.event(id,cancel?'cancelled':'permission-revoked',{});});}
  chooseOutline(id:string,artifactId:string):WorkflowRun{return this.tx(()=>{const r=this.run(id);this.free(id);this.assertFresh(r);if(['completed','cancelled'].includes(r.state))fault('WORKFLOW_PERMISSION','Task is closed.');if(r.config.template!=='new-article')fault('WORKFLOW_INVALID','Only new articles have an outline gate.');if(r.selectedOutlineId===artifactId)return r;if(artifactId!==r.outlineId)fault('STALE_REVISION','Approve the current outline version, not an older artifact.');const art=this.artifact(artifactId);if(art.runId!==id||art.type!=='outline'||art.epoch!==r.epoch)fault('WORKFLOW_INVALID','Wrong outline.');r.selectedOutlineId=artifactId;r.stage='compose';r.grantId=null;r.state='waiting-approval';r.candidateIds=[];r.reportIds=[];this.write(r);this.event(id,'outline-approved',{artifactId});return r;});}
  amendOutline(id:string,artifactId:string,value:OutlineOutput):WorkflowArtifact{return this.tx(()=>{const r=this.run(id);this.free(id);this.assertFresh(r);if(['completed','cancelled'].includes(r.state))fault('WORKFLOW_PERMISSION','Task is closed.');if(artifactId!==r.outlineId)fault('STALE_REVISION','Edit the latest outline.');const parent=this.artifact(artifactId);const packet=(parent.value as {output:OutlineOutput;request:WorkflowContentRequest});validateWorkflowOutput(value,packet.request);
    const art:WorkflowArtifact={id:newId('artifact'),runId:id,key:`author-outline:${newId('edit')}`,type:'outline',inputHash:hash(packet.request),parentIds:[artifactId],value:{request:packet.request,output:structuredClone(value)},createdAt:now(),origin:'author',epoch:r.epoch};this.insert('workflow_artifacts',art.id,art,{run_id:id,step_key:art.key});r.outlineId=art.id;r.selectedOutlineId=null;r.candidateIds=[];r.reportIds=[];r.stage='research';r.state='waiting-approval';r.grantId=null;this.write(r);this.event(id,'outline-amended',{artifactId:art.id});return art;});}
  adopt(id:string,artifactId:string):string{return this.tx(()=>{const r=this.run(id);this.free(id);if(r.adoptedDocumentId){const old=this.events(id).find(e=>(e as {action:string}).action==='adopted') as {detail:{artifactId:string}}|undefined;if(old?.detail.artifactId===artifactId)return r.adoptedDocumentId;fault('WORKFLOW_INVALID','This task already adopted another candidate.');}
    this.assertFresh(r);if(r.config.template!=='new-article'||r.state!=='waiting-approval'||!r.candidateIds.includes(artifactId))fault('WORKFLOW_PERMISSION','Choose a final current candidate at the author adoption gate.');const art=this.artifact(artifactId);if(art.runId!==id||art.epoch!==r.epoch||!art.parentIds.includes(r.selectedOutlineId!))fault('STALE_REVISION','Candidate belongs to an older outline.');
    const value=art.value as {output:DraftOutput;request:WorkflowContentRequest};validateWorkflowOutput(value.output,value.request);this.host.sources.verifyContext(value.request.sources);const doc=this.host.createDocument(value.output.title,renderWorkflowDraft(value.output,value.request.sources));if(r.config.profileId)this.host.memory.attach(doc.id,r.config.profileId);if(r.config.intent)this.host.memory.saveIntent(doc.id,r.config.intent);
    r.adoptedDocumentId=doc.id;r.state='completed';r.grantId=null;r.notice='Author adopted this candidate; not published externally.';this.write(r);this.event(id,'adopted',{artifactId,documentId:doc.id});return doc.id;
  });}
  finish(id:string):void{this.tx(()=>{const r=this.run(id);this.free(id);if(r.state!=='waiting-approval'||r.config.template==='new-article')fault('WORKFLOW_INVALID','Use candidate adoption for new articles.');r.state='completed';r.grantId=null;r.notice='Task closed. Pending changes still need independent author decisions.';this.write(r);this.event(id,'closed-without-text-approval',{});});}
}
