// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {Workspace} from '@writer-agent/storage';
import {captureAnalysisRequest} from '@writer-agent/core';
import {scripted,runAnalysis} from './analysis-helpers.js';
const {DesktopApplication}=await import(new URL('../../apps/cli/dist/application/desktop.js',import.meta.url).href) as typeof import('../../apps/cli/src/application/desktop.js');
const {ConnectionStore}=await import(new URL('../../apps/cli/dist/application/presets.js',import.meta.url).href) as typeof import('../../apps/cli/src/application/presets.js');
function setup(t:test.TestContext){const root=mkdtempSync(join(tmpdir(),'siglum-desktop-test-')),w=Workspace.create(join(root,'writing')),d=w.createDocument('Test','The tool may help. The limits remain.');t.after(()=>{w.close();rmSync(root,{recursive:true,force:true,maxRetries:4,retryDelay:50});});const r=w.currentRevision(d.id),b=r.snapshot.blocks[0]!;w.ranges.create(d.id,r.id,[{blockId:b.id,start:9,end:12,before:'may',after:'could',summary:'tentative wording',dependsOn:[],group:null},{blockId:b.id,start:30,end:36,before:'remain',after:'apply',summary:'wording',dependsOn:[],group:null}]);return {root,w,d,ops:w.ranges.list(d.id)};}
test('range review combines independently selected ranges without duplicate blocks',async t=>{const {w,d,ops}=setup(t);const req=w.analysis.prepare(d.id,'semantic-review',{instruction:'Review changes.',rangeOperationIds:ops.map(o=>o.id)});assert.equal(req.before.blocks.length,1);assert.equal(req.after?.blocks[0]?.text,'The tool could help. The limits apply.');captureAnalysisRequest(req);const report=await runAnalysis(w,req,scripted());assert.equal(report.freshness,'current');assert.equal(w.markdown(d.id),'The tool may help. The limits remain.');});
test('rejecting a selected range invalidates analysis without changing document head',async t=>{const {w,d,ops}=setup(t),head=w.currentRevision(d.id).id;const req=w.analysis.prepare(d.id,'semantic-review',{instruction:'Review.',rangeOperationIds:[ops[0]!.id]});const report=await runAnalysis(w,req,scripted());w.ranges.decide(d.id,[ops[0]!.id],'reject',head);assert.equal(w.currentRevision(d.id).id,head);assert.equal(w.analysis.report(report.id).freshness,'stale');});
test('remaining range review maps after another independent range accepted',t=>{const {w,d,ops}=setup(t);w.ranges.decide(d.id,[ops[0]!.id],'accept',w.currentRevision(d.id).id);const req=w.analysis.prepare(d.id,'semantic-review',{instruction:'Review.',rangeOperationIds:[ops[1]!.id]});assert.equal(req.before.blocks[0]?.text,'The tool could help. The limits remain.');assert.equal(req.after?.blocks[0]?.text,'The tool could help. The limits apply.');});
test('malformed range review cannot bypass generic request validation',t=>{const {w,d,ops}=setup(t);const req=w.analysis.prepare(d.id,'semantic-review',{instruction:'Review.',rangeOperationIds:[ops[0]!.id]});assert.throws(()=>captureAnalysisRequest({...req,rangeOperationIds:['wrong']}));assert.throws(()=>captureAnalysisRequest(JSON.parse(JSON.stringify({...req,changes:null}))));});
test('a late review result after range rejection is refused atomically',async t=>{const {w,d,ops}=setup(t);const req=w.analysis.prepare(d.id,'semantic-review',{instruction:'Review.',rangeOperationIds:[ops[0]!.id]});const p=scripted(async()=>{w.ranges.decide(d.id,[ops[0]!.id],'reject',w.currentRevision(d.id).id);return {providerId:'test/fake',output:{},usage:null};});await assert.rejects(runAnalysis(w,req,p));assert.equal(w.analysis.runs(d.id).length,0);});
test('desktop service rejects filesystem, shell, SQL and Git requests',async t=>{const root=mkdtempSync(join(tmpdir(),'siglum-desktop-app-')),a=new DesktopApplication(new ConnectionStore(join(root,'connections')));t.after(async()=>{await a.close();rmSync(root,{recursive:true,force:true});});for(const method of ['readFile','exec','sql','git','openWorkspace'])await assert.rejects(a.request(method,{path:'/etc/passwd'}));const o=await a.request('overview') as {workspace:unknown;presets:unknown[]};assert.equal(o.workspace,null);assert.deepEqual(o.presets,[]);});
test('desktop drafts persist separately and stale buffer saves do not overwrite',async t=>{const root=mkdtempSync(join(tmpdir(),'siglum-desktop-buffer-')),a=new DesktopApplication(new ConnectionStore(join(root,'connections')));t.after(async()=>{await a.close();rmSync(root,{recursive:true,force:true});});a.openWorkspace(join(root,'writing'),true);const d=a.importDocument('Article','Original text.');const state=await a.request('document',{id:d.id}) as {revision:{id:string;snapshot:{blocks:{id:string}[]}}};const input={documentId:d.id,baseRevisionId:state.revision.id,expectedVersion:0,blocks:[{blockId:state.revision.snapshot.blocks[0]!.id,text:'My manual draft.'}]};await a.request('bufferSave',input);assert.equal(a.exportDocument(d.id),'Original text.');await assert.rejects(a.request('bufferSave',input));await a.request('bufferCommit',{documentId:d.id,head:state.revision.id,bufferVersion:1});assert.equal(a.exportDocument(d.id),'My manual draft.');});
test('desktop missing preset does not dispatch or save a preview',async t=>{const root=mkdtempSync(join(tmpdir(),'siglum-desktop-preview-')),a=new DesktopApplication(new ConnectionStore(join(root,'connections')));t.after(async()=>{await a.close();rmSync(root,{recursive:true,force:true});});a.openWorkspace(join(root,'writing'),true);const d=a.importDocument('Draft','Words.');await assert.rejects(a.request('suggestPreview',{documentId:d.id,instruction:'Edit',selection:{snapshots:[],excerpts:[]},presetId:'missing'}));assert.equal(a.activeJobs,0);assert.equal(a.exportDocument(d.id),'Words.');await assert.rejects(a.request('previewSend',{id:'missing',fingerprint:'none'}));});
