// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync, symlinkSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { hashBytes, parseSkillFrontmatter, makeSkillPackage, validateWorkflowExtensions, validateMcpConnection, inspectToolSchema, validateToolArguments, toolHeaders, headerValue, indexResearch, planEvidence, lineRange, mapCitations, renderCitedDraft, joinChapterDrafts, rankDiscoveries, validateWorkflowRequest } from '@writer-agent/core';
import type { DraftOutput, SourceContextItem, SearchResult } from '@writer-agent/core';
import { temporary, fixture } from './helpers.js';
import { skillPackage, readSkillDirectory, fictionalText, stdioConfig } from './extensions-helpers.js';
import { workflowConfig } from './workflow-helpers.js';

function draft(markdown:string,citations:DraftOutput['citations']):DraftOutput{return {protocolVersion:1,task:'draft',runId:'run1',requestId:'req1',title:'Synthetic draft',markdown,citations,limitations:[]};}
function source(text:string,id='a'):SourceContextItem{return {sourceId:`src-${id}`,snapshotId:`snap-${id}`,excerptId:`ex-${id}`,locator:'reference.txt',title:null,textHash:hashBytes(text),contentHash:hashBytes(text),startLine:1,endLine:1,text};}

test('Skill official field subset, quoted scalars and metadata preserve original saved bytes',()=>{const text='\ufeff---\r\nname: writing-method\r\ndescription: >-\r\n  Method for\r\n  selected writing.\r\nlicense: "Apache-2.0"\r\nmetadata:\r\n  author: \'Example\'\r\n---\r\nInstructions 😀\r\n';const p=makeSkillPackage('writing-method',[{path:'SKILL.md',text,hash:hashBytes(text)}]);assert.equal(p.metadata.description,'Method for selected writing.');assert.equal(p.files[0]!.text,text);assert.match(p.body,/Instructions 😀/);});
for(const bad of ['---\nname: x\nname: y\ndescription: d\n---\nbody','---\nname: x\ndescription: *alias\n---\nbody','---\nname: Bad_Name\ndescription: x\n---\nbody','---\nname: x\ndescription: d\nunknown: yes\n---\nbody'])test(`Skill refuses invalid metadata ${hashBytes(bad).slice(0,8)}`,()=>assert.throws(()=>parseSkillFrontmatter(bad)));
test('Skill imports reject unsafe paths, scripts, hash changes and case collisions',()=>{for(const path of ['../x.md','/x.md','a\\x.md','CON.md','x:secret.md','scripts/run.md'])assert.throws(()=>makeSkillPackage('source-check',[...skillPackage().files,{path,text:'x',hash:hashBytes('x')}]));assert.throws(()=>makeSkillPackage('source-check',[...skillPackage().files,{path:'skill.md',text:'x',hash:hashBytes('x')}]));const p=skillPackage();p.files[0]!.text+='tampered';assert.throws(()=>makeSkillPackage('source-check',p.files));});
test('Explicit local skill import is bounded and never executes scripts',t=>{const root=join(temporary(t),'source-check');mkdirSync(root);const p=skillPackage();writeFileSync(join(root,'SKILL.md'),p.files[0]!.text);assert.equal(readSkillDirectory(root).metadata.name,'source-check');mkdirSync(join(root,'scripts'));writeFileSync(join(root,'scripts','run.mjs'),`require('fs').writeFileSync('BAD','x')`);assert.throws(()=>readSkillDirectory(root));assert.equal(existsSync(join(root,'BAD')),false);});
test('Skill directory symlinks are refused before import',t=>{const parent=temporary(t),root=join(parent,'source-check');mkdirSync(root);writeFileSync(join(root,'SKILL.md'),skillPackage().files[0]!.text);const external=join(parent,'private');mkdirSync(external);symlinkSync(external,join(root,'outside'),'junction');assert.throws(()=>readSkillDirectory(root));});
test('MCP config refuses implicit installers, unsafe secrets/options, HTTP without authorization',()=>{const base=stdioConfig();for(const command of ['npx','C:\\bin\\npx.exe','C:\\bin\\cmd.exe','C:\\tools\\start.cmd'])assert.throws(()=>validateMcpConnection({...base,command}));assert.throws(()=>validateMcpConnection({...base,env:['NODE_OPTIONS']}));for(const url of ['http://example.org/mcp','https://user:secret@example.org','https://example.org/?token=x','file:///data'])assert.throws(()=>validateMcpConnection({name:'x',protocol:'2026-07-28',transport:'http',url,tokenEnv:null,allowRemote:true,timeoutMs:1000}));});
test('Workflow extension schema refuses hidden authority and excessive selections',()=>{assert.throws(()=>validateWorkflowExtensions({skills:[],calls:[],chapterDrafting:false,autoApprove:true}));assert.throws(()=>validateWorkflowExtensions({skills:[],calls:[{serverId:'x',catalogId:'x',kind:'tool',name:'delete',arguments:{},permission:'write'}],chapterDrafting:false}));});
test('Bounded schema checks actual types, counts, objects, local references and unions',()=>{const s={type:'object',properties:{n:{$ref:'#/$defs/count'},label:{oneOf:[{const:'a'},{const:'b'}]},items:{type:'array',items:{type:'string',minLength:2},uniqueItems:true,maxItems:2}},$defs:{count:{type:'integer',minimum:1,maximum:5}},required:['n','label'],additionalProperties:false};inspectToolSchema(s);validateToolArguments(s,{n:2,label:'a',items:['😀a']});for(const v of [{n:0,label:'a'},{n:2,label:'c'},{n:2,label:'a',extra:true},{n:2,label:'a',items:['aa','aa']},{n:2.5,label:'b'}])assert.throws(()=>validateToolArguments(s,v));});
test('Unsupported schema assertions/remote refs/cycles fail closed rather than weakly validate',()=>{for(const s of [{type:'string',pattern:'.*'},{$ref:'https://example.org/schema'},{type:'string',format:'uri'},{$defs:{loop:{$ref:'#/$defs/loop'}},$ref:'#/$defs/loop'},{type:'array',items:[{type:'string'}]}])assert.throws(()=>inspectToolSchema(s));});
test('Boolean schemas and tuple prefix semantics remain precise',()=>{validateToolArguments(true,{x:1});assert.throws(()=>validateToolArguments(false,{}));const s={type:'array',prefixItems:[{type:'string'},{type:'integer'}],items:false};validateToolArguments(s,['x',2]);assert.throws(()=>validateToolArguments(s,['x',2,3]));});
test('Modern header mirror encodes Unicode and prevents header/sentinel injection',()=>{const s={type:'object',properties:{q:{type:'string','x-mcp-header':'query'},n:{type:'integer','x-mcp-header':'count'}}};const h=toolHeaders(s,{q:'内容\r\nX-Injected: 1',n:3});assert.equal(h['Mcp-Param-query'],headerValue('内容\r\nX-Injected: 1'));assert.doesNotMatch(h['Mcp-Param-query']!,/[\r\n]/);assert.equal(h['Mcp-Param-count'],'3');assert.notEqual(headerValue('=?base64?abc?='),'=?base64?abc?=');assert.throws(()=>toolHeaders({type:'object',properties:{a:{type:'string','x-mcp-header':'same'},b:{type:'string','x-mcp-header':'Same'}}},{}));});
test('Research indexes the tail, retrieves relevant evidence plus qualifying context',()=>{const index=indexResearch('snap',fictionalText),plan=planEvidence(index,fictionalText,'battery endurance',8000,2);const text=plan.windows.map(w=>lineRange(fictionalText,w.startLine,w.endLine).quote).join('\n');assert.match(text,/12 percent/);assert.match(text,/no causal conclusion/);assert.match(text,/colder conditions/);assert.ok(plan.windows.some(w=>w.startLine>40));assert.equal(plan.indexedEntireText,true);assert.equal(plan.modelReadEntireText,false);});
test('Research Chinese, emoji and CRLF coordinates map to exact original text',()=>{const text='序言😀\r\n\r\n无关事项\r\n\r\n## 电池续航\r\n电池续航提高，但不能推断因果。\r\n限制：样本只有六个。';const index=indexResearch('s',text);for(const c of index.chunks){assert.equal(text.slice(c.start,c.end),c.quote);assert.equal(hashBytes(c.quote),c.quoteHash);}const p=planEvidence(index,text,'电池续航');assert.ok(p.windows.length);assert.match(p.windows.map(w=>lineRange(text,w.startLine,w.endLine).quote).join(''),/限制/);});
test('Oversized important passage is refused, not clipped, and no-match is labelled',()=>{const text='header\n'+'battery '.repeat(3000),i=indexResearch('s',text),p=planEvidence(i,text,'battery',256);assert.equal(p.windows.length,0);assert.ok(p.warnings.some(w=>w.includes('exceed')));const empty=planEvidence(indexResearch('x','nothing here'),'nothing here','未知的主题');assert.match(empty.warnings[0]!,/No literal/);});
test('Index detects changed source and evidence budget constraints',()=>{const index=indexResearch('s','a\n\nb');assert.throws(()=>planEvidence(index,'changed','a'));assert.throws(()=>planEvidence(index,'a\n\nb','a',0));});
test('Source ranking explains normalized URL and snippet duplicates without truth scores',()=>{const repeated='long repeated text '.repeat(20);const r:SearchResult={query:'battery',requestId:null,credits:null,results:[{id:'1',title:'Battery',url:'https://a.example.org/x#p',snippet:repeated,score:null},{id:'2',title:'Other',url:'https://a.example.org/x',snippet:'other',score:null},{id:'3',title:'Battery',url:'https://b.example.org/y',snippet:repeated,score:null},{id:'4',title:'Battery limits',url:'https://c.example.org/z',snippet:'Contrary evidence',score:null}],provider:'tavily',discoveredAt:'2026-01-01'} as SearchResult;const result=rankDiscoveries([r],[],5,'battery');assert.equal(result.selected.length,2);assert.equal(result.excluded.length,2);assert.equal(result.interpretation,'retrieval-order-not-truth-rating');assert.ok(result.selected.every(s=>s.publishedAt===null));});
test('Citation render renumbers by appearance and maps exact adopted offsets',()=>{const sources=[source('alpha','a'),source('beta','b')],d=draft('Second claim.[^S2]\nFirst claim.[^S1]',[{itemIndex:0,start:0,end:5,quote:'alpha'},{itemIndex:1,start:0,end:4,quote:'beta'}]);const r=renderCitedDraft(d,sources);assert.match(r.markdown,/Second claim\.\[\^S1\]/);assert.equal(r.map.manuscriptHash,hashBytes(r.markdown));for(const b of r.map.bindings){assert.equal(r.markdown.slice(b.markerStart,b.markerEnd),b.marker);assert.equal(r.markdown.slice(b.sentenceStart,b.sentenceEnd),b.sentence);}assert.equal(r.map.bindings[0]!.snapshotId,'snap-b');});
test('Citation validation rejects invalid index, missing/unused quote and split surrogate',()=>{const s=[source('😀a')];for(const d of [draft('Claim.[^S1]',[]),draft('Claim.',[{itemIndex:0,start:0,end:2,quote:'😀'}]),draft('Claim.[^S0]',[]),draft('Claim.[^S2]',[{itemIndex:0,start:0,end:2,quote:'😀'}]),draft('Claim.[^S1]',[{itemIndex:0,start:0,end:1,quote:'\ud83d'}])])assert.throws(()=>mapCitations(d,s));});
test('Chapter assembly remaps local indices to stable master evidence',()=>{const master=[source('alpha','a'),source('beta','b')];const d=draft('Text.[^S1]',[{itemIndex:0,start:0,end:4,quote:'beta'}]);const joined=joinChapterDrafts('Title',[{heading:'Tail chapter',draft:d,sources:[master[1]!]}],master,{runId:'run1',requestId:'joined'});assert.match(joined.markdown,/\[\^S2\]/);assert.equal(joined.citations[0]!.itemIndex,1);assert.equal(mapCitations(joined,master).bindings[0]!.snapshotId,'snap-b');});
test('Public query protocol cannot carry skill/private guidance fields',()=>{assert.throws(()=>validateWorkflowRequest({protocolVersion:1,task:'query-plan',runId:'r',requestId:'q',publicBrief:'public',language:'en',maxQueries:1,skills:[]}));});
test('Legacy workflow configs remain unchanged and extension opt-in is explicit',t=>{const {workspace:w}=fixture(t);const c=workflowConfig(),r=w.workflows.create(c);assert.equal(Object.hasOwn(r.capture,'extensions'),false);const newRun=w.workflows.create({...c,extensions:{skills:[],calls:[],chapterDrafting:false}});assert.equal(newRun.capture.extensions?.version,'extensions-v1');});

test('Citation-map fanout is bounded and does not allocate an unbounded repeated marker graph',()=>{const s=[source('quote')],d=draft('Sentence.[^S1]\n'.repeat(513),[{itemIndex:0,start:0,end:5,quote:'quote'}]);assert.throws(()=>mapCitations(d,s),/limit/);});
test('Long headings remain bounded navigation labels without changing source text coordinates',()=>{const text='# '+'LongHeading'.repeat(1000)+'\n\n'+'battery observations\n\n'.repeat(500);const index=indexResearch('s',text);assert.ok(index.chunks.every(c=>c.heading.length<=257));for(const c of index.chunks)assert.equal(text.slice(c.start,c.end),c.quote);});
test('Missing-digit, negative and leading-zero source markers are refused explicitly',()=>{for(const m of ['[^S]','[^S-1]','[^S01]'])assert.throws(()=>mapCitations(draft('Text.'+m,[]),[source('text')]));});
test('Unsupported older schema dialect is excluded rather than validated under newer tuple semantics',()=>{assert.throws(()=>inspectToolSchema({$schema:'http://json-schema.org/draft-07/schema#',type:'object'}));});

test('Windows ambiguous trailing-dot directory components in skill paths are refused',()=>{for(const path of ['references./note.md','references/note.','dir../note.md'])assert.throws(()=>makeSkillPackage('source-check',[...skillPackage().files,{path,text:'x',hash:hashBytes('x')}]));});
test('Chapter joining refuses excessive unique caveats instead of losing qualification notices',()=>{const parts=Array.from({length:3},(_,i)=>({heading:`Section ${i}`,draft:{...draft('Uncited synthetic discussion.',[]),limitations:Array.from({length:8},(_,j)=>`Qualification ${i}-${j}`)},sources:[]}));assert.throws(()=>joinChapterDrafts('Example',parts,[],{runId:'run',requestId:'req'}),/none were silently dropped/);});
