// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, copyFileSync } from 'node:fs';
import { join } from 'node:path';
import { McpClient, mcpLaunchHash, stdioConfig, httpFixture, approved, fictionalText, fixturePath } from './extensions-helpers.js';
import { temporary } from './helpers.js';
import { headerValue } from '@writer-agent/core';
import type { McpConnection } from '@writer-agent/core';

for(const protocol of ['2026-07-28','2025-11-25'] as const)test(`Real stdio MCP ${protocol} discovers, calls, reads and closes`,async()=>{
  const config=stdioConfig('normal',protocol),hash=await mcpLaunchHash(config),client=new McpClient(config,hash);
  try{const catalog=await client.discover();assert.equal(catalog.tools[0]!.name,'lookup');assert.equal(catalog.resources[0]!.uri,'memory://fiction/reference');const tool=await client.execute(approved(config,hash,catalog));assert.equal(tool.text,fictionalText);assert.equal(tool.interpretation,'external-service-unverified');const resource=await client.execute(approved(config,hash,catalog,true));assert.equal(resource.text,fictionalText);}finally{await client.close();await client.close();}
});
for(const protocol of ['2026-07-28','2025-11-25'] as const)for(const sse of [false,true])test(`Real HTTP MCP ${protocol}, ${sse?'SSE':'JSON'} validates transport identity/headers`,async()=>{
  const fixture=await httpFixture({sse}),config={...fixture.config,protocol},hash=await mcpLaunchHash(config),client=new McpClient(config,hash);
  try{const cat=await client.discover();const call=approved(config,hash,cat);call.arguments={query:'电池续航',limit:2};const result=await client.execute(call);assert.match(result.text,/12 percent/);const request=fixture.calls.find(c=>c.message.method==='tools/call')!;assert.equal(request.headers['mcp-protocol-version'],protocol);assert.equal(request.headers.authorization,undefined);if(protocol==='2026-07-28'){assert.equal(request.headers['mcp-method'],'tools/call');assert.equal(request.headers['mcp-name'],'lookup');assert.equal(request.headers['mcp-param-query'],headerValue('电池续航'));assert.equal((request.message.params as {_meta:Record<string,unknown>})._meta['io.modelcontextprotocol/protocolVersion'],protocol);}else assert.equal(request.headers['mcp-session-id'],'synthetic-session');}finally{await client.close();await fixture.close();}
});
test('MCP launch fingerprint includes actual installed script and detects change without running',async t=>{const dir=temporary(t),script=join(dir,'server with spaces.mjs');copyFileSync(fixturePath,script);const config=stdioConfig() as Extract<McpConnection,{transport:'stdio'}>;config.args=[script];config.cwd=dir;const before=await mcpLaunchHash(config);writeFileSync(script,readFileSync(script,'utf8')+'\n// Changed\n');const client=new McpClient(config,before);try{await assert.rejects(client.connect(),{code:'MCP_CHANGED'});}finally{await client.close();}});
test('Relative direct script arguments are fingerprinted against explicit cwd too',async t=>{const dir=temporary(t),script=join(dir,'server.mjs');copyFileSync(fixturePath,script);const config=stdioConfig() as Extract<McpConnection,{transport:'stdio'}>;config.args=['server.mjs'];config.cwd=dir;const before=await mcpLaunchHash(config);writeFileSync(script,'// altered');assert.notEqual(await mcpLaunchHash(config),before);});
test('Stdio child environment excludes private keys unless explicitly named',async()=>{process.env.SIGLUM_PRIVATE_TEST_KEY='not-a-real-secret';process.env.SIGLUM_APPROVED_TEST_ENV='explicit-synthetic-value';const config=stdioConfig('environment') as Extract<McpConnection,{transport:'stdio'}>;config.env=['SIGLUM_APPROVED_TEST_ENV'];const hash=await mcpLaunchHash(config),c=new McpClient(config,hash);try{const cat=await c.discover(),r=await c.execute(approved(config,hash,cat));assert.deepEqual(JSON.parse(r.text),{unapproved:null,approved:'explicit-synthetic-value'});}finally{await c.close();delete process.env.SIGLUM_PRIVATE_TEST_KEY;delete process.env.SIGLUM_APPROVED_TEST_ENV;}});
test('Stdio framing supports fragmented messages rather than assuming one data event',async()=>{const config=stdioConfig('fragmented'),hash=await mcpLaunchHash(config),c=new McpClient(config,hash);try{assert.equal((await c.discover()).tools.length,1);}finally{await c.close();}});
test('MCP pagination is followed with explicit returned cursors',async()=>{const f=await httpFixture({mode:'pagination'}),h=await mcpLaunchHash(f.config),c=new McpClient(f.config,h);try{const catalog=await c.discover();assert.equal(catalog.tools.length,2);const lists=f.calls.filter(x=>x.message.method==='tools/list');assert.equal(lists.length,2);assert.equal((lists[1]!.message.params as {cursor:string}).cursor,'page2');}finally{await c.close();await f.close();}});
for(const mode of ['repeat-cursor','too-many','wrong-id'])test(`MCP rejects malformed discovery: ${mode}`,async()=>{const f=await httpFixture({mode}),c=new McpClient(f.config,await mcpLaunchHash(f.config));try{await assert.rejects(c.discover());assert.equal(f.calls.filter(x=>x.message.method==='tools/call').length,0);}finally{await c.close();await f.close();}});
test('Unsupported JSON Schema tools are excluded, not treated as validated',async()=>{const f=await httpFixture({mode:'unsupported-schema'}),c=new McpClient(f.config,await mcpLaunchHash(f.config));try{const catalog=await c.discover();assert.equal(catalog.tools.length,0);assert.equal(catalog.excluded.length,1);}finally{await c.close();await f.close();}});
test('Descriptor change under same tool name blocks call before dispatch',async()=>{let changed=false;const f=await httpFixture({mutate:(r,m)=>{if(changed&&m.method==='tools/list'){const v=r as {result:{tools:{description:string}[]}};v.result.tools[0]!.description='New behavior';}return r;}}),h=await mcpLaunchHash(f.config),c=new McpClient(f.config,h);try{const cat=await c.discover();changed=true;await assert.rejects(c.execute(approved(f.config,h,cat)),{code:'MCP_CHANGED'});assert.equal(f.calls.filter(x=>x.message.method==='tools/call').length,0);}finally{await c.close();await f.close();}});
for(const [mode,code]of [['binary','MCP_CONTENT_UNSUPPORTED'],['tool-error','MCP_TOOL_ERROR'],['interaction','MCP_INTERACTION_UNSUPPORTED'],['error','MCP_REMOTE_ERROR'],['callback','MCP_INTERACTION_UNSUPPORTED'],['oversize','MCP_LIMIT']] as const)test(`MCP tool ${mode} is refused without executing follow-up requests`,async()=>{const config=stdioConfig(mode),h=await mcpLaunchHash(config),c=new McpClient(config,h);try{const cat=await c.discover();await assert.rejects(c.execute(approved(config,h,cat)),{code});}finally{await c.close();}});
test('Remote JSON error does not reflect response body or private message',async()=>{const f=await httpFixture({mode:'error'}),h=await mcpLaunchHash(f.config),c=new McpClient(f.config,h);try{const cat=await c.discover();await assert.rejects(c.execute(approved(f.config,h,cat)),e=>{assert.doesNotMatch(String(e),/PRIVATE_REMOTE_ERROR_BODY/);return true;});}finally{await c.close();await f.close();}});
for(const status of [401,429,302,500])test(`HTTP ${status} stops without redirect/retry`,async()=>{const f=await httpFixture({status}),c=new McpClient(f.config,await mcpLaunchHash(f.config));try{await assert.rejects(c.discover());assert.equal(f.calls.length,1);}finally{await c.close();await f.close();}});
test('MCP duplicate JSON keys are refused before accepting result',async()=>{const f=await httpFixture({raw:'{"jsonrpc":"2.0","id":1,"id":2,"result":{}}'}),c=new McpClient(f.config,await mcpLaunchHash(f.config));try{await assert.rejects(c.discover(),{code:'MCP_INVALID_RESPONSE'});}finally{await c.close();await f.close();}});
test('Modern server discovery metadata may be omitted without inventing identity',async()=>{const f=await httpFixture({mutate:r=>{delete(r as {result:{_meta?:unknown}}).result._meta;return r;}}),c=new McpClient(f.config,await mcpLaunchHash(f.config));try{assert.equal((await c.discover()).tools.length,1);}finally{await c.close();await f.close();}});
test('Timeout does not silently repeat tool request',async()=>{const f=await httpFixture({mode:'timeout'}),config={...f.config,timeoutMs:200},h=await mcpLaunchHash(config),c=new McpClient(config,h);try{const cat=await c.discover();await assert.rejects(c.execute(approved(config,h,cat)),{code:'MCP_TIMEOUT'});assert.equal(f.calls.filter(x=>x.message.method==='tools/call').length,1);}finally{await c.close();await f.close();}});
test('Cancellation closes outstanding stdio request without automatic restart',async()=>{const config={...stdioConfig('timeout'),timeoutMs:2000},h=await mcpLaunchHash(config),c=new McpClient(config,h);try{const cat=await c.discover(),ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),100);try{await assert.rejects(c.execute(approved(config,h,cat),ctrl.signal),{code:'MCP_CANCELLED'});}finally{clearTimeout(timer);}}finally{await c.close();}});
test('Resource result cannot substitute a different, unapproved URI',async()=>{const f=await httpFixture({mutate:(r,m)=>{if(m.method==='resources/read')(r as {result:{contents:{uri:string}[]}}).result.contents[0]!.uri='file:///private';return r;}}),h=await mcpLaunchHash(f.config),c=new McpClient(f.config,h);try{const cat=await c.discover();await assert.rejects(c.execute(approved(f.config,h,cat,true)),{code:'MCP_CONTENT_UNSUPPORTED'});}finally{await c.close();await f.close();}});
