// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { Workspace } from '@writer-agent/storage';
import { temporary, fixture } from './helpers.js';
import { stdioConfig, runExtensionsGuide, selectWorkflowExtensions, skillPackage, fictionalText } from './extensions-helpers.js';
import type { WizardIO } from '../../apps/cli/src/terminal.js';
const cli=fileURLToPath(new URL('../../apps/cli/dist/index.js',import.meta.url)),example=fileURLToPath(new URL('../../examples/skills/source-check',import.meta.url));
function run(a:string[]){return spawnSync(process.execPath,[cli,...a],{encoding:'utf8',timeout:20000,env:{...process.env,SIGLUM_PRIVATE_TEST:'DO_NOT_INHERIT'}});}
function good(a:string[]){const r=run(a);assert.equal(r.status,0,r.stdout+'\n'+r.stderr);return r.stdout;}
function io(answers:string[]){const output:string[]=[];const input:WizardIO={ask:async prompt=>{output.push(prompt);if(!answers.length)throw Error('No more scripted input');return answers.shift()!;},line:text=>output.push(text)};return {input,output};}
for(const family of ['extensions','skill','mcp','research','citations'])test(`${family} help needs no workspace/key and describes explicit trust`,()=>{assert.match(good([family,'help']),/no automatic script installation/);});
test('Skill CLI previews then imports disabled, enables explicitly and exposes selected exact reference',t=>{const root=join(temporary(t),'中文 extension workspace'),w=Workspace.create(root);w.close();const preview=JSON.parse(good(['skill','import',root,example]));assert.equal(preview.preview,true);assert.deepEqual(JSON.parse(good(['skill','list',root])),[]);const s=JSON.parse(good(['skill','import',root,example,'--apply']));assert.equal(JSON.parse(good(['skill','list',root]))[0].enabled,false);good(['skill','enable',root,s.id]);assert.equal(JSON.parse(good(['skill','list',root]))[0].enabled,true);const refs=JSON.parse(good(['skill','read',root,s.id,'references/checklist.md','1','2']));assert.equal(refs[0].references[0].startLine,1);good(['skill','disable',root,s.id]);assert.notEqual(run(['skill','read',root,s.id,'references/checklist.md','1','2']).status,0);});
test('MCP CLI preview/register does not launch, trust is fingerprint bound and explicit discovery runs fixture only',t=>{const root=join(temporary(t),'mcp workspace'),w=Workspace.create(root);w.close();const configFile=join(temporary(t),'connection.json');writeFileSync(configFile,JSON.stringify(stdioConfig()));assert.equal(JSON.parse(good(['mcp','register',root,configFile])).preview,true);assert.deepEqual(JSON.parse(good(['mcp','list',root])),[]);const s=JSON.parse(good(['mcp','register',root,configFile,'--apply']));assert.equal(JSON.parse(good(['mcp','discover',root,s.id])).networkOrProcessStarted,false);assert.notEqual(run(['mcp','discover',root,s.id,'--connect']).status,0);assert.notEqual(run(['mcp','trust',root,s.id,'wrong']).status,0);good(['mcp','trust',root,s.id,s.launchHash]);assert.equal(JSON.parse(good(['mcp','discover',root,s.id,'--connect'])).catalog.tools[0].name,'lookup');good(['mcp','revoke',root,s.id]);assert.notEqual(run(['mcp','discover',root,s.id,'--connect']).status,0);});
test('CLI rejects unknown and partial flags rather than silently sending/registering',t=>{const {workspace:w}=fixture(t);for(const args of [['skill','import',w.root,example,'--send'],['mcp','discover',w.root,'unknown','--yes'],['extensions','call',w.root],['citations','export',w.root],['research','query',w.root,'x']])assert.notEqual(run(args).status,0);});
test('Evidence CLI finds a late synthetic passage without calling a provider or altering the source',t=>{const {workspace:w}=fixture(t),s=w.sources.add({kind:'file',locator:'late.txt',raw:Buffer.from(fictionalText),mediaType:'text/plain'});const old=s.snapshot.textHash;const result=JSON.parse(good(['research','query',w.root,s.snapshot.id,'battery endurance']));assert.ok(result.items[0].startLine>40);assert.equal(w.sources.snapshot(s.snapshot.id).textHash,old);});
test('Citation export refuses an existing destination',t=>{const {workspace:w,document:d}=fixture(t),path=join(temporary(t),'keep.json');writeFileSync(path,'KEEP');assert.notEqual(run(['citations','export',w.root,d.id,path]).status,0);assert.equal(readFileSync(path,'utf8'),'KEEP');});
test('Extension guide refuses noninteractive stdin without hanging or auto-approving',t=>{const {workspace:w}=fixture(t);const r=run(['extensions','guide',w.root,'--lang','zh-CN']);assert.notEqual(r.status,0);assert.match(r.stderr,/TTY|terminal|终端/i);assert.deepEqual(w.extensions.servers(),[]);});
test('Numbered guide exits and empty selections do not activate any capability',async t=>{const {workspace:w}=fixture(t),first=io(['0']);await runExtensionsGuide(w,first.input,'zh-CN');assert.match(first.output.join('\n'),/Siglum 工具与研究/);const second=io(['0','n','n']);const selected=await selectWorkflowExtensions(w,second.input,'en',true);assert.deepEqual(selected,{skills:[],calls:[],chapterDrafting:false});});
test('Cancelling skill activation keeps imported text disabled',async t=>{const {workspace:w}=fixture(t),s=w.extensions.importSkill(skillPackage()),input=io(['1','1','n','0']);await runExtensionsGuide(w,input.input,'en');assert.equal(w.extensions.skillEnabled(s.id),false);});

test('Paired extension guides retain exact shell/JSON examples and declare installed SDK plus host restrictions',()=>{const docs=fileURLToPath(new URL('../../docs/',import.meta.url));const en=readFileSync(join(docs,'extensions.md'),'utf8'),zh=readFileSync(join(docs,'extensions.zh-CN.md'),'utf8');const examples=(text:string)=>[...text.matchAll(/```(?:sh|json)\n([\s\S]*?)```/g)].map(m=>m[1]);assert.deepEqual(examples(en),examples(zh));assert.match(en,/pinned official SDK2\.0\.0/);assert.match(zh,/官方 MCP SDK2\.0\.0/);assert.doesNotMatch(readFileSync(fileURLToPath(new URL('../../README.md',import.meta.url)),'utf8'),/No background learning, fine-tuning, vectors or Skills\/MCP execution/);});
