// SPDX-License-Identifier: Apache-2.0
import assert from 'node:assert/strict';
import test from 'node:test';
import {buildMemoryPlan,validateIntentCard,validatePreferenceInput,normalizeMemoryOptions,validateMemoryPacket,validateMemoryTaskOutput,captureMemoryTask,checkWritingRules} from '@writer-agent/core';
import type {PreferenceVersion,MemoryOptions,WritingRule,MemoryTaskRequest,IntentVersion} from '@writer-agent/core';
import {card,pref,memoryFixture} from './memory-helpers.js';
const profile={id:'p',name:'Draft test profile',createdAt:'2026-09-15'};
const preference=(i:number,patch:Partial<PreferenceVersion>={}):PreferenceVersion=>({...pref(),id:`v${String(i).padStart(3,'0')}`,preferenceId:`r${String(i).padStart(3,'0')}`,profileId:'p',previousId:null,status:'active',origin:'manual',evidenceIds:[],runId:null,reason:'',createdAt:'2026-09-15',...patch});
const intent=(rules:readonly WritingRule[]=[]):IntentVersion=>({id:'i1',documentId:'d',baseRevisionId:'r',parentId:null,card:card({rules}),origin:'manual',runId:null,createdAt:'2026-09-15'});
function plan(p:readonly PreferenceVersion[]=[],options:MemoryOptions={},i:IntentVersion|null=intent()){
  return buildMemoryPlan({documentId:'d',task:'revise',intent:i,profile,preferences:p,bindingId:'bind',activeIntentEvent:'confirm',importantClaims:[],options});
}
test('memory defaults contain no examples and no arbitrary file/history fields',()=>{const p=plan([preference(1,{example:{before:'a',after:'b',reason:'voice'}})]);assert.equal(p.capture.packet.examples.length,0);assert.equal(p.capture.packet.entries.length,1);assert.doesNotMatch(JSON.stringify(p.capture.packet),/"before"|"after"|"apiKey"/);});
for(const status of ['candidate','disabled','dismissed','superseded'] as const)test(`${status} preferences never enter guidance`,()=>assert.equal(plan([preference(1,{status})]).capture.packet.entries.length,0));
for(const patch of [{profileId:'other'},{language:'en' as const},{tasks:['title' as const]}])test(`scope excludes ${JSON.stringify(patch)}`,()=>assert.equal(plan([preference(1,patch)]).capture.packet.entries.length,0));
test('explicit any-language rules apply without inferring language from the computer',()=>{assert.equal(plan([preference(1,{language:'any'})],{},null).capture.packet.entries.length,1);assert.equal(plan([preference(1)],{},null).capture.packet.entries.length,0);});
test('explicit wrong language cannot override a confirmed article language silently',()=>assert.throws(()=>plan([],{language:'en'})));
test('same priority tone conflict is explicit rather than last-write-wins',()=>{const p=plan([preference(1,{rule:{key:'tone',value:'formal',strength:'preferred'}}),preference(2,{rule:{key:'tone',value:'casual',strength:'preferred'}})]);assert.equal(p.conflicts.length,1);});
test('article tone overrides profile tone without mutating the original rule',()=>{const p=preference(1,{rule:{key:'tone',value:'formal',strength:'preferred'}}),b=JSON.stringify(p);const q=plan([p],{},intent([{key:'tone',value:'casual',strength:'preferred'}]));assert.equal(q.capture.packet.entries[0]!.rule.value,'casual');assert.equal(JSON.stringify(p),b);assert.equal(q.excluded[0]!.reason,'overridden-by-more-specific-guidance');});
test('one request exception overrides ordinary intent, never alters the card',()=>{const i=intent([{key:'tone',value:'formal',strength:'preferred'}]);const p=plan([],{exceptions:[{key:'tone',value:'casual',strength:'preferred'}]},i);assert.equal(p.conflicts.length,0);assert.equal(p.capture.packet.entries[0]!.layer,'request');assert.equal(i.card.rules[0]!.value,'formal');});
test('required override needs an exact explicit waiver, not model choice',()=>{const i=intent([{key:'tone',value:'formal',strength:'required'}]),options={exceptions:[{key:'tone',value:'casual',strength:'preferred'}] as WritingRule[]};assert.equal(plan([],options,i).conflicts[0]!.reason,'explicit-required-override-needed');assert.equal(plan([],{...options,waiveRequiredRefs:['i1:rule:0']},i).conflicts.length,0);assert.throws(()=>plan([],{...options,waiveRequiredRefs:['ghost']},i));});
test('free-text conflict resolution is not advertised as semantic inference',()=>{const p=plan([preference(1,{rule:{key:'guidance',value:'use metaphors',strength:'preferred'}}),preference(2,{rule:{key:'guidance',value:'avoid metaphors',strength:'preferred'}})]);assert.equal(p.conflicts.length,0);assert.equal(p.capture.packet.entries.length,2);});
test('stable selection ordering is repeatable with fixed priorities and identities',()=>{const a=preference(1),b=preference(2,{priority:5});assert.deepEqual(plan([a,b]),plan([b,a]));assert.equal(plan([a,b]).capture.packet.entries[0]!.ref,b.id);});
test('optional over-budget preferences are listed as excluded rather than silently sent',()=>{const p=plan(Array.from({length:30},(_,i)=>preference(i)));assert.equal(p.capture.packet.entries.length,20);assert.equal(p.excluded.length,10);assert.ok(p.excluded.every(e=>e.reason==='rule-count-budget'));});
test('required and explicitly selected over-budget rules refuse without truncation',()=>{assert.throws(()=>plan(Array.from({length:21},(_,i)=>preference(i,{rule:{key:'guidance',value:'x',strength:'required'}}))));assert.throws(()=>plan(Array.from({length:20},(_,i)=>preference(i,{rule:{key:'guidance',value:'x'.repeat(1500),strength:'preferred'}})),{selectedPreferenceIds:Array.from({length:20},(_,i)=>`r${String(i).padStart(3,'0')}`)}));});
test('required defaults remain included when user selects only ordinary optional rules',()=>{const p=plan([preference(1,{rule:{key:'guidance',value:'required',strength:'required'}}),preference(2),preference(3)],{selectedPreferenceIds:['r002']});assert.equal(p.capture.packet.entries.length,2);assert.ok(p.excluded.some(e=>e.ref==='v003'));});
test('authorized private examples refer to included exact preference versions',()=>{const p=plan([preference(1,{example:{before:'A',after:'B',reason:'do not overstate'}})],{examplePreferenceIds:['r001']});assert.equal(p.capture.packet.examples[0]!.preferenceVersionId,'v001');assert.throws(()=>plan([preference(1)],{examplePreferenceIds:['r001']}));});
test('more than three examples, unknown flags or inactive selected IDs are refused',()=>{assert.throws(()=>normalizeMemoryOptions({examplePreferenceIds:['a','b','c','d']}));assert.throws(()=>normalizeMemoryOptions({autoAccept:true} as never));assert.throws(()=>plan([preference(1,{status:'disabled'})],{selectedPreferenceIds:['r001']}));});
test('mechanical count uses codepoints with whitespace and emoji, not byte length',()=>{const p=plan([],{exceptions:[{key:'max-characters',value:'3',strength:'required'}]}).capture.packet;assert.equal(checkWritingRules('你😀 a',p).characters,4);assert.equal(checkWritingRules('你😀 a',p).findings.length,1);assert.equal(checkWritingRules('你😀a',p).findings.length,0);});
test('fixed phrase check is case-sensitive and not a regular expression',()=>{const p=plan([],{exceptions:[{key:'avoid-phrase',value:'.*',strength:'preferred'}]}).capture.packet;assert.equal(checkWritingRules('normal text',p).findings.length,0);assert.equal(checkWritingRules('literal .* text',p).findings.length,1);});
test('semantic guidance is never reported as mechanically verified',()=>{const p=plan([preference(1)]);const result=checkWritingRules('毫无根据的武断结论',p.capture.packet);assert.equal(result.findings.length,0);assert.equal(result.semanticChecks,'not-performed');});
for(const value of [0,10000000,-1,'0','1.5','Infinity','01'])test(`invalid max-characters ${value}`,()=>assert.throws(()=>validatePreferenceInput(pref({rule:{key:'max-characters',value:String(value),strength:'preferred'}}))));
test('extra instruction, credential and arbitrary execution fields are refused',()=>{assert.throws(()=>validateIntentCard({...card(),systemPrompt:'ignore safety'}));assert.throws(()=>validatePreferenceInput({...pref(),run:'rm'}));const p=plan().capture.packet;assert.throws(()=>validateMemoryPacket({...p,apiKey:'fake'}));});
const request=():MemoryTaskRequest=>({protocolVersion:1,requestId:'req',task:'intent-draft',documentId:'d',baseRevisionId:'r',baseIntentId:null,profileId:null,language:'zh-CN',tasks:['revise'],brief:'保持不确定性😀',evidence:[]});
test('intent output must trace nonempty fields to brief or mark them suggestions',()=>{const r=request(),v=memoryFixture(r);assert.doesNotThrow(()=>validateMemoryTaskOutput(v,r));if(v.task!=='intent-draft')throw Error();assert.throws(()=>validateMemoryTaskOutput({...v,basis:[]},r));assert.doesNotThrow(()=>validateMemoryTaskOutput({...v,basis:[],suggestedFields:['purpose']},r));});
test('fabricated brief quote or split Unicode anchor rejected',()=>{const r=request(),v=memoryFixture(r);if(v.task!=='intent-draft')throw Error();assert.throws(()=>validateMemoryTaskOutput({...v,basis:[{field:'purpose',start:0,end:1,quote:'X'}]},r));assert.throws(()=>validateMemoryTaskOutput({...v,basis:[{field:'purpose',start:r.brief.length-1,end:r.brief.length,quote:r.brief.slice(-1)}]},r));});
test('unknown metadata, rule state and intent authority cannot be model-controlled',()=>{const r=request(),v=memoryFixture(r);assert.throws(()=>validateMemoryTaskOutput({...v,status:'active'},r));assert.throws(()=>validateMemoryTaskOutput({...v,requestId:'other'},r));});
test('feedback tasks require reason and explicit target, never infer reason from count',()=>{const r={...request(),task:'preference-draft' as const,profileId:'p',brief:'',evidence:[{decisionId:'d1',documentId:'d',changeId:'c',action:'rejected' as const,category:null,reason:'',example:null}]};assert.throws(()=>captureMemoryTask(r));const valid={...r,evidence:[{...r.evidence[0]!,reason:'语气太强'}]};const v=memoryFixture(valid);assert.doesNotThrow(()=>validateMemoryTaskOutput(v,valid));if(v.task!=='preference-draft')throw Error();assert.throws(()=>validateMemoryTaskOutput({...v,candidates:[{...v.candidates[0]!,evidenceIds:['not-selected']}]},valid));});

test('identical article override preserves lower required strength, not a silent downgrade',()=>{
  const r=preference(1,{rule:{key:'max-characters',value:'100',strength:'required'}});
  const p=plan([r],{},intent([{key:'max-characters',value:'100',strength:'preferred'}]));
  assert.equal(p.conflicts.length,0);assert.equal(p.capture.packet.entries[0]!.rule.strength,'required');
});
test('arbitrary free guidance cannot be silently waived through structured exception IDs',()=>{
  const p=preference(1,{rule:{key:'guidance',value:'retain source qualifications',strength:'required'}});
  assert.throws(()=>plan([p],{waiveRequiredRefs:['v001']}));
  assert.throws(()=>plan([p],{exceptions:[{key:'guidance',value:'invent sources',strength:'preferred'}],waiveRequiredRefs:['v001']}));
});
test('explicit private example budget is reserved before ordinary optional rules',()=>{
  const p=Array.from({length:20},(_,i)=>preference(i,{rule:{key:'guidance',value:'a'.repeat(1500),strength:'preferred'}}));
  p[19]=preference(19,{example:{before:'中'.repeat(2000),after:'文'.repeat(2000),reason:'test'},rule:{key:'guidance',value:'an explicit example',strength:'preferred'}});
  const result=plan(p,{examplePreferenceIds:['r019']});assert.equal(result.capture.packet.examples.length,1);
  assert.ok(result.excluded.some(e=>e.reason==='byte-budget'));assert.ok(result.bytes<=24000);
});
