// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';
import assert from 'node:assert/strict';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readFileSync, existsSync } from 'node:fs';
import { spawn } from 'node:child_process';
import { temporary } from './helpers.js';
import { fakeServer, json, ollamaEnvelope, requestFromBody, wire } from './provider-helpers.js';
import { reviewFixture } from './analysis-helpers.js';
import type { AnalysisRequest } from '@writer-agent/core';
import { ConnectionStore, FakeSecrets, settings, presetRef, prepareProbe, runProbe, ProductError } from './product-helpers.js';
const cli = fileURLToPath(new URL('../../apps/cli/dist/index.js', import.meta.url));
function storeFixture(t: Parameters<typeof temporary>[0]) { return new ConnectionStore(join(temporary(t), 'app'), new FakeSecrets()); }
test('Probe preview does not resolve keys or call the service; unconfirmed fingerprint creates no probe', async (t) => { const store = storeFixture(t), secrets = store.secrets as FakeSecrets, p = await store.save('test', settings(), 'system', 'FAKE_TOKEN'); const plan = await prepareProbe('model', store, p); assert.equal(secrets.reads, 0); assert.equal(store.probes().length, 0); await assert.rejects(runProbe(plan, 'wrong', store), { code: 'PROBE_STALE' }); assert.equal(store.probes().length, 0); assert.equal(secrets.reads, 0); });
test('Changing connection after preview blocks service probing before network', async (t) => { const store = storeFixture(t), p = await store.save('test', settings(), 'none'), plan = await prepareProbe('model', store, p); await store.save('new', settings(), 'none', undefined, presetRef(p)); await assert.rejects(runProbe(plan, plan.fingerprint, store), { code: 'PRESET_STALE' }); assert.equal(store.probes().length, 0); });
test('Cancelled probe does not create credentials or dispatch a request', async (t) => { const store = storeFixture(t), plan = await prepareProbe('keyring', store), abort = new AbortController(); abort.abort(); await assert.rejects(runProbe(plan, plan.fingerprint, store, abort.signal), { code: 'CANCELLED' }); assert.equal((store.secrets as FakeSecrets).writes, 0); assert.equal(existsSync(store.directory), false); });
test('Keyring self-test returns attributed fake result, journals and cleans only its own key', async (t) => { const store = storeFixture(t), s = store.secrets as FakeSecrets; s.values.set('Other-app-key', 'UNTOUCHED'); const plan = await prepareProbe('keyring', store), result = await runProbe(plan, plan.fingerprint, store); assert.equal(result.status, 'passed'); assert.match(JSON.stringify(result), /isolated-memory-test-not-os/); assert.deepEqual([...s.values.entries()], [['Other-app-key', 'UNTOUCHED']]); assert.equal(store.pendingSecrets().length, 0); assert.equal(store.probes()[0]!.status, 'passed'); });
test('Failed OS cleanup retains isolated operation identity for explicit recovery, never deletes other apps', async (t) => { const store = storeFixture(t), s = store.secrets as FakeSecrets; s.remove = async () => { throw new ProductError('CREDENTIAL_LOCKED', 'Synthetic locked store'); }; const plan = await prepareProbe('keyring', store), result = await runProbe(plan, plan.fingerprint, store); assert.equal(result.status, 'failed'); assert.equal(store.pendingSecrets().length, 1); const own = store.pendingSecrets()[0]!; s.remove = async (id) => s.values.delete(id); await store.cleanupSecret(String(own.id)); assert.equal(s.values.size, 0); assert.equal(store.pendingSecrets().length, 0); });
test('An interrupted live-check journal remains unknown instead of success after configuration reopening', t => { const store = storeFixture(t); store.probeStart({ kind: 'search', maxRequests: 1 }); const next = new ConnectionStore(store.directory, store.secrets); assert.equal(next.probes()[0]!.status, 'outcome-unknown'); });
test('Explicit model trial uses production propose/review, has two bounded calls and never adopts edits', async (t) => { const s = await fakeServer(t, (req, res) => { const raw = JSON.parse((req.body.messages as {
    content: string;
}[])[1]!.content) as AnalysisRequest; if (raw.task === 'semantic-review')
    json(res, ollamaEnvelope(reviewFixture(raw)));
else
    json(res, ollamaEnvelope(wire(requestFromBody(req.body)))); }); const store = storeFixture(t), p = await store.save('fixture', settings(s.base), 'none'), plan = await prepareProbe('model', store, p), result = await runProbe(plan, plan.fingerprint, store); assert.equal(result.status, 'passed', JSON.stringify(result)); assert.equal(s.requests.length, 2); assert.match(JSON.stringify(result), /"manuscriptUnchanged":true/); assert.doesNotMatch(JSON.stringify(result), /A small fictional observation may suggest/); });
test('Wrong actual model response is recorded failed, never passed because HTTP was reachable', async (t) => { const s = await fakeServer(t, (_req, res) => json(res, ollamaEnvelope({ autoAccept: true }))), store = storeFixture(t), p = await store.save('bad fixture', settings(s.base), 'none'), plan = await prepareProbe('model', store, p), result = await runProbe(plan, plan.fingerprint, store); assert.equal(result.status, 'failed'); assert.equal(s.requests.length, 1); assert.equal(store.probes()[0]!.status, 'failed'); });
test('Slow model trial records uncertain external outcome without implicit retry or secret echo', async (t) => { const s = await fakeServer(t, () => { }), store = storeFixture(t), set = settings(s.base); if (set.kind === 'model')
    set.model.timeoutMs = 100; const p = await store.save('slow', set, 'none'), plan = await prepareProbe('model', store, p), r = await runProbe(plan, plan.fingerprint, store); assert.equal(r.status, 'outcome-unknown'); assert.equal(s.requests.length, 1); });
test('Explicit search probe executes fixed basic request and reports actual returned credits', async (t) => { const old = globalThis.fetch; let calls = 0; globalThis.fetch = async (input, init) => { calls++; assert.equal(String(input), 'https://api.tavily.com/search'); const b = JSON.parse(String(init?.body)); assert.equal(b.search_depth, 'basic'); assert.equal(b.auto_parameters, false); assert.equal(b.include_answer, false); assert.equal(new Headers(init?.headers).get('authorization'), 'Bearer SYNTHETIC_TAVILY'); return new Response(JSON.stringify({ query: b.query, results: [{ title: 'Synthetic cache documentation', url: 'https://example.test/cache', content: 'Cache-Control example', score: 0.5 }], request_id: 'probe-fiction', usage: { credits: 1 } }), { status: 200, headers: { 'Content-Type': 'application/json' } }); }; t.after(() => { globalThis.fetch = old; }); const store = storeFixture(t), p = await store.save('search', { kind: 'search', endpoint: 'https://api.tavily.com/search' }, 'session', 'SYNTHETIC_TAVILY'), plan = await prepareProbe('search', store, p), result = await runProbe(plan, plan.fingerprint, store); assert.equal(result.status, 'passed', JSON.stringify(result)); assert.equal(calls, 1); assert.doesNotMatch(JSON.stringify(result), /SYNTHETIC_TAVILY/); });
test('MCP verification uses the official adapter but does not call a business tool', async (t) => { const store = storeFixture(t), path = fileURLToPath(new URL('../fixtures/sdk-server.mjs', import.meta.url)), p = await store.save('SDK fixture', { kind: 'mcp', connection: { name: 'SDK fixture', transport: 'stdio', protocol: '2026-07-28', command: process.execPath, args: [path], cwd: dirname(path), env: [], timeoutMs: 5000 } }, 'none'), plan = await prepareProbe('mcp-discovery', store, p); assert.ok(plan.launchHash); const result = await runProbe(plan, plan.fingerprint, store); assert.equal(result.status, 'passed', JSON.stringify(result)); assert.match(JSON.stringify(result), /discovery-only-not-all-tools/); });
function command(args: string[], directory: string) { return new Promise<{
    status: number | null;
    out: string;
    err: string;
}>((res, rej) => { const p = spawn(process.execPath, [cli, ...args], { env: { ...process.env, XDG_CONFIG_HOME: directory, LOCALAPPDATA: directory }, stdio: ['ignore', 'pipe', 'pipe'] }); let out = '', err = ''; const timeout = setTimeout(() => { p.kill(); rej(Error('CLI timed out')); }, 20000); p.stdout.on('data', x => out += String(x)); p.stderr.on('data', x => err += String(x)); p.on('error', e => { clearTimeout(timeout); rej(e); }); p.on('close', status => { clearTimeout(timeout); res({ status, out, err }); }); }); }
test('Offline product doctor requires neither workspace, keyring session nor network', async (t) => { const directory = join(temporary(t), 'empty-settings'), r = await command(['product', 'doctor'], directory); assert.equal(r.status, 0, r.err); assert.match(r.out, /not-run/); assert.equal(existsSync(directory), false); });
for (const args of [['product', 'guide'], ['product', 'doctor', 'missing', 'extra'], ['product', 'unknown'], ['product', 'help', 'extra']])
    test('New command rejects invalid arguments: ' + args.join(' '), async (t) => { const r = await command(args, temporary(t)); assert.notEqual(r.status, 0); });
test('Full product demonstration couples SDK, preset, summary, report, reopen and explicit adoption', async () => { const { productDemo } = await import(new URL('../../apps/cli/dist/product-demo.js', import.meta.url).href) as typeof import('../../apps/cli/src/product-demo.js'); const r = await productDemo(); assert.equal(r.reports.length, 2); for (const p of r.reports) {
    const h = readFileSync(p, 'utf8');
    assert.match(h, /script-src 'none'/);
    assert.doesNotMatch(h, /SYNTHETIC_DEMO_KEY/);
} });

test('Paired product guides have identical runnable commands and explicit sensitive boundaries',async()=>{
  const docs=fileURLToPath(new URL('../../docs/',import.meta.url));const en=readFileSync(join(docs,'product.md'),'utf8'),zh=readFileSync(join(docs,'product.zh-CN.md'),'utf8');
  const commands=(s:string)=>[...s.matchAll(/```sh\n([\s\S]*?)```/g)].map(m=>m[1]!.trim());assert.deepEqual(commands(en),commands(zh));
  for(const s of [en,zh]){assert.match(s,/PRODUCT_DEMO_OK/);assert.match(s,/derived-navigation-not-evidence/);assert.match(s,/outcome-unknown/);assert.match(s,/schema6/);assert.match(s,/Secret Service/);}
});
