// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { temporary, fixture, propose } from './helpers.js';
import { workflowSetup, modelFixture, grant, executeWorkflow } from './workflow-helpers.js';
import { reportSnapshot, renderReadingReport, writeReadingReport, safeReportLink, escapeHtml, localDiagnostics, recoveryView, ConnectionStore, FakeSecrets, runProductGuide } from './product-helpers.js';
import type { ReadingReport } from '../../apps/cli/src/application/report.js';
const minimal = (text = ''): ReadingReport => ({ format: 1, kind: 'siglum-read-only-snapshot', version: '0.0.8', generatedAt: '2026-09-16T00:00:00Z', language: 'en', title: 'Private reading', scope: { text: true, sources: false, guidance: false }, sections: [{ title: 'Text', text }] });
for (const payload of ['<script>alert(1)</script>', '<img src=https://host.invalid onerror=alert(1)>', '</pre><svg onload=alert(1)>', '<iframe srcdoc="<script>x</script>">', '</style><script>x</script>', '&#60;script&#62;', '\u001b]8;;https://host.invalid\u0007text'])
    test('HTML escapes untrusted content: ' + JSON.stringify(payload.slice(0, 30)), () => { const html = renderReadingReport(minimal(payload)); assert.doesNotMatch(html, /<script|<img|<iframe|<svg/i); assert.ok(html.includes(escapeHtml(payload))); });
for (const url of ['javascript:alert(1)', 'data:text/html,<b>', 'file:///C:/secret', 'shell:calc', 'https://user:password@example.test/', 'https://example.test/\n'])
    test('Report link refuses ' + url, () => assert.equal(safeReportLink(url), null));
test('Safe source link is explicitly clickable, no referrer and no automatic resource fetch', () => { const r = minimal(); r.sections[0]!.link = 'https://example.test/reference'; const h = renderReadingReport(r); assert.match(h, /rel="noopener noreferrer"/); assert.match(h, /referrerpolicy="no-referrer"/); assert.doesNotMatch(h, /<(?:script|img|iframe|form|link)\b/i); assert.match(h, /connect-src 'none'/); });
test('Metadata document report excludes private title, original text, source and intent bytes', t => { const { workspace: w, document: d } = fixture(t, 'MANUSCRIPT_PRIVATE'); w.memory.saveIntent(d.id, { language: 'en', audience: 'GUIDANCE_PRIVATE', purpose: 'x', thesis: '', rules: [], importantOccurrenceIds: [] }); const report = reportSnapshot(w, { documentId: d.id, language: 'en', includeText: false, includeSources: false, includeGuidance: false }); assert.doesNotMatch(JSON.stringify(report), /MANUSCRIPT_PRIVATE|GUIDANCE_PRIVATE|测试文稿/); assert.doesNotMatch(renderReadingReport(report), /MANUSCRIPT_PRIVATE|GUIDANCE_PRIVATE|测试文稿/); });
test('Document report separates current state from generation-time frozen content', t => { const { workspace: w, document: d } = fixture(t, 'before'); const r = reportSnapshot(w, { documentId: d.id, language: 'en', includeText: true, includeSources: false, includeGuidance: false }); const c = propose(w, d.id, 0, 'after'); w.accept(c.id); assert.match(renderReadingReport(r), /before/); assert.doesNotMatch(JSON.stringify(r), /"after"/); assert.equal(r.generatedAt, r.generatedAt); });
test('Report includes explicit full before/after text but does not alter approvals', t => { const { workspace: w, document: d } = fixture(t, 'before'); const c = propose(w, d.id, 0, 'after'); const r = reportSnapshot(w, { documentId: d.id, language: 'zh-CN', includeText: true, includeSources: false, includeGuidance: false }); const h = renderReadingReport(r); assert.match(h, /修改前/); assert.match(h, /修改后/); assert.equal(w.getChange(c.id).status, 'pending'); assert.equal(w.history(d.id).length, 1); });
test('Excluded evidence quote fields do not hide inside exported task details', async (t) => { const { w, run } = workflowSetup(t, { goal: 'PRIVATE-GOAL' }), model = modelFixture(); grant(w, run.id); await executeWorkflow(w, run.id, { model }); const r = reportSnapshot(w, { runId: run.id, language: 'en', includeText: true, includeSources: false, includeGuidance: false }); const text = JSON.stringify(r); assert.doesNotMatch(text, /"sourceQuotes"|"guidance"\s*:\s*\{|PRIVATE-GOAL/); const metadata = reportSnapshot(w, { runId: run.id, language: 'en', includeText: false, includeSources: false, includeGuidance: false }); assert.doesNotMatch(JSON.stringify(metadata), /Fictional research|fictional findings|PRIVATE-GOAL|causal conclusion/); });
test('Opt-in original sources are included with exact pinned identity and no model call', async (t) => { const { w, run, source } = workflowSetup(t), model = modelFixture(); grant(w, run.id); await executeWorkflow(w, run.id, { model }); const n = w.workflows.attempts(run.id).length; const r = reportSnapshot(w, { runId: run.id, language: 'en', includeText: false, includeSources: true, includeGuidance: false }); assert.match(JSON.stringify(r), new RegExp(source.snapshot.id)); assert.match(JSON.stringify(r), /not a causal conclusion/); assert.equal(w.workflows.attempts(run.id).length, n); });
test('HTML publication never overwrites a target and leaves no partial temp files', t => { const dir = temporary(t), path = join(dir, 'report with 空格.html'), r = minimal('Test'); writeReadingReport(path, r); const before = readFileSync(path); assert.throws(() => writeReadingReport(path, minimal('Replacement'))); assert.deepEqual(readFileSync(path), before); assert.deepEqual(readdirSync(dir), ['report with 空格.html']); });
test('Invalid report language cannot become attribute injection', () => { const r = minimal(); Object.assign(r, { language: 'en" onload="alert(1)' }); assert.throws(() => renderReadingReport(r), { code: 'REPORT_INVALID' }); });
test('Recovery view distinguishes saved steps and uncertain external attempt without private request', async (t) => { const { w, run } = workflowSetup(t, { goal: 'PRIVATE_GOAL' }), model = modelFixture(); model.workflowTask = async () => { throw Error('uncertain'); }; grant(w, run.id); await assert.rejects(executeWorkflow(w, run.id, { model })); const view = recoveryView(w, run.id); assert.equal(view.problems[0]!.possiblyProcessed, true); assert.equal(view.problems[0]!.status, 'outcome-unknown'); assert.doesNotMatch(JSON.stringify(view), /PRIVATE_GOAL/); });
test('Product guide local diagnostics/exit invokes no secrets or external services', async (t) => { const { workspace: w, dir } = fixture(t), secrets = new FakeSecrets(), store = new ConnectionStore(join(dir, 'app'), secrets); const answers = ['1', '0'], out: string[] = []; await runProductGuide(w, { ask: async () => answers.shift() ?? '0', line: x => out.push(x) }, 'zh-CN', store); assert.equal(secrets.reads + secrets.writes, 0); assert.equal(existsSync(store.directory), false); assert.match(out.join('\n'), /not-run/); });
test('Product guide new system preset uses masked input and never prints the key', async (t) => { const { workspace: w, dir } = fixture(t), secrets = new FakeSecrets(), store = new ConnectionStore(join(dir, 'app'), secrets); const answers = ['3', 'Local model', '1', '1', 'fixture', 'http://127.0.0.1:11434', 'n', '1', '', '', '1', 'y', '0']; const output: string[] = []; let masked = 0; await runProductGuide(w, { ask: async () => { const a = answers.shift(); if (a === undefined)
        throw Error('too many prompts'); return a; }, secret: async () => { masked++; return 'SYNTHETIC-MASKED-KEY'; }, line: x => output.push(x) }, 'en', store); assert.equal(masked, 1); assert.equal(store.list().length, 1); assert.doesNotMatch(output.join('\n'), /SYNTHETIC-MASKED-KEY/); assert.equal(readFileSync(store.path).includes(Buffer.from('SYNTHETIC-MASKED-KEY')), false); });
test('Model summary data never implicitly enters a metadata-only diagnostic', t => { const { workspace: w, dir } = fixture(t, 'MY_MANUSCRIPT'); const d = localDiagnostics(w, new ConnectionStore(join(dir, 'new'), new FakeSecrets())); assert.doesNotMatch(JSON.stringify(d), /MY_MANUSCRIPT/); });
