// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { DatabaseSync } from 'node:sqlite';
import { Workspace,migrateWorkspace } from '@writer-agent/storage';
import { applySplices,rangeDiff,mapRange,graphemeBoundaries,hashBytes } from '@writer-agent/core';
import type { ProposedRange } from '@writer-agent/core';
const {SCHEMA_V1_SQL,APPLICATION_ID}=await import(new URL('../../packages/storage/dist/schema.js',import.meta.url).href) as {SCHEMA_V1_SQL:string;APPLICATION_ID:number};
const {SOURCES_SQL}=await import(new URL('../../packages/storage/dist/source-schema.js',import.meta.url).href) as {SOURCES_SQL:string};
const {ANALYSIS_SQL}=await import(new URL('../../packages/storage/dist/analysis-schema.js',import.meta.url).href) as {ANALYSIS_SQL:string};
const {MEMORY_SQL}=await import(new URL('../../packages/storage/dist/memory-schema.js',import.meta.url).href) as {MEMORY_SQL:string};
const {WORKFLOW_SQL}=await import(new URL('../../packages/storage/dist/workflow-schema.js',import.meta.url).href) as {WORKFLOW_SQL:string};
const {EXTENSION_SQL}=await import(new URL('../../packages/storage/dist/extension-schema.js',import.meta.url).href) as {EXTENSION_SQL:string};

function setup(t:test.TestContext,text='One red boat. Two blue birds.'){const parent=mkdtempSync(join(tmpdir(),'siglum-range-'));const root=join(parent,'workspace'),w=Workspace.create(root),d=w.createDocument('Test',text);t.after(()=>{w.close();rmSync(parent,{recursive:true,force:true,maxRetries:3,retryDelay:50});});return {w,d,root};}
function proposal(blockId:string,before:string,after:string,text:string):ProposedRange{const start=text.indexOf(before);return {blockId,start,end:start+before.length,before,after,summary:'Selected wording',dependsOn:[],group:null};}
function two(t:test.TestContext){const f=setup(t),r=f.w.currentRevision(f.d.id),b=r.snapshot.blocks[0]!;const set=f.w.ranges.create(f.d.id,r.id,[proposal(b.id,'red','crimson',b.text),proposal(b.id,'blue','azure',b.text)]);return {...f,ops:f.w.ranges.list(f.d.id),set};}
for(const [a,b]of [['abc','axc'],['','new'],['remove',''],['a😀b','a👩🏽‍💻b'],['研究可能有效。第二句保持。','研究暂时有效。第二句保留。'],['e\u0301 a','é a'],['aa\r\nbb','aa\r\nXX'],['red and blue','crimson and azure'],['word word word','word changed word']] as const){
 test(`range diff lossless ${JSON.stringify(a)} -> ${JSON.stringify(b)}`,()=>{const d=rangeDiff(a,b);assert.equal(applySplices(a,d.splices).text,b);for(const s of d.splices){assert(graphemeBoundaries(a).has(s.start));assert(graphemeBoundaries(a).has(s.end));}});
}
test('no-op diff is empty',()=>assert.deepEqual(rangeDiff('same','same').splices,[]));
test('bounded diff uses explicit coarse fallback',()=>{const d=rangeDiff('a b c d e','f g h i j',1);assert(d.coarse);assert.equal(applySplices('a b c d e',d.splices).text,'f g h i j');});
test('different ranges in one block: accept one reject other',t=>{const {w,d,ops}=two(t);w.ranges.decide(d.id,[ops[0]!.id],'accept',w.currentRevision(d.id).id);w.ranges.decide(d.id,[ops[1]!.id],'reject',w.currentRevision(d.id).id);assert.equal(w.markdown(d.id),'One crimson boat. Two blue birds.');assert.equal(w.ranges.operation(ops[1]!.id).status,'rejected');assert.equal(w.history(d.id).length,2);});
for(const reverse of [false,true])test(`independent range acceptance order ${reverse}`,t=>{const {w,d,ops}=two(t);for(const o of reverse?[...ops].reverse():ops)w.ranges.decide(d.id,[o.id],'accept',w.currentRevision(d.id).id);assert.equal(w.markdown(d.id),'One crimson boat. Two azure birds.');w.ranges.decide(d.id,[ops[0]!.id],'revert',w.currentRevision(d.id).id);assert.equal(w.markdown(d.id),'One red boat. Two azure birds.');});
test('one batch accepts two ranges and individual inverse preserves second',t=>{const {w,d,ops}=two(t);w.ranges.decide(d.id,ops.map(o=>o.id),'accept',w.currentRevision(d.id).id);w.ranges.decide(d.id,[ops[0]!.id],'revert',w.currentRevision(d.id).id);assert.equal(w.markdown(d.id),'One red boat. Two azure birds.');});
test('manual overlap blocks a previous inverse',t=>{const {w,d,ops}=two(t);w.ranges.decide(d.id,[ops[0]!.id],'accept',w.currentRevision(d.id).id);const r=w.currentRevision(d.id),b=r.snapshot.blocks[0]!;w.ranges.manual(d.id,r.id,[{blockId:b.id,expectedVersion:b.version,text:b.text.replace('crimson','scarlet')}]);assert.throws(()=>w.ranges.decide(d.id,[ops[0]!.id],'revert',w.currentRevision(d.id).id),/overlap|touched/);assert.equal(w.markdown(d.id),'One scarlet boat. Two blue birds.');});
test('manual disjoint edit is mapped and preserved',t=>{const {w,d,ops}=two(t);w.ranges.decide(d.id,[ops[0]!.id],'accept',w.currentRevision(d.id).id);const r=w.currentRevision(d.id),b=r.snapshot.blocks[0]!;w.ranges.manual(d.id,r.id,[{blockId:b.id,expectedVersion:b.version,text:b.text.replace('birds','eagles')}]);w.ranges.decide(d.id,[ops[0]!.id],'revert',w.currentRevision(d.id).id);assert.equal(w.markdown(d.id),'One red boat. Two blue eagles.');});
test('ABA overlap remains a conflict even when text returns',t=>{const {w,d,ops}=two(t);w.ranges.decide(d.id,[ops[0]!.id],'accept',w.currentRevision(d.id).id);for(const [from,to]of [['crimson','scarlet'],['scarlet','crimson']]){const r=w.currentRevision(d.id),b=r.snapshot.blocks[0]!;w.ranges.manual(d.id,r.id,[{blockId:b.id,expectedVersion:b.version,text:b.text.replace(from!,to!)}]);}assert.throws(()=>w.ranges.decide(d.id,[ops[0]!.id],'revert',w.currentRevision(d.id).id),/overlap|touched/);});
test('same word repeated is addressed by position, not first match',t=>{const {w,d}=setup(t,'word word word'),r=w.currentRevision(d.id),b=r.snapshot.blocks[0]!;w.ranges.create(d.id,r.id,[{blockId:b.id,start:5,end:9,before:'word',after:'middle',summary:'middle occurrence',dependsOn:[],group:null}]);const o=w.ranges.list(d.id)[0]!;w.ranges.decide(d.id,[o.id],'accept',r.id);assert.equal(w.markdown(d.id),'word middle word');});
test('same insertion boundary is mutually exclusive',t=>{const {w,d}=setup(t,'ab'),r=w.currentRevision(d.id),b=r.snapshot.blocks[0]!;for(const after of ['X','Y'])w.ranges.create(d.id,r.id,[{blockId:b.id,start:1,end:1,before:'',after,summary:'insert',dependsOn:[],group:null}]);const ops=w.ranges.list(d.id);w.ranges.decide(d.id,[ops[0]!.id],'accept',r.id);assert.throws(()=>w.ranges.decide(d.id,[ops[1]!.id],'accept',w.currentRevision(d.id).id),/touched/);});
test('delete and inverse insertion preserve distant edits',t=>{const {w,d}=setup(t,'erase alpha omega'),r=w.currentRevision(d.id),b=r.snapshot.blocks[0]!;w.ranges.create(d.id,r.id,[proposal(b.id,'erase ','',b.text),proposal(b.id,'omega','OMEGA',b.text)]);const ops=w.ranges.list(d.id);w.ranges.decide(d.id,ops.map(o=>o.id),'accept',r.id);assert.equal(w.markdown(d.id),'alpha OMEGA');w.ranges.decide(d.id,[ops[0]!.id],'revert',w.currentRevision(d.id).id);assert.equal(w.markdown(d.id),'erase alpha OMEGA');});
for(const [text,start,end]of [['a😀b',2,3],['xe\u0301y',1,2],['x👩🏽‍💻y',2,3],['a\r\nb',1,2]] as const)test(`refuse split character cluster ${JSON.stringify(text)}`,()=>assert.throws(()=>applySplices(text,[{start,end,before:text.slice(start,end),after:'x'}]),/grapheme|Range|Unicode/));
test('replacement cannot create a cross-boundary combining cluster',()=>assert.throws(()=>applySplices('ax',[{start:1,end:2,before:'x',after:'\u0301'}]),/grapheme/));
test('overlap in a proposal set is refused before persistence',t=>{const {w,d}=setup(t,'abc'),r=w.currentRevision(d.id),id=r.snapshot.blocks[0]!.id;assert.throws(()=>w.ranges.create(d.id,r.id,[{blockId:id,start:0,end:2,before:'ab',after:'A',summary:'a',group:null,dependsOn:[]},{blockId:id,start:1,end:3,before:'bc',after:'B',summary:'b',group:null,dependsOn:[]}]),/Overlapping/);assert.equal(w.ranges.list(d.id).length,0);});
test('atomic groups cannot be partly accepted or reverted',t=>{const {w,d}=setup(t),r=w.currentRevision(d.id),b=r.snapshot.blocks[0]!;w.ranges.create(d.id,r.id,[{...proposal(b.id,'red','crimson',b.text),group:'together'},{...proposal(b.id,'blue','azure',b.text),group:'together'}]);const ops=w.ranges.list(d.id);assert.throws(()=>w.ranges.decide(d.id,[ops[0]!.id],'accept',r.id),/atomic/);w.ranges.decide(d.id,ops.map(o=>o.id),'accept',r.id);assert.throws(()=>w.ranges.decide(d.id,[ops[0]!.id],'revert',w.currentRevision(d.id).id),/atomic/);});
test('dependencies require predecessors and prevent unsafe inverse',t=>{const {w,d}=setup(t),r=w.currentRevision(d.id),b=r.snapshot.blocks[0]!;w.ranges.create(d.id,r.id,[proposal(b.id,'red','crimson',b.text),{...proposal(b.id,'blue','azure',b.text),dependsOn:[0]}]);const ops=w.ranges.list(d.id);assert.throws(()=>w.ranges.decide(d.id,[ops[1]!.id],'accept',r.id),/dependent/);w.ranges.decide(d.id,ops.map(o=>o.id),'accept',r.id);assert.throws(()=>w.ranges.decide(d.id,[ops[0]!.id],'revert',w.currentRevision(d.id).id),/depends/);w.ranges.decide(d.id,ops.map(o=>o.id),'revert',w.currentRevision(d.id).id);assert.equal(w.markdown(d.id),'One red boat. Two blue birds.');});
test('cyclic dependencies refused',t=>{const {w,d}=setup(t),r=w.currentRevision(d.id),b=r.snapshot.blocks[0]!;assert.throws(()=>w.ranges.create(d.id,r.id,[{...proposal(b.id,'red','crimson',b.text),dependsOn:[1]},{...proposal(b.id,'blue','azure',b.text),dependsOn:[0]}]),/cycle/);});
test('stale UI head refuses decision, pending operation preserved',t=>{const {w,d,ops}=two(t),old=w.currentRevision(d.id).id;w.ranges.decide(d.id,[ops[0]!.id],'accept',old);assert.throws(()=>w.ranges.decide(d.id,[ops[1]!.id],'accept',old),/Refresh/);assert.equal(w.ranges.operation(ops[1]!.id).status,'pending');});
test('duplicate decisions refused without extra revision',t=>{const {w,d,ops}=two(t);w.ranges.decide(d.id,[ops[0]!.id],'accept',w.currentRevision(d.id).id);assert.throws(()=>w.ranges.decide(d.id,[ops[0]!.id],'accept',w.currentRevision(d.id).id),/pending/);assert.equal(w.history(d.id).length,2);});
test('cross-document operation refuses all side effects',t=>{const {w,d,ops}=two(t),other=w.createDocument('other','text');assert.throws(()=>w.ranges.decide(other.id,[ops[0]!.id],'accept',other.headRevisionId),/pending/);assert.equal(w.history(d.id).length,1);});
test('old block proposals stay readable; delegated proposal cannot auto-accept',t=>{const {w,d}=setup(t),r=w.currentRevision(d.id),b=r.snapshot.blocks[0]!,c=w.proposeChanges(d.id,r.id,[{blockId:b.id,before:b.text,after:b.text.replace('red','crimson').replace('blue','azure'),summary:'two edits'}])[0]!;const split=w.ranges.splitChange(c.id,r.id);assert.equal(split.operations.length,2);assert.throws(()=>w.accept(c.id),/reviewed as ranges/);w.ranges.decide(d.id,[split.operations[0]!.id],'accept',r.id);assert.equal(w.getChange(c.id).status,'pending');assert.equal(w.ranges.splitChange(c.id,w.currentRevision(d.id).id).set.id,split.set.id);});
test('legacy block edits in different blocks preserve range applicability',t=>{const {w,d}=setup(t,'red text\n\nother text'),r=w.currentRevision(d.id),a=r.snapshot.blocks[0]!,b=r.snapshot.blocks[1]!;w.ranges.create(d.id,r.id,[proposal(a.id,'red','blue',a.text)]);const c=w.proposeChanges(d.id,r.id,[{blockId:b.id,before:b.text,after:'changed other',summary:'other'}])[0]!;w.accept(c.id);w.ranges.decide(d.id,[w.ranges.list(d.id)[0]!.id],'accept',w.currentRevision(d.id).id);assert.equal(w.markdown(d.id),'blue text\n\nchanged other');});
test('legacy block edits in target block break unsafe remapping',t=>{const {w,d}=setup(t),r=w.currentRevision(d.id),b=r.snapshot.blocks[0]!;w.ranges.create(d.id,r.id,[proposal(b.id,'red','crimson',b.text)]);const c=w.proposeChanges(d.id,r.id,[{blockId:b.id,before:b.text,after:b.text.replace('blue','azure'),summary:'other'}])[0]!;w.accept(c.id);assert.throws(()=>w.ranges.decide(d.id,[w.ranges.list(d.id)[0]!.id],'accept',w.currentRevision(d.id).id),/unrecorded/);});
test('manual revision exposes manual origin and monotonic block version',t=>{const {w,d}=setup(t),r=w.currentRevision(d.id),b=r.snapshot.blocks[0]!;const next=w.ranges.manual(d.id,r.id,[{blockId:b.id,expectedVersion:b.version,text:'changed'}]);assert.equal(next.editOrigin,'manual-edited');assert.equal(next.snapshot.blocks[0]!.version,b.version+1);assert.equal(w.decisions(d.id).length,0);});
test('editor buffer autosave does not mutate manuscript; CAS and reopen work',t=>{const {w,d,root}=setup(t),r=w.currentRevision(d.id),blocks=r.snapshot.blocks.map(b=>({blockId:b.id,text:b.text+' note'}));const b=w.ranges.saveBuffer(d.id,r.id,0,blocks);assert.equal(w.history(d.id).length,1);assert.throws(()=>w.ranges.saveBuffer(d.id,r.id,0,blocks),/another session/);const other=Workspace.open(root);try{assert.equal(other.ranges.buffer(d.id)!.version,b.version);}finally{other.close();}w.ranges.commitBuffer(d.id,r.id,b.version);assert.equal(w.markdown(d.id),'One red boat. Two blue birds. note');assert.equal(w.ranges.buffer(d.id),null);});
test('saved buffer is preserved on head conflict',t=>{const {w,d,ops}=two(t),r=w.currentRevision(d.id);const b=w.ranges.saveBuffer(d.id,r.id,0,r.snapshot.blocks.map(x=>({blockId:x.id,text:'buffer'})));w.ranges.decide(d.id,[ops[0]!.id],'accept',r.id);assert.throws(()=>w.ranges.commitBuffer(d.id,r.id,b.version),/Another session/);assert.equal(w.ranges.buffer(d.id)!.blocks[0]!.text,'buffer');});
test('SQL failure atomically rolls back all ranges, revisions and journal',t=>{const {w,d,root,ops}=two(t),db=new DatabaseSync(join(root,'.writer','workspace.sqlite'));try{db.exec("CREATE TRIGGER range_fail BEFORE INSERT ON range_decisions BEGIN SELECT RAISE(ABORT,'test failure'); END");assert.throws(()=>w.ranges.decide(d.id,ops.map(o=>o.id),'accept',w.currentRevision(d.id).id),/test failure/);assert.equal(w.history(d.id).length,1);assert(w.ranges.list(d.id).every(o=>o.status==='pending'));assert.equal(db.prepare('SELECT COUNT(*) AS n FROM content_journals').get()!.n,0);}finally{db.close();}});
test('content journal integrity and append-only protection',t=>{const {w,d,root,ops}=two(t);const rev=w.ranges.decide(d.id,[ops[0]!.id],'accept',w.currentRevision(d.id).id),db=new DatabaseSync(join(root,'.writer','workspace.sqlite'));try{assert.throws(()=>db.prepare('UPDATE content_journals SET payload_hash=? WHERE revision_id=?').run('bad',rev.id),/append-only/);assert.throws(()=>db.exec('DELETE FROM range_decisions'),/append-only/);}finally{db.close();}});
test('schema6 explicit migration preserves original rows and a readable backup',t=>{
  const parent=mkdtempSync(join(tmpdir(),'siglum-v6-v7-')),root=join(parent,'old');const w=Workspace.create(root);w.close();const path=join(root,'.writer','workspace.sqlite');rmSync(path,{force:true});const db=new DatabaseSync(path);
  try{db.exec(SCHEMA_V1_SQL+SOURCES_SQL+ANALYSIS_SQL+MEMORY_SQL+WORKFLOW_SQL+EXTENSION_SQL+'PRAGMA user_version=6;');db.prepare('INSERT INTO workspace VALUES(?,?,?)').run('ws_old','Old','2026-01-01');assert.equal(db.prepare('PRAGMA application_id').get()!.application_id,APPLICATION_ID);}finally{db.close();}
  t.after(()=>rmSync(parent,{recursive:true,force:true,maxRetries:3,retryDelay:50}));const old=Workspace.open(root);let doc!:ReturnType<Workspace['createDocument']>;try{doc=old.createDocument('kept','old text');assert.throws(()=>old.ranges.list(doc.id),/migration/);}finally{old.close();}
  assert.equal(migrateWorkspace(root).needed,true);const upgraded=migrateWorkspace(root,true);assert.equal(upgraded.to,7);const check=Workspace.open(root);try{assert.equal(check.markdown(doc.id),'old text');assert.deepEqual(check.ranges.list(doc.id),[]);}finally{check.close();}const backup=new DatabaseSync(upgraded.backup!,{readOnly:true});try{assert.equal(backup.prepare('PRAGMA user_version').get()!.user_version,6);}finally{backup.close();}
});
test('random disjoint operations commute, and individual inverses preserve other changes',t=>{
  const {w}=setup(t);let state=17;const random=()=>{state=(state*1664525+1013904223)>>>0;return state;};
  for(let k=0;k<100;k++){
    const left=String(random()%10000),right=String(random()%10000),original=`L[${left}] gap R[${right}]`,d=w.createDocument('property '+k,original),r=w.currentRevision(d.id),b=r.snapshot.blocks[0]!;
    const i=original.indexOf(left),j=original.lastIndexOf(right);const p=[{blockId:b.id,start:i,end:i+left.length,before:left,after:'LEFT'+k,summary:'left',group:null,dependsOn:[]},{blockId:b.id,start:j,end:j+right.length,before:right,after:'RIGHT'+k,summary:'right',group:null,dependsOn:[]}];w.ranges.create(d.id,r.id,p);const ops=w.ranges.list(d.id);const order=random()%2?ops:[...ops].reverse();for(const o of order)w.ranges.decide(d.id,[o.id],'accept',w.currentRevision(d.id).id);w.ranges.decide(d.id,[ops[0]!.id],'revert',w.currentRevision(d.id).id);assert.equal(w.markdown(d.id),`L[${left}] gap R[RIGHT${k}]`);w.ranges.decide(d.id,[ops[1]!.id],'revert',w.currentRevision(d.id).id);assert.equal(w.markdown(d.id),original);
  }
});
test('mapRange applies start/end insertion affinity explicitly',()=>{assert.deepEqual(mapRange({start:2,end:4},[{start:2,end:2,before:'',after:'X'}]),{start:3,end:5});assert.deepEqual(mapRange({start:2,end:4},[{start:4,end:4,before:'',after:'X'}]),{start:2,end:4});});
test('read data tampering is detected',t=>{const {w,d,root,ops}=two(t),db=new DatabaseSync(join(root,'.writer','workspace.sqlite'));try{db.prepare('UPDATE range_operations SET payload_hash=? WHERE id=?').run(hashBytes('bad'),ops[0]!.id);assert.throws(()=>w.ranges.list(d.id),/integrity/);}finally{db.close();}});
