// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {mkdirSync,readdirSync,existsSync} from 'node:fs';
import {join} from 'node:path';
import {Workspace,migrateWorkspace} from '@writer-agent/storage';
import {temporary,propose} from './helpers.js';
import {pref,card} from './memory-helpers.js';
import {workflowConfig} from './workflow-helpers.js';
const {SCHEMA_V1_SQL}=await import(new URL('../../packages/storage/dist/schema.js',import.meta.url).href) as {SCHEMA_V1_SQL:string};
const {SOURCES_SQL}=await import(new URL('../../packages/storage/dist/source-schema.js',import.meta.url).href) as {SOURCES_SQL:string};
const {ANALYSIS_SQL}=await import(new URL('../../packages/storage/dist/analysis-schema.js',import.meta.url).href) as {ANALYSIS_SQL:string};
const {MEMORY_SQL}=await import(new URL('../../packages/storage/dist/memory-schema.js',import.meta.url).href) as {MEMORY_SQL:string};
function old(t:Parameters<typeof temporary>[0]){const root=join(temporary(t),'Legacy v4 中文 空格'),path=join(root,'.writer/workspace.sqlite');mkdirSync(join(root,'.writer'),{recursive:true});const db=new DatabaseSync(path);try{db.exec(SCHEMA_V1_SQL+SOURCES_SQL+ANALYSIS_SQL+MEMORY_SQL+'PRAGMA user_version=4');db.prepare('INSERT INTO workspace(id,name,created_at) VALUES(?,?,?)').run('w','legacy','2026-09-15');}finally{db.close();}const w=Workspace.open(root);try{const d=w.createDocument('old','你好😀\r\n\r\nSome teams may improve.'),c=propose(w,d.id,0,'你好😀！');w.reject(c.id,'Keep old greeting');const p=w.memory.createProfile('Profile');w.memory.attach(d.id,p.id);w.memory.addPreference(p.id,pref());w.memory.saveIntent(d.id,card());const s=w.sources.add({kind:'file',locator:'s.txt',raw:Buffer.from('source'),mediaType:'text/plain'});const e=w.sources.extract(s.snapshot.id,1,1);w.sources.note(s.snapshot.id,'private note',e.id);return {root,path,d,p,s};}finally{w.close();}}
function rows(path:string){const db=new DatabaseSync(path,{readOnly:true});try{const tables=db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name!='sqlite_sequence' ORDER BY name").all().map(r=>String(r.name));return Object.fromEntries(tables.map(n=>[n,db.prepare('SELECT * FROM '+n).all()]));}finally{db.close();}}
test('schema4 remains usable without automatic workflow enablement, preview does not create backup',t=>{const {root,path}=old(t);const before=rows(path);const w=Workspace.open(root);try{assert.throws(()=>w.workflows.list(),{code:'MIGRATION_REQUIRED'});assert.equal(w.info().schemaVersion,4);assert.equal(w.memory.profiles().length,1);}finally{w.close();}const p=migrateWorkspace(root);assert.equal(p.to,7);assert.equal(p.applied,false);assert.deepEqual(rows(path),before);assert.equal(existsSync(join(root,'.writer/backups')),false);});
test('schema4 to7 keeps every prior row and verified private backup, then enables workflows',t=>{const {root,path,d}=old(t),before=rows(path),m=migrateWorkspace(root,true);assert.ok(m.backup);assert.deepEqual(rows(m.backup),before);const after=rows(path);for(const [name,value]of Object.entries(before))assert.deepEqual(after[name],value,name);const w=Workspace.open(root);try{assert.equal(w.info().schemaVersion,7);const r=w.workflows.create(workflowConfig({template:'revise-article',documentId:d.id,language:'zh-CN',memoryOptions:{language:'zh-CN'}}));assert.equal(r.state,'waiting-approval');assert.equal(w.history(d.id).length,1);assert.equal(w.memory.profiles().length,1);}finally{w.close();}assert.equal(migrateWorkspace(root,true).needed,false);assert.equal(readdirSync(join(root,'.writer/backups')).length,1);});
test('workflow schema DDL collision rolls back all new tables and leaves schema4 intact',t=>{const {root,path}=old(t);const db=new DatabaseSync(path);try{db.exec('CREATE TABLE workflow_attempts(dummy TEXT)');}finally{db.close();}const before=rows(path);assert.throws(()=>migrateWorkspace(root,true),{code:'CORRUPT_DATA'});assert.deepEqual(rows(path),before);const check=new DatabaseSync(path);try{assert.equal(check.prepare('PRAGMA user_version').get()!.user_version,4);assert.equal(check.prepare("SELECT count(*) n FROM sqlite_master WHERE name='workflow_runs'").get()!.n,0);}finally{check.close();}assert.equal(existsSync(join(root,'.writer/migration.lock')),false);assert.equal(readdirSync(join(root,'.writer/backups')).length,1);});
test('unknown future schema refuses workflow migration and never overwrites contents',t=>{const {root,path}=old(t);const db=new DatabaseSync(path);try{db.exec('PRAGMA user_version=999');}finally{db.close();}const before=rows(path);assert.throws(()=>migrateWorkspace(root,true),{code:'UNSUPPORTED_SCHEMA'});assert.throws(()=>Workspace.open(root),{code:'UNSUPPORTED_SCHEMA'});assert.deepEqual(rows(path),before);});
