// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';
import assert from 'node:assert/strict';
import { Workspace } from '@writer-agent/storage';
import { WriterError } from '@writer-agent/core';
import type { WorkflowRequest, WorkflowConfig, OutlineOutput, WorkflowContentRequest, SearchResult } from '@writer-agent/core';
import { ProviderError } from '@writer-agent/models';
import { workflowSetup, workflowConfig, grant, dependencies, executeWorkflow, modelFixture, workflowFixture } from './workflow-helpers.js';
import { fixture, propose } from './helpers.js';
import { pref } from './memory-helpers.js';
const webSource='Synthetic observations in a small sample. No causal conclusion.';
function webDependencies(hook?:(r:WorkflowRequest)=>void|Promise<void>){let searchCalls=0,fetchCalls=0;const packets:WorkflowRequest[]=[];return {packets,get counts(){return {searchCalls,fetchCalls};},model:modelFixture(async r=>{packets.push(structuredClone(r));await hook?.(r);}),search:{id:'tavily',search:async(q:{query:string}):Promise<SearchResult>=>{searchCalls++;return {query:q.query,results:[{id:'local-result',url:'https://example.org/study',title:'Synthetic observations',snippet:'DISCOVERY_SNIPPET_ONLY',score:null}],credits:null,requestId:null,provider:'tavily',discoveredAt:new Date().toISOString()};}},fetchPage:async(url:string)=>{fetchCalls++;return {url,raw:Buffer.from(webSource),mediaType:'text/plain' as const};}};}
async function research(w:Workspace,id:string){grant(w,id);const r=await executeWorkflow(w,id,dependencies());w.workflows.chooseOutline(id,r.outlineId!);return r;}
test('new-article phases retain A/B, refuse automatic adoption and adopt idempotently',async t=>{
 const {w,run}=workflowSetup(t);const docs=w.listDocuments().length;await assert.rejects(executeWorkflow(w,run.id,dependencies()),{code:'WORKFLOW_PERMISSION'});const r=await research(w,run.id);assert.equal(w.listDocuments().length,docs);await assert.rejects(executeWorkflow(w,run.id,dependencies()),{code:'WORKFLOW_PERMISSION'});grant(w,run.id);const finish=await executeWorkflow(w,run.id,dependencies());assert.equal(finish.candidateIds.length,2);assert.equal(w.listDocuments().length,docs);assert.equal(w.workflows.usage(run.id).models,4);const id=w.workflows.adopt(run.id,finish.candidateIds[1]!);assert.equal(w.workflows.adopt(run.id,finish.candidateIds[1]!),id);assert.equal(w.listDocuments().length,docs+1);assert.throws(()=>w.workflows.adopt(run.id,finish.candidateIds[0]!));assert.ok(w.workflows.artifact(r.outlineId!));assert.match(w.markdown(id),/small/);
});
test('no autoRevision yields one candidate and never an extra hidden model call',async t=>{const {w,run}=workflowSetup(t,{autoRevision:false});await research(w,run.id);grant(w,run.id);const r=await executeWorkflow(w,run.id,dependencies());assert.equal(r.candidateIds.length,1);assert.equal(w.workflows.usage(run.id).models,3);});
test('empty critique skips even the authorized optional revision',async t=>{const {w,run}=workflowSetup(t);await research(w,run.id);grant(w,run.id);const model=modelFixture();model.workflowTask=async r=>{const o=workflowFixture(r);return {providerId:model.id,output:o.task==='draft-review'?{...o,issues:[],needsRevision:false}:o,usage:null};};const end=await executeWorkflow(w,run.id,{model});assert.equal(end.candidateIds.length,1);assert.equal(w.workflows.usage(run.id).models,3);});
test('revised article alternatives stay pending against the official baseline',async t=>{const f=fixture(t),w=f.workspace,d=f.document;const r=w.workflows.create(workflowConfig({template:'revise-article',documentId:d.id}));grant(w,r.id);const end=await executeWorkflow(w,r.id,dependencies());assert.equal(end.state,'waiting-approval');assert.equal(end.candidateIds.length,2);assert.equal(w.history(d.id).length,1);const all=w.listChanges(d.id);assert.equal(all.length,2);assert.ok(all.every(c=>c.status==='pending'&&c.baseRevisionId===d.headRevisionId));w.accept(all[0]!.id);assert.throws(()=>w.accept(all[1]!.id),{code:'CHANGE_CONFLICT'});w.revert(all[0]!.id);assert.equal(w.markdown(d.id),'甲段可能成立。\n\n乙段保持不变。');});
test('review-only never adds a candidate or changes manuscript approval',async t=>{const f=fixture(t),w=f.workspace,d=f.document,c=propose(w,d.id,0,'第一段成立。');const r=w.workflows.create(workflowConfig({template:'review-changes',documentId:d.id,changeIds:[c.id],autoRevision:false}));grant(w,r.id);const end=await executeWorkflow(w,r.id,dependencies());assert.equal(end.state,'completed');assert.equal(end.candidateIds.length,0);assert.equal(w.history(d.id).length,1);assert.equal(w.getChange(c.id).status,'pending');assert.equal(w.workflows.usage(r.id).models,1);});
test('public planner sees only public brief; actual sources not discovery snippets go to outline',async t=>{const {w,run}=workflowSetup(t,{research:'web',selection:{},goal:'PRIVATE_GOAL_NOT_FOR_SEARCH'});grant(w,run.id);const deps=webDependencies();await executeWorkflow(w,run.id,deps);assert.equal(deps.counts.searchCalls,1);assert.equal(deps.counts.fetchCalls,1);const query=deps.packets[0]!;assert.equal(query.task,'query-plan');assert.doesNotMatch(JSON.stringify(query),/PRIVATE_GOAL_NOT_FOR_SEARCH|writing|intent|sources/);const outline=deps.packets.find(r=>r.task==='outline')!;assert.match(JSON.stringify(outline),/Synthetic observations/);assert.doesNotMatch(JSON.stringify(outline),/DISCOVERY_SNIPPET_ONLY/);assert.equal(w.workflows.usage(run.id).searches,1);assert.equal((w.workflows.attempts(run.id).find(a=>a.kind==='search')!.usage as {credits:number|null}).credits,null);});
test('unread webpages are recorded unavailable; snippets cannot fabricate a research success',async t=>{const {w,run}=workflowSetup(t,{research:'web',selection:{}});grant(w,run.id);const deps=webDependencies();deps.fetchPage=async()=>{throw new WriterError('SOURCE_BLOCKED','Failed page');};const end=await executeWorkflow(w,run.id,deps);assert.equal(end.state,'blocked');assert.equal(end.outlineId,null);assert.equal(deps.packets.length,1);assert.equal(w.workflows.usage(run.id).fetches,1);assert.ok(w.workflows.artifacts(run.id).some(a=>a.type==='fetch'&&(a.value as {available:boolean}).available===false));});
test('long fetched source retains full saved text and discloses selected prefix',async t=>{const {w,run}=workflowSetup(t,{research:'web',selection:{}});grant(w,run.id);const deps=webDependencies();deps.fetchPage=async url=>({url,raw:Buffer.from(Array.from({length:80},(_,i)=>'Line '+i).join('\n')),mediaType:'text/plain'});await executeWorkflow(w,run.id,deps);const req=deps.packets.find(r=>r.task==='outline') as WorkflowContentRequest;assert.match(req.gaps.join('\n'),/40\/80/);assert.equal(req.sources[0]!.endLine,40);assert.match(w.sources.snapshot(req.sources[0]!.snapshotId).text,/Line 79/);});
test('timeout is outcome-unknown and cannot silently resend on resume',async t=>{const {w,run}=workflowSetup(t);grant(w,run.id);let calls=0;const deps=dependencies(()=>{calls++;throw new ProviderError('PROVIDER_TIMEOUT','timeout');});await assert.rejects(executeWorkflow(w,run.id,deps),{code:'PROVIDER_TIMEOUT'});const a=w.workflows.attempts(run.id)[0]!;assert.equal(a.status,'outcome-unknown');await assert.rejects(executeWorkflow(w,run.id,deps),{code:'WORKFLOW_UNKNOWN'});assert.equal(calls,1);assert.throws(()=>w.workflows.retry(run.id,a.id,false),{code:'WORKFLOW_UNKNOWN'});w.workflows.retry(run.id,a.id,true);await executeWorkflow(w,run.id,dependencies());assert.equal(w.workflows.usage(run.id).models,2);});
test('confirmed failure needs explicit retry and no raw error or secret is persisted',async t=>{const {w,run}=workflowSetup(t);grant(w,run.id);await assert.rejects(executeWorkflow(w,run.id,dependencies(()=>{throw new ProviderError('PROVIDER_AUTH','DO_NOT_PERSIST_SECRET');})));assert.equal(w.workflows.attempts(run.id)[0]!.status,'failed');assert.doesNotMatch(JSON.stringify(w.workflows.attempts(run.id)),/DO_NOT_PERSIST_SECRET/);await assert.rejects(executeWorkflow(w,run.id,dependencies()),{code:'WORKFLOW_UNKNOWN'});w.workflows.retry(run.id,w.workflows.attempts(run.id)[0]!.id,false);await executeWorkflow(w,run.id,dependencies());});
test('abort of uncooperative provider returns and records unknown without database mutation',async t=>{const {w,run}=workflowSetup(t);grant(w,run.id);const ctrl=new AbortController();const promise=executeWorkflow(w,run.id,dependencies(()=>new Promise(()=>{})),ctrl.signal);setTimeout(()=>ctrl.abort(),20);await assert.rejects(promise,{code:'WORKFLOW_UNKNOWN'});assert.equal(w.workflows.attempts(run.id)[0]!.status,'outcome-unknown');assert.equal(w.workflows.artifacts(run.id).length,0);});
test('phase active-time bound stops stalled provider even when provider timeout is longer',async t=>{const {w,run}=workflowSetup(t);const p=w.workflows.preview(run.id,{models:3,searches:0,fetches:0,activeMs:500});w.workflows.authorize(run.id,p.fingerprint,p.limits);await assert.rejects(executeWorkflow(w,run.id,dependencies(()=>new Promise(()=>{}))));assert.equal(w.workflows.attempts(run.id)[0]!.status,'outcome-unknown');assert.ok(w.workflows.usage(run.id).activeMs>=450);});
test('completed model step is reused after failure, reopen and explicit retry',async t=>{const {w,run}=workflowSetup(t);await research(w,run.id);grant(w,run.id);await assert.rejects(executeWorkflow(w,run.id,dependencies(r=>{if(r.task==='draft-review')throw new ProviderError('PROVIDER_AUTH','fixture');})));const draftCount=w.workflows.artifacts(run.id).filter(a=>a.type==='draft').length;assert.equal(draftCount,1);const a=w.workflows.attempts(run.id).find(a=>a.status==='failed')!;w.close();const again=Workspace.open(w.root);try{again.workflows.retry(run.id,a.id,false);grant(again,run.id);const tasks:string[]=[];const end=await executeWorkflow(again,run.id,dependencies(r=>{tasks.push(r.task);}));assert.deepEqual(tasks,['draft-review','draft-revision']);assert.equal(end.candidateIds.length,2);assert.equal(again.workflows.artifacts(run.id).filter(a=>a.type==='draft').length,1);}finally{again.close();}});
test('input refresh invalidates private outline but reuses matching public searches and pages',async t=>{const {w,run}=workflowSetup(t,{research:'web',selection:{}}),deps=webDependencies();grant(w,run.id);const first=await executeWorkflow(w,run.id,deps);w.workflows.refresh(run.id,{...run.config,goal:'New private focus'});grant(w,run.id);const second=await executeWorkflow(w,run.id,deps);assert.notEqual(second.outlineId,first.outlineId);assert.deepEqual(deps.counts,{searchCalls:1,fetchCalls:1});assert.equal(deps.packets.filter(r=>r.task==='query-plan').length,1);assert.ok(w.workflows.artifact(first.outlineId!));assert.throws(()=>w.workflows.chooseOutline(run.id,first.outlineId!),{code:'STALE_REVISION'});});
test('model mutation cannot modify host baseline or grant permission',async t=>{const {w,run}=workflowSetup(t);grant(w,run.id);const model=modelFixture();model.workflowTask=async r=>{const changed={...r,runId:'forged'};return {providerId:model.id,output:workflowFixture(changed),usage:null};};await assert.rejects(executeWorkflow(w,run.id,{model}));assert.equal(w.workflows.artifacts(run.id).length,0);assert.equal(w.workflows.run(run.id).config.goal,run.config.goal);});
test('revoking authority during model wait fences the returning worker',async t=>{const {w,run}=workflowSetup(t);grant(w,run.id);await assert.rejects(executeWorkflow(w,run.id,dependencies(()=>{w.workflows.pause(run.id);})));assert.equal(w.workflows.artifacts(run.id).length,0);assert.equal(w.workflows.run(run.id).grantId,null);assert.equal(w.workflows.attempts(run.id)[0]!.status,'outcome-unknown');});
test('related memory change during model wait cannot save stale output',async t=>{const {w}=workflowSetup(t),profile=w.memory.createProfile('Scoped');const run=w.workflows.create(workflowConfig({profileId:profile.id,selection:{snapshots:[w.sources.list()[0]!.latestSnapshotId!]}}));grant(w,run.id);await assert.rejects(executeWorkflow(w,run.id,dependencies(()=>{w.memory.addPreference(profile.id,pref({language:'en'}));})),{code:'STALE_REVISION'});assert.equal(w.workflows.artifacts(run.id).length,0);});
test('author outline replacement keeps history and requires fresh explicit composition grant',async t=>{const {w,run}=workflowSetup(t);const first=await research(w,run.id);const a=w.workflows.artifact(first.outlineId!),v=a.value as {output:OutlineOutput};const amended=w.workflows.amendOutline(run.id,a.id,{...v.output,direction:'Author changed the angle.'});assert.equal(amended.origin,'author');assert.equal(w.workflows.run(run.id).grantId,null);assert.throws(()=>w.workflows.chooseOutline(run.id,a.id),{code:'STALE_REVISION'});w.workflows.chooseOutline(run.id,amended.id);grant(w,run.id);const end=await executeWorkflow(w,run.id,dependencies());assert.ok(w.workflows.artifact(end.candidateIds[0]!).parentIds.includes(amended.id));});
test('completed optional revision cannot be silently repeated after an upstream rerun',async t=>{const {w,run}=workflowSetup(t);await research(w,run.id);grant(w,run.id);await executeWorkflow(w,run.id,dependencies());const state=w.workflows.run(run.id);const o=w.workflows.artifact(state.outlineId!).value as {output:OutlineOutput};const amended=w.workflows.amendOutline(run.id,state.outlineId!,{...o.output,direction:'Another approved angle'});w.workflows.chooseOutline(run.id,amended.id);grant(w,run.id);await assert.rejects(executeWorkflow(w,run.id,dependencies()),{code:'WORKFLOW_BUDGET'});assert.equal(w.workflows.attempts(run.id).filter(a=>a.task==='draft-revision'&&a.status==='completed').length,1);});
test('repeated authorize of a phase cannot exceed the task aggregate quota',async t=>{const config:Partial<WorkflowConfig>={budget:{models:1,searches:0,fetches:0,activeMs:100000}};const {w,run}=workflowSetup(t,config);grant(w,run.id);await assert.rejects(executeWorkflow(w,run.id,dependencies(()=>{throw new ProviderError('PROVIDER_AUTH','x');})));w.workflows.retry(run.id,w.workflows.attempts(run.id)[0]!.id,false);grant(w,run.id);await assert.rejects(executeWorkflow(w,run.id,dependencies()),{code:'WORKFLOW_BUDGET'});assert.equal(w.workflows.usage(run.id).models,1);});
test('budget extension resumes a cached draft rather than regenerating already saved output',async t=>{const {w,run}=workflowSetup(t);await research(w,run.id);const p=w.workflows.preview(run.id,{models:1,searches:0,fetches:0,activeMs:50000});w.workflows.authorize(run.id,p.fingerprint,p.limits);await assert.rejects(executeWorkflow(w,run.id,dependencies()),{code:'WORKFLOW_BUDGET'});assert.equal(w.workflows.artifacts(run.id).filter(a=>a.type==='draft').length,1);w.workflows.setBudget(run.id,{...run.config.budget,models:12});grant(w,run.id);const tasks:string[]=[];await executeWorkflow(w,run.id,dependencies(r=>{tasks.push(r.task);}));assert.deepEqual(tasks,['draft-review','draft-revision']);assert.equal(w.workflows.artifacts(run.id).filter(a=>a.type==='draft').length,1);});
