// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';
import assert from 'node:assert/strict';
import { TavilySearch, parseSearchResponse, selectSearchHits, OllamaProvider, OpenAICompatibleProvider, workflowMessages } from '@writer-agent/models';
import type { SearchRequest, WorkflowQueryRequest } from '@writer-agent/core';
import {fakeServer,json,chatEnvelope,ollamaEnvelope} from './provider-helpers.js';
import {workflowFixture} from './workflow-helpers.js';
const q:SearchRequest={query:'public fictional question',language:'en',domains:['example.org'],timeRange:'month',maxResults:5};
const hit={url:'https://example.org/a',title:'Fictional result',content:'Discovery snippet; not fetched content',score:0.7};
const result={query:q.query,results:[hit],usage:{credits:1},request_id:'fixture-id'};
function key(t:Parameters<typeof fakeServer>[0]){const name='SIGLUM_TEST_SEARCH_ONLY',before=process.env[name];process.env[name]='NOT_A_REAL_KEY';t.after(()=>{if(before===undefined)delete process.env[name];else process.env[name]=before;});return name;}
test('Tavily native HTTP fixes depth/options, sends only search fields, preserves reported usage',async t=>{const s=await fakeServer(t,(_req,res)=>json(res,result)),p=new TavilySearch({keyEnv:key(t),testEndpoint:s.base+'/search'});const r=await p.search(q);assert.equal(r.credits,1);assert.equal(r.requestId,'fixture-id');assert.equal(s.requests.length,1);const request=s.requests[0]!;assert.equal(request.headers.authorization,'Bearer NOT_A_REAL_KEY');assert.deepEqual(request.body,{query:q.query,search_depth:'basic',auto_parameters:false,include_answer:false,include_raw_content:false,include_images:false,include_usage:true,max_results:5,topic:'general',language:'en',filter_by_language:false,include_domains:['example.org'],time_range:'month'});assert.doesNotMatch(JSON.stringify(r),/NOT_A_REAL_KEY/);});
test('search preflight missing credentials makes no HTTP request',async t=>{const s=await fakeServer(t,(_req,res)=>json(res,result));const p=new TavilySearch({keyEnv:'SIGLUM_MISSING_TEST_SEARCH_ENV',testEndpoint:s.base+'/search'});assert.throws(()=>p.preflight(),{code:'SEARCH_AUTH'});await assert.rejects(p.search(q),{code:'SEARCH_AUTH'});assert.equal(s.requests.length,0);});
for(const [status,code]of [[401,'SEARCH_AUTH'],[429,'SEARCH_RATE_LIMIT'],[432,'SEARCH_QUOTA'],[433,'SEARCH_QUOTA'],[500,'SEARCH_HTTP']]as const)test(`search HTTP ${status} is safe, bounded and not retried`,async t=>{const s=await fakeServer(t,(_h,res)=>json(res,{error:'PRIVATE_BODY_TOKEN'},status));const p=new TavilySearch({keyEnv:key(t),testEndpoint:s.base+'/search'});await assert.rejects(p.search(q),e=>{assert.equal((e as {code:string}).code,code);assert.doesNotMatch(String(e),/PRIVATE_BODY_TOKEN/);return true;});assert.equal(s.requests.length,1);});
for(const kind of ['redirect','invalid-json','wrong-mime','oversize','disconnect']as const)test('search rejects '+kind+' without retry/fallback',async t=>{const s=await fakeServer(t,(_h,res)=>{if(kind==='redirect'){res.writeHead(302,{Location:'/other'});res.end();}else if(kind==='invalid-json'){res.writeHead(200,{'content-type':'application/json'});res.end('{broken');}else if(kind==='wrong-mime'){res.writeHead(200,{'content-type':'text/plain'});res.end('{}');}else if(kind==='oversize'){json(res,{...result,padding:'x'.repeat(500001)});}else res.destroy();});const p=new TavilySearch({keyEnv:key(t),testEndpoint:s.base+'/search'});await assert.rejects(p.search(q));assert.equal(s.requests.length,1);});
test('search cancellation stops a stalled response without background retry',async t=>{const s=await fakeServer(t,()=>{}),ctrl=new AbortController();const p=new TavilySearch({keyEnv:key(t),testEndpoint:s.base+'/search'});const pending=p.search(q,ctrl.signal);const timer=setTimeout(()=>ctrl.abort(),40);try{await assert.rejects(pending,{code:'SEARCH_CANCELLED'});}finally{clearTimeout(timer);}assert.ok(s.requests.length<=1);});
for(const testEndpoint of ['https://evil.example/search','http://localhost/search','http://127.0.0.1/search?key=x','http://a:b@127.0.0.1/search'])test('test transport injection cannot select remote or credential URL '+testEndpoint,()=>assert.throws(()=>new TavilySearch({testEndpoint})));
for(const bad of [{...result,query:'other'},{query:q.query,results:[{...hit,url:'file:///secret'}]},{query:q.query,results:[{...hit,url:'https://name:pass@example.org'}]},{query:q.query,results:[{title:'missing'}]},{...result,usage:{credits:-1}},{...result,request_id:123}])test('search refuses malformed envelope/URL/usage',()=>assert.throws(()=>parseSearchResponse(bad,q)));
test('URL duplicates normalize fragment; missing credits are unknown, not zero',()=>{const r=parseSearchResponse({query:q.query,results:[hit,{...hit,url:hit.url+'#anchor'}]},q);assert.equal(r.results.length,1);assert.equal(r.credits,null);assert.equal(r.requestId,null);});
test('discovered private IP is never fetched; host diversity and exclusion reasons are explicit',()=>{const r=parseSearchResponse({query:q.query,results:[{...hit,url:'http://127.0.0.1/secret'},hit,{...hit,url:'https://example.org/b'},{...hit,url:'https://other.example.net/a'},{...hit,url:'https://last.example.net/a'}]},q);const all=selectSearchHits([r,r],[],2);assert.deepEqual(all.selected.map(h=>h.url),['https://example.org/a','https://other.example.net/a']);assert.ok(all.excluded.some(x=>x.reason==='blocked-url-or-domain'));assert.ok(all.excluded.some(x=>x.reason==='duplicate-url'));assert.ok(all.excluded.some(x=>x.reason==='page-attempt-budget'));assert.match(all.policy,/not-reliability/);assert.equal(selectSearchHits([r],['example.org'],5).selected.length,2);});
const r:WorkflowQueryRequest={protocolVersion:1,task:'query-plan',runId:'r',requestId:'x',publicBrief:q.query,language:'en',maxQueries:2};
for(const Provider of [OllamaProvider,OpenAICompatibleProvider]){
 test(`${Provider.name} production workflow method uses dedicated task schema`,async t=>{const s=await fakeServer(t,(req,res)=>json(res,req.path==='/api/chat'?ollamaEnvelope(workflowFixture(r)):chatEnvelope(workflowFixture(r))));const p=new Provider({model:'fixture',baseURL:s.base});const output=await p.workflowTask(r);assert.equal(output.output.task,'query-plan');assert.equal(output.providerId,p.id);assert.equal(output.usage,null);assert.equal(s.requests.length,1);assert.equal(s.requests[0]!.body.tools,undefined);assert.match(JSON.stringify(s.requests[0]!.body),/query-plan/);assert.doesNotMatch(JSON.stringify(workflowMessages(r)),/privateDraft|authorizationToken/);});
 test(`${Provider.name} does not accept model-created approval fields or wrong run`,async t=>{const s=await fakeServer(t,(req,res)=>json(res,req.path==='/api/chat'?ollamaEnvelope({...workflowFixture(r),approve:true}):chatEnvelope({...workflowFixture(r),runId:'forged'})));const p=new Provider({model:'fixture',baseURL:s.base});await assert.rejects(p.workflowTask(r),{code:'PROVIDER_INVALID_WORKFLOW'});assert.equal(s.requests.length,1);});
 test(`${Provider.name} rejects duplicate workflow JSON keys rather than silently choosing one`,async t=>{const text=JSON.stringify(workflowFixture(r)).replace('"protocolVersion":1','"protocolVersion":1,"protocolVersion":1');const s=await fakeServer(t,(req,res)=>json(res,req.path==='/api/chat'?{done:true,done_reason:'stop',message:{role:'assistant',content:text}}:{choices:[{finish_reason:'stop',message:{role:'assistant',content:text}}]}));await assert.rejects(new Provider({model:'fixture',baseURL:s.base}).workflowTask(r));});
}
test('Chinese search explicitly uses language boost without filtering all other languages',async t=>{const s=await fakeServer(t,(hit,res)=>json(res,{query:hit.body.query,results:[]}));await new TavilySearch({keyEnv:key(t),testEndpoint:s.base+'/search'}).search({...q,query:'浏览器缓存与验证',language:'zh-CN'});assert.equal(s.requests[0]!.body.language,'zh-cn');assert.equal(s.requests[0]!.body.filter_by_language,false);});
