// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';
import assert from 'node:assert/strict';
import { validateWorkflowConfig, validateWorkflowBudget, validateWorkflowRequest, validateWorkflowOutput, publicResultUrl, renderWorkflowDraft } from '@writer-agent/core';
import type { WorkflowQueryRequest, WorkflowContentRequest } from '@writer-agent/core';
import { workflowConfig, workflowSetup } from './workflow-helpers.js';
import { workflowFixture } from './workflow-helpers.js';
const query:WorkflowQueryRequest={protocolVersion:1,task:'query-plan',runId:'run1',requestId:'req1',publicBrief:'A public question',language:'en',maxQueries:3};
for(const [name,patch] of [ ['unknown field',{apiKey:'NO'}],['unknown template',{template:'shell'}],['private new doc identity',{documentId:'doc-existing'}],['empty public brief',{research:'web',publicBrief:''}],['bad memory',{memoryOptions:{activate:true}}],['arbitrary key-env',{searchKeyEnv:'secret with spaces'}],['bad domain',{domains:['*.example.org']}],['bad time',{timeRange:'all'}],['model URL credentials',{model:{...workflowConfig().model,baseURL:'https://me:secret@example.org/v1',allowRemote:true}}] ] as const){test(`workflow config rejects ${name}`,()=>assert.throws(()=>validateWorkflowConfig({...workflowConfig(),...patch})));}
test('canonical config and zero external quotas are valid',()=>{const c=workflowConfig();assert.doesNotThrow(()=>validateWorkflowConfig(c));assert.doesNotThrow(()=>validateWorkflowBudget({models:0,searches:0,fetches:0,activeMs:100}));});
for(const v of [-1,0.5,NaN,Infinity,41])test(`bounded workflow model count rejects ${v}`,()=>assert.throws(()=>validateWorkflowBudget({models:v,searches:3,fetches:5,activeMs:1000})));
test('planning schema has no private manuscript, profile or API fields',()=>{assert.doesNotThrow(()=>validateWorkflowRequest(query));assert.throws(()=>validateWorkflowRequest({...query,privateDraft:'secret'}));assert.throws(()=>validateWorkflowRequest({...query,task:'run-command'}));});
for(const output of [{...workflowFixture(query),runId:'other'},{...workflowFixture(query),autoApprove:true},{...workflowFixture(query),queries:['x','x']},{...workflowFixture(query),queries:[]},{...workflowFixture(query),queries:['x'.repeat(401)]}])test('query output exact shape, target and bounded unique queries',()=>assert.throws(()=>validateWorkflowOutput(output,query)));
for(const url of ['file:///etc/passwd','http://localhost','http://127.0.0.1','http://169.254.169.254/meta','https://u:p@example.org','https://example.org:8443/x','http://example.org.evil.net'])test(`discovered source policy rejects ${url}`,()=>assert.throws(()=>publicResultUrl(url,['example.org'])));
test('domain allowlist matches boundary and URL fragment is normalized',()=>assert.equal(publicResultUrl('https://docs.example.org/page#part',['example.org']),'https://docs.example.org/page'));
test('candidate citations and quotes require exact pinned material; host owns URL footnotes',t=>{
 const {w,run}=workflowSetup(t),r:WorkflowContentRequest={protocolVersion:1,task:'outline',runId:run.id,requestId:'q',goal:'Explain',language:'en',guidance:null,sources:run.capture.sources,gaps:[],feedback:'',outline:null,draft:null,review:null};
 const o=workflowFixture(r);assert.equal(o.task,'outline');if(o.task!=='outline')throw Error();const dreq={...r,task:'draft' as const,outline:o},d=workflowFixture(dreq);assert.ok(d.task==='draft');if(d.task!=='draft')throw Error();
 assert.doesNotThrow(()=>validateWorkflowOutput(d,dreq));assert.throws(()=>validateWorkflowOutput({...d,markdown:'Invented [^S2]'},dreq));assert.throws(()=>validateWorkflowOutput({...d,markdown:'https://madeup.example/paper'},dreq));assert.throws(()=>validateWorkflowOutput({...d,citations:[{itemIndex:0,start:0,end:4,quote:'FAKE'}]},dreq));
 const markdown=renderWorkflowDraft(d,run.capture.sources);assert.match(markdown,/snapshot/);assert.match(markdown,/fiction.txt/);assert.equal(w.history(w.listDocuments()[0]!.id).length,1);
});
test('draft review is anchored to candidate, not a fabricated manuscript revision',t=>{const {run}=workflowSetup(t);const r:WorkflowContentRequest={protocolVersion:1,task:'outline',runId:run.id,requestId:'q',goal:'Explain',language:'en',guidance:null,sources:run.capture.sources,gaps:[],feedback:'',outline:null,draft:null,review:null};const o=workflowFixture(r);if(o.task!=='outline')throw Error();const dr={...r,task:'draft' as const,outline:o},d=workflowFixture(dr);if(d.task!=='draft')throw Error();const rr={...r,task:'draft-review' as const,outline:o,draft:d},review=workflowFixture(rr);if(review.task!=='draft-review')throw Error();assert.throws(()=>validateWorkflowOutput({...review,issues:[{...review.issues[0],quote:'invented'}]},rr));assert.throws(()=>validateWorkflowOutput({...review,needsRevision:true,issues:[]},rr));assert.doesNotThrow(()=>validateWorkflowOutput({...review,needsRevision:false,issues:[]},rr));});
test('workflow requests reject malformed or foreign nested outline/draft parents',t=>{const {run}=workflowSetup(t);const r:WorkflowContentRequest={protocolVersion:1,task:'draft',runId:run.id,requestId:'q',goal:'Explain',language:'en',guidance:null,sources:run.capture.sources,gaps:[],feedback:'',outline:null,draft:null,review:null};assert.throws(()=>validateWorkflowRequest({...r,outline:{runId:'other'}}));assert.throws(()=>validateWorkflowRequest({...r,outline:{task:'outline',runId:run.id,requestId:'q'}}));});

test('workflow language conflicts are explicit, not inferred from system locale',()=>{assert.throws(()=>validateWorkflowConfig(workflowConfig({language:'zh-CN',memoryOptions:{language:'en'}})),{code:'WORKFLOW_INVALID'});});
