// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';import { join } from 'node:path';
import { Workspace } from '@writer-agent/storage';
import { workflowSetup,grant } from './workflow-helpers.js';
import { propose } from './helpers.js';
import { pref } from './memory-helpers.js';
test('create and preview do not start a request or manuscript',t=>{const {w,run}=workflowSetup(t);assert.equal(run.state,'waiting-approval');assert.equal(w.workflows.attempts(run.id).length,0);assert.equal(w.listDocuments().length,1);const p=w.workflows.preview(run.id);assert.equal(p.summary.search,null);assert.throws(()=>w.workflows.acquire(run.id),{code:'WORKFLOW_PERMISSION'});assert.throws(()=>w.workflows.authorize(run.id,'wrong'),{code:'STALE_REVISION'});});
test('grant fixes limits/tasks/input; no permission for unrelated tools',t=>{const {w,run}=workflowSetup(t);grant(w,run.id);const lease=w.workflows.acquire(run.id);try{assert.throws(()=>w.workflows.reserve(lease,'shell','model','shell',{}),{code:'WORKFLOW_PERMISSION'});assert.throws(()=>w.workflows.authorize(run.id,w.workflows.preview(run.id).fingerprint),{code:'WORKFLOW_BUSY'});}finally{w.workflows.release(lease);}});
test('one task cannot acquire two simultaneous workers',t=>{const {w,run}=workflowSetup(t);grant(w,run.id);const other=Workspace.open(w.root);const lease=w.workflows.acquire(run.id);try{assert.throws(()=>other.workflows.acquire(run.id),{code:'WORKFLOW_BUSY'});assert.throws(()=>other.workflows.recover(run.id),{code:'WORKFLOW_BUSY'});}finally{other.close();w.workflows.release(lease);}});
test('unknown outcome after expired lease blocks silent replay and fences old writer',t=>{const {w,run}=workflowSetup(t);grant(w,run.id);const lease=w.workflows.acquire(run.id),a=w.workflows.reserve(lease,'key','model','outline',{data:'public'});w.workflows.dispatched(lease,a.id);w.workflows.recover(run.id,Date.now()+60000);assert.equal(w.workflows.attempts(run.id)[0]!.status,'outcome-unknown');assert.throws(()=>w.workflows.acquire(run.id),{code:'WORKFLOW_UNKNOWN'});assert.throws(()=>w.workflows.retry(run.id,a.id,false),{code:'WORKFLOW_UNKNOWN'});assert.throws(()=>w.workflows.complete(lease,a.id,'outline',{}),{code:'WORKFLOW_BUSY'});w.workflows.retry(run.id,a.id,true);const newer=w.workflows.acquire(run.id);try{assert.ok(newer.generation>lease.generation);assert.equal(w.workflows.usage(run.id).models,1);}finally{w.workflows.release(newer);}});
test('reserved-but-not-dispatched recovery needs explicit retry without duplicate warning',t=>{const {w,run}=workflowSetup(t);grant(w,run.id);const l=w.workflows.acquire(run.id),a=w.workflows.reserve(l,'key','model','outline',{});w.workflows.recover(run.id,Date.now()+60000);assert.equal(w.workflows.attempts(run.id)[0]!.errorCode,'NOT_SENT');w.workflows.retry(run.id,a.id,false);assert.equal(w.workflows.usage(run.id).models,1);});
test('failure retry does not refund attempt quota or reset on reopen',t=>{const {w,run}=workflowSetup(t);const limits={models:1,searches:0,fetches:0,activeMs:100000};const p=w.workflows.preview(run.id,limits);w.workflows.authorize(run.id,p.fingerprint,limits);const l=w.workflows.acquire(run.id),a=w.workflows.reserve(l,'key','model','outline',{});w.workflows.dispatched(l,a.id);w.workflows.fail(l,a.id,'PROVIDER_HTTP',false);w.workflows.release(l);w.workflows.retry(run.id,a.id,false);const l2=w.workflows.acquire(run.id);try{assert.throws(()=>w.workflows.reserve(l2,'key','model','outline',{}),{code:'WORKFLOW_BUDGET'});}finally{w.workflows.release(l2);}const other=Workspace.open(w.root);try{assert.equal(other.workflows.usage(run.id).models,1);}finally{other.close();}});
test('revocation fences in-flight output; cancellation preserves evidence and draft history',t=>{const {w,run}=workflowSetup(t);grant(w,run.id);const l=w.workflows.acquire(run.id),a=w.workflows.reserve(l,'key','model','outline',{});w.workflows.dispatched(l,a.id);w.workflows.pause(run.id,true);assert.equal(w.workflows.run(run.id).state,'cancelled');assert.throws(()=>w.workflows.complete(l,a.id,'outline',{}),{code:'WORKFLOW_BUSY'});assert.equal(w.workflows.artifacts(run.id).length,0);assert.equal(w.sources.list().length,1);});
test('active budget is charged only for worker lease time, not author waiting',t=>{const {w,run}=workflowSetup(t);grant(w,run.id);const start=Date.now(),l=w.workflows.acquire(run.id,start);w.workflows.pulse(l,start+500);w.workflows.release(l);assert.ok(w.workflows.usage(run.id).activeMs>=500);const before=w.workflows.usage(run.id).activeMs;w.workflows.preview(run.id);assert.equal(w.workflows.usage(run.id).activeMs,before);});
test('step artifact plus local side effect roll back together on injected failure',t=>{const {w,run}=workflowSetup(t);grant(w,run.id);const l=w.workflows.acquire(run.id),a=w.workflows.reserve(l,'key','model','outline',{});w.workflows.dispatched(l,a.id);const raw=new DatabaseSync(join(w.root,'.writer/workspace.sqlite'));try{raw.exec("CREATE TRIGGER fail_wf BEFORE INSERT ON workflow_artifacts BEGIN SELECT RAISE(ABORT,'injected'); END;");}finally{raw.close();}try{assert.throws(()=>w.workflows.complete(l,a.id,'outline',{},[],null,()=>{w.createDocument('rollback','do not persist');return {}; }),/injected/);assert.equal(w.listDocuments().length,1);assert.equal(w.workflows.artifacts(run.id).length,0);assert.equal(w.workflows.attempts(run.id)[0]!.status,'dispatched');}finally{w.workflows.release(l);}});
test('nested savepoint rollback does not undo successful outer operations',t=>{const {w,run}=workflowSetup(t);grant(w,run.id);const l=w.workflows.acquire(run.id),a=w.workflows.reserve(l,'key','model','outline',{});w.workflows.dispatched(l,a.id);try{const artifact=w.workflows.complete(l,a.id,'test',{},[],null,()=>{w.createDocument('kept','literal');try{w.createDocument('','bad');}catch{}return {ok:true};});assert.equal(w.listDocuments().length,2);assert.equal(w.workflows.complete(l,a.id,'ignored',{}).id,artifact.id);}finally{w.workflows.release(l);}});
test('document/guidance changes invalidate capture but unrelated profiles do not',t=>{const {w,document,source}=workflowSetup(t);const run=w.workflows.create({...workflowSetupConfig(document.id,source.snapshot.id)});grant(w,run.id);const p=w.memory.createProfile('unrelated');w.memory.addPreference(p.id,pref());assert.doesNotThrow(()=>w.workflows.assertFresh(w.workflows.run(run.id)));const c=propose(w,document.id,0,'later');w.accept(c.id);assert.throws(()=>w.workflows.acquire(run.id),{code:'STALE_REVISION'});const refreshed=w.workflows.refresh(run.id);assert.equal(refreshed.epoch,2);assert.equal(refreshed.grantId,null);});
import { workflowConfig } from './workflow-helpers.js';
function workflowSetupConfig(doc:string,source:string){return workflowConfig({template:'revise-article',documentId:doc,selection:{snapshots:[source]}});}
test('changed related new-article profile invalidates grant',t=>{const {w}=workflowSetup(t);const p=w.memory.createProfile('English');const run=w.workflows.create(workflowConfig({profileId:p.id}));grant(w,run.id);w.memory.addPreference(p.id,{...pref(),language:'en'});assert.throws(()=>w.workflows.acquire(run.id),{code:'STALE_REVISION'});});
test('immutable artifacts and event records have append-only protection',t=>{const {w,run}=workflowSetup(t);grant(w,run.id);const l=w.workflows.acquire(run.id),a=w.workflows.reserve(l,'x','model','outline',{});w.workflows.dispatched(l,a.id);w.workflows.complete(l,a.id,'test',{});w.workflows.release(l);const db=new DatabaseSync(join(w.root,'.writer/workspace.sqlite'));try{assert.throws(()=>db.exec('DELETE FROM workflow_artifacts'),/append-only/);assert.throws(()=>db.exec("UPDATE workflow_events SET payload='{}'"),/append-only/);}finally{db.close();}});

test('host reserve enforces disabled automatic revision even in an edit stage',t=>{const {w,document}=workflowSetup(t);const r=w.workflows.create(workflowConfig({template:'revise-article',documentId:document.id,autoRevision:false}));grant(w,r.id);const l=w.workflows.acquire(r.id);try{assert.throws(()=>w.workflows.reserve(l,'second','model','revise-proposal',{}),{code:'WORKFLOW_PERMISSION'});assert.equal(w.workflows.usage(r.id).models,0);}finally{w.workflows.release(l);}});
test('cancelled task cannot resurrect through refresh/outline changes',t=>{const {w,run}=workflowSetup(t);w.workflows.pause(run.id,true);assert.throws(()=>w.workflows.refresh(run.id),{code:'WORKFLOW_INVALID'});assert.throws(()=>w.workflows.chooseOutline(run.id,'old'),{code:'WORKFLOW_PERMISSION'});assert.throws(()=>w.workflows.amendOutline(run.id,'old',{} as never),{code:'WORKFLOW_PERMISSION'});w.workflows.pause(run.id);assert.equal(w.workflows.run(run.id).state,'cancelled');});
