// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,mkdirSync,readFileSync,rmSync,existsSync} from 'node:fs';
import {join} from 'node:path';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';
import {verifyPackage,installBootstrap} from '../bootstrap.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');
function fixture(t){const root=mkdtempSync(join(tmpdir(),'siglum-bootstrap-')),source=join(root,'source'),dest=join(root,'owned');mkdirSync(join(source,'src'),{recursive:true});const files=[['launch.mjs','export const launch=()=>{throw Error("must not execute in install test")};'],['src/engine.mjs','// test fixture']].map(([path,body])=>{writeFileSync(join(source,path),body);return {path,bytes:Buffer.byteLength(body),sha256:sha(body)};});writeFileSync(join(source,'UPDATER_MANIFEST.json'),JSON.stringify({format:1,kind:'updater-bootstrap',version:'0.2.0',files}));t.after(()=>rmSync(root,{recursive:true,force:true,maxRetries:4}));return {root,source,dest};}
test('bootstrap verifies pinned files before copying without executing them',async t=>{const f=fixture(t),r=await installBootstrap({root:f.dest,source:f.source,shortcuts:false});assert(r.installed);assert(existsSync(r.launcher));assert(existsSync(join(r.destination,'UPDATER_MANIFEST.json')));assert(!existsSync(join(f.dest,'config.json')));});
test('bootstrap same-version repeat reuses exact package',async t=>{const f=fixture(t);await installBootstrap({root:f.dest,source:f.source,shortcuts:false});assert((await installBootstrap({root:f.dest,source:f.source,shortcuts:false})).reused);});
test('bootstrap rejects modified source code',async t=>{const f=fixture(t);writeFileSync(join(f.source,'launch.mjs'),'different');await assert.rejects(verifyPackage(f.source),/changed/);});
test('bootstrap does not replace an unknown stable launcher',async t=>{const f=fixture(t);mkdirSync(f.dest);writeFileSync(join(f.dest,'start.mjs'),'my custom launcher');await assert.rejects(installBootstrap({root:f.dest,source:f.source,shortcuts:false}),/different stable launcher/);assert.equal(readFileSync(join(f.dest,'start.mjs'),'utf8'),'my custom launcher');});
test('bootstrap does not upgrade an active panel process',async t=>{const f=fixture(t);mkdirSync(f.dest);writeFileSync(join(f.dest,'panel-session.json'),JSON.stringify({pid:process.pid}));await assert.rejects(installBootstrap({root:f.dest,source:f.source,shortcuts:false}),/running updater/);});
test('stable launcher hashes files before importing executable package code',async t=>{const f=fixture(t),r=await installBootstrap({root:f.dest,source:f.source,shortcuts:false});const code=readFileSync(r.launcher,'utf8');assert(code.indexOf('hash(bytes)')<code.indexOf('await import'));assert(!code.includes('verifyPackage'));});
