// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';
import {writeFileSync,readFileSync,mkdirSync,existsSync,symlinkSync} from 'node:fs';import{join}from'node:path';
import{DatabaseSync}from'node:sqlite';
import{readZip,parseDelivery}from'../src/zip.mjs';import{strictJson}from'../src/json.mjs';
import{verifiedIdentity,DEFAULT_POLICY,validPolicy,checkRemoteName}from'../src/identity.mjs';
import{fingerprint,sourceTreeHash,parseVersion,compareVersion}from'../src/common.mjs';
import{childEnvironment}from'../src/process.mjs';import{UpdateStore,acquireRepositoryLock}from'../src/state.mjs';
import{zip,fixture,temporary,delivery,git}from'./helpers.mjs';
const raw=(name='JaynOwO/writer-agent')=>({id:1370967185,node_id:DEFAULT_POLICY.nodeId,owner:{id:255999131,login:name.split('/')[0]},full_name:name,permissions:{push:true},default_branch:'main'});
for(const name of ['JaynOwO/siglum-ai','JaynOwO/Siglum-AI','NewLogin/again','JaynOwO/writer-agent'])test('same stable identity supports rename '+name,()=>{assert.equal(verifiedIdentity(raw(name),DEFAULT_POLICY).fullName,name);});
test('same old name with different repository ID refuses',()=>{assert.throws(()=>verifiedIdentity({...raw(),id:99},DEFAULT_POLICY),{code:'REPOSITORY_MISMATCH'});});
test('same repository transferred to different owner refuses',()=>{assert.throws(()=>verifiedIdentity({...raw(),owner:{id:99,login:'buyer'}},DEFAULT_POLICY),{code:'OWNER_CHANGED'});});
test('policy cannot remove mandatory checks',()=>{assert.throws(()=>validPolicy({...DEFAULT_POLICY,expectedChecks:[]}),{code:'POLICY_INVALID'});});
test('remote parsing accepts standard HTTPS/SSH, not custom host',()=>{assert.equal(checkRemoteName('https://github.com/JaynOwO/siglum-ai.git'),'JaynOwO/siglum-ai');assert.equal(checkRemoteName('git@github.com:JaynOwO/siglum-ai.git'),'JaynOwO/siglum-ai');assert.throws(()=>checkRemoteName('ssh://git@alias/siglum-ai'));});
test('semantic versions do not use lexical ordering',()=>{assert(compareVersion('0.0.10','0.0.9')>0);assert(compareVersion('1.0.0','1.0.0-beta.2')>0);assert.throws(()=>parseVersion('latest'));});
for(const value of ['{"a":1,"a":2}','{"a":1,"\\u0061":2}','{"b":{"a":1,"a":2}}'])test('duplicate JSON keys refused '+value,()=>assert.throws(()=>strictJson(value),{code:'JSON_DUPLICATE'}));
for(const value of ['[1,]','{"x":1,}','true garbage','01','"unterminated','{"x":NaN}'])test('malformed JSON refused '+value,()=>assert.throws(()=>strictJson(value)));
test('JSON size/depth budgets enforced',()=>{assert.throws(()=>strictJson('[[[1]]]',{depth:1}));assert.throws(()=>strictJson('"abcdef"',{bytes:3}));assert.deepEqual(strictJson('{"x":[true,null,"😀"]}'),{x:[true,null,'😀']});});
for(const p of ['../x','/root','C:/x','a\\b','NUL','a/COM1.txt','a/.git/config','a/x.','a/x ','a/x:secret'])test('ZIP unsafe path '+p,()=>assert.throws(()=>readZip(zip([[p,'x']]))));
test('ZIP duplicate case paths refused',()=>assert.throws(()=>readZip(zip([['a','x'],['A','y']])),{code:'ZIP_DUPLICATE'}));
test('ZIP file/directory collision refused',()=>assert.throws(()=>readZip(zip([['a','x'],['a/b','y']])),{code:'ZIP_COLLISION'}));
test('ZIP symlinks refused',()=>assert.throws(()=>readZip(zip([['a','/etc/passwd',0xa1ff0000]])),{code:'ZIP_LINK'}));
test('ZIP data corruption refused',()=>{const b=zip([['x','content']]);b[31]^=1;assert.throws(()=>readZip(b),{code:'ZIP_CHECKSUM'});});
test('ZIP prefix and size budget refused',()=>{assert.throws(()=>readZip(Buffer.concat([Buffer.from('prefix'),zip([['x','ok']])])));assert.throws(()=>readZip(zip([['x','123456']]),{compressed:1000,total:3,file:100,entries:10,ratio:100}));});
test('unrelated database is not reinitialized',t=>{const root=temporary(t),db=new DatabaseSync(join(root,'state.sqlite'));db.exec('CREATE TABLE private(x TEXT)');db.close();assert.throws(()=>new UpdateStore(root),{code:'STATE_SCHEMA'});const check=new DatabaseSync(join(root,'state.sqlite'));try{assert(check.prepare("SELECT name FROM sqlite_master WHERE name='private'").get());}finally{check.close();}});
test('repository common lock refuses live owner and preserves bytes',t=>{const root=temporary(t),unlock=acquireRepositoryLock(root,'a');try{const b=readFileSync(join(root,'siglum-updater-v02.lock'));assert.throws(()=>acquireRepositoryLock(root,'a',true),{code:'REPOSITORY_LOCKED'});assert.deepEqual(readFileSync(join(root,'siglum-updater-v02.lock')),b);}finally{unlock();}});
test('state CAS and append-only event history',t=>{const s=new UpdateStore(temporary(t));try{const a=s.create({}),b=s.change(a.id,a.revision,{x:1});assert.throws(()=>s.change(a.id,a.revision,{x:2}),{code:'TASK_STALE'});assert.equal(s.get(a.id).x,1);assert.throws(()=>s.db.exec('DELETE FROM events'),/append-only/);assert.equal(b.revision,2);}finally{s.close();}});
test('build environment excludes all unrelated credentials and injection variables',()=>{const env=childEnvironment('build',{PATH:'/bin',HOME:'/home/test',OPENAI_API_KEY:'secret',GH_TOKEN:'secret',NODE_OPTIONS:'--require evil',GIT_CONFIG_COUNT:'1',SSH_AUTH_SOCK:'/secret'});assert.equal(env.PATH,'/bin');for(const k of ['OPENAI_API_KEY','GH_TOKEN','NODE_OPTIONS','GIT_CONFIG_COUNT','SSH_AUTH_SOCK'])assert.equal(env[k],undefined);});
test('manifest exact file hashes and target Git tree',async t=>{const f=await fixture(t);assert.equal(sourceTreeHash(f.baseFiles),f.baseTree);assert.equal(f.parsed.files.size,4);const bad=delivery(f.baseFiles,f.files,f.baseSha,f.baseTree,{identity:{host:'github.com',repositoryId:'99'}});assert.throws(()=>parseDelivery(bad.bytes,f.config.policy),{code:'REPOSITORY_MISMATCH'});});
test('legacy bundle requires explicit name binding, new names do not change original bytes',async t=>{const f=await fixture(t);const {identity,...legacy}=f.manifest;const b=zip([['UPDATE_MANIFEST.json',JSON.stringify(legacy)],...f.files.entries().map(([p,b])=>['source/'+p,b])]);assert.throws(()=>parseDelivery(b,f.config.policy),{code:'LEGACY_BINDING_REQUIRED'});const p=parseDelivery(b,{...f.config.policy,legacyApproved:true});assert.equal(p.manifest.repository,'JaynOwO/writer-agent');});
test('state shutdown is idempotent before temporary directory cleanup',t=>{const root=temporary(t),s=new UpdateStore(root);s.close();assert.doesNotThrow(()=>s.close());const again=new UpdateStore(root);again.close();});
