// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';
import{writeFileSync,readFileSync,existsSync,mkdirSync}from'node:fs';import{join}from'node:path';
import{fingerprint}from'../src/common.mjs';import{UpdateEngine}from'../src/engine.mjs';
import{fixture,git}from'./helpers.mjs';
async function authorize(f,mode='full'){const {task}=await f.engine.prepare(f.bytes,'test source.zip');return f.engine.authorize(task.id,fingerprint(f.engine.preview(task)),mode);}
test('complete worktree/commit/push/PR/CI/squash/local sync without direct main push',async t=>{const f=await fixture(t),task=await authorize(f),result=await f.engine.run(task.id);assert.equal(result.error,null,JSON.stringify(result.error));assert.equal(result.state,'done');assert.equal(result.remoteMerged,true);assert.equal(result.localSynced,true);assert.equal(result.cleanupComplete,true);assert.equal(git(f.repo,'rev-parse','HEAD'),result.mergeSha);assert.equal(git(f.repo,'branch','--show-current'),'main');assert.equal(readFileSync(join(f.repo,'new.txt'),'utf8'),'new content\n');assert.equal(f.validates(),1);assert.equal(f.gh.createCount,1);assert.equal(f.gh.mergeCount,1);});
test('uncommitted original work survives full update; local sync is a separate false fact',async t=>{const f=await fixture(t);writeFileSync(join(f.repo,'README.md'),'my private edits');writeFileSync(join(f.repo,'not-committed.txt'),'do not touch');const oldIndex=readFileSync(join(f.repo,'.git','index'));const task=await authorize(f),r=await f.engine.run(task.id);assert.equal(r.error,null,JSON.stringify(r.error));assert(r.remoteMerged);assert(!r.localSynced);assert.equal(readFileSync(join(f.repo,'README.md'),'utf8'),'my private edits');assert.equal(readFileSync(join(f.repo,'not-committed.txt'),'utf8'),'do not touch');assert.deepEqual(readFileSync(join(f.repo,'.git','index')),oldIndex);assert.equal(git(f.repo,'rev-parse','HEAD'),f.baseSha);});
test('prepared but unapproved task makes no managed worktree or remote PR',async t=>{const f=await fixture(t),{task}=await f.engine.prepare(f.bytes),r=await f.engine.run(task.id);assert.equal(r.error.code,'AUTHORIZATION_REQUIRED');assert.equal(f.gh.prs.length,0);assert.equal(r.worktree,null);});
test('wrong preview fingerprint cannot authorize',async t=>{const f=await fixture(t),{task}=await f.engine.prepare(f.bytes);assert.throws(()=>f.engine.authorize(task.id,'0'.repeat(64),'full'),{code:'PREVIEW_CHANGED'});});
test('same approved package is detected; merged task is not installed twice',async t=>{const f=await fixture(t),task=await authorize(f),r=await f.engine.run(task.id);assert.equal(r.error,null);const again=await f.engine.prepare(f.bytes,'same (1).zip');assert(again.duplicate);assert.equal(again.task.id,task.id);const rerun=await f.engine.run(task.id);assert.equal(rerun.state,'done');assert.equal(f.gh.createCount,1);assert.equal(f.gh.mergeCount,1);assert.equal(f.validates(),1);});
test('PR-only mode does not merge automatically',async t=>{const f=await fixture(t),task=await authorize(f,'pr-only'),r=await f.engine.run(task.id);assert.equal(r.error,null);assert.equal(r.state,'pr-created');assert.equal(f.gh.createCount,1);assert.equal(f.gh.mergeCount,0);assert.equal(git(f.repo,'rev-parse','HEAD'),f.baseSha);});
test('all mandatory CI failures stop integration',async t=>{const f=await fixture(t);f.gh.ciState='failed';const task=await authorize(f),r=await f.engine.run(task.id);assert.equal(r.error.code,'CI_FAILED');assert.equal(f.gh.mergeCount,0);assert.equal(git(f.remote,'rev-parse','main'),f.baseSha);});
test('CI wait timeout preserves PR and resumes without extra commit, push or PR',async t=>{const f=await fixture(t);f.gh.ciState='waiting';const task=await authorize(f),a=await f.engine.run(task.id,{maxWaitMs:0});assert.equal(a.state,'ci-waiting');assert.equal(a.error,null);f.gh.ciState='passed';const b=await f.engine.run(task.id);assert.equal(b.error,null,JSON.stringify(b.error));assert(b.remoteMerged);assert.equal(a.commitSha,b.commitSha);assert.equal(f.gh.createCount,1);assert.equal(f.validates(),1);});
for(const action of ['create-pr','merge'])test('lost '+action+' reply is reconciled without repeating remote write',async t=>{const f=await fixture(t);f.gh.failAfter=action;const task=await authorize(f),a=await f.engine.run(task.id);assert(a.error);const b=await f.engine.run(task.id);assert.equal(b.error,null,JSON.stringify(b.error));assert(b.remoteMerged);assert.equal(f.gh.createCount,1);assert.equal(f.gh.mergeCount,1);});
for(const action of ['commit','push'])test('lost '+action+' reply is reconciled from actual Git object/ref',async t=>{const f=await fixture(t);let armed=true;const orig=f.git[action==='commit'?'text':'run'];if(action==='commit')f.git.text=async(root,...args)=>{const v=await orig(root,...args);if(armed&&args.includes('commit')){armed=false;throw new Error('lost commit reply');}return v;};else f.git.run=async(root,args,...opts)=>{const v=await orig(root,args,...opts);if(armed&&args[0]==='push'){armed=false;throw new Error('lost push reply');}return v;};const task=await authorize(f),a=await f.engine.run(task.id);assert(a.error);const b=await f.engine.run(task.id);assert.equal(b.error,null,JSON.stringify(b.error));assert(b.remoteMerged);assert.equal(f.gh.createCount,1);assert.equal(f.gh.mergeCount,1);assert.equal(f.validates(),1);});
test('rename after PR creation keeps task, PR and repository identity',async t=>{const f=await fixture(t);f.gh.ciState='waiting';const task=await authorize(f),a=await f.engine.run(task.id,{maxWaitMs:0});f.gh.name='JaynOwO/Siglum-AI';f.gh.ciState='passed';const b=await f.engine.run(task.id);assert.equal(b.error,null);assert.equal(b.repositoryName,'JaynOwO/Siglum-AI');assert.equal(b.prId,a.prId);assert.equal(b.repositoryId,'1370967185');assert.equal(f.gh.createCount,1);});
test('repo ID replacement or owner transfer stops resume',async t=>{const f=await fixture(t),task=await authorize(f);f.gh.ownerId='99';const r=await f.engine.run(task.id);assert.equal(r.error.code,'OWNER_CHANGED');assert.equal(f.validates(),0);assert.equal(f.gh.prs.length,0);});
test('changing main after authorization refuses, no silent rebase',async t=>{const f=await fixture(t),task=await authorize(f);const sha=git(f.remote,'commit-tree',f.baseTree,'-p',f.baseSha,'-m','external change');git(f.remote,'update-ref','refs/heads/main',sha,f.baseSha);const r=await f.engine.run(task.id);assert.equal(r.error.code,'BASE_CHANGED');assert.equal(f.validates(),0);assert.equal(f.gh.prs.length,0);});
test('test mutation of approved source is detected before commit',async t=>{const f=await fixture(t,{validate:async t=>writeFileSync(join(t.worktree,'README.md'),'unexpected')});const task=await authorize(f),r=await f.engine.run(task.id);assert.equal(r.error.code,'FILE_CONFLICT');assert.equal(r.state,'applied');assert.equal(f.gh.prs.length,0);assert.equal(git(f.repo,'rev-parse','HEAD'),f.baseSha);});
test('known partially applied target resumes validation, not manual file cleanup',async t=>{let fail=true;const f=await fixture(t,{validate:async()=>{if(fail)throw new Error('test fails once');}}),task=await authorize(f),a=await f.engine.run(task.id);assert.equal(a.state,'applied');fail=false;const b=await f.engine.run(task.id);assert.equal(b.error,null);assert(b.remoteMerged);assert.equal(f.validates(),2);});
test('unknown changed remote feature branch is never force pushed',async t=>{const f=await fixture(t);f.gh.failAfter='create-pr';const task=await authorize(f),a=await f.engine.run(task.id);assert(a.error);const other=git(f.remote,'commit-tree',f.baseTree,'-p',f.baseSha,'-m','different');git(f.remote,'update-ref','refs/heads/'+a.branch,other,a.commitSha);const b=await f.engine.run(task.id);assert.equal(b.error.code,'PR_CHANGED');assert.equal(git(f.remote,'rev-parse',a.branch),other);assert.equal(f.gh.mergeCount,0);});
test('original local fast-forward can be finished separately after cleanup warning/sync skip',async t=>{const f=await fixture(t);writeFileSync(join(f.repo,'README.md'),'local change');const task=await authorize(f),a=await f.engine.run(task.id);assert(a.remoteMerged&&!a.localSynced);writeFileSync(join(f.repo,'README.md'),f.baseFiles.get('README.md'));const b=await f.engine.run(task.id,{finishLocal:true});assert.equal(b.error,null);assert(b.localSynced);assert.equal(f.gh.mergeCount,1);});
