// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';
import { servePanel,diagnosticTask } from '../src/server.mjs';
const fake=()=>({closing:false,jobs:new Map(),output:new Map(),store:{get:id=>({id,secret:'not-for-export',repoPath:'/private/path',version:'0.0.9',state:'prepared',error:{code:'TEST',message:'Test',details:{stdout:'PRIVATE'}}}),events:()=>[]},state:()=>({configured:false,tasks:[]}),preview:async()=>({fingerprint:'f'}),action:async()=>({accepted:true}),prepare:async()=>({accepted:true}),close:async function(){this.closing=true;}});
function raw(origin,path,headers={},method='GET',body=''){return new Promise((resolve,reject)=>{const req=http.request(new URL(path,origin),{method,headers},res=>{let b='';res.on('data',x=>b+=x);res.on('end',()=>resolve({status:res.statusCode,body:b,headers:res.headers}));});req.on('error',reject);req.end(body);});}
async function panel(t){const app=fake(),s=await servePanel(app);t.after(()=>s.close());return {...s,app};}
test('UI entry has no token embedded in HTML and restrictive CSP',async t=>{const s=await panel(t),r=await raw(s.origin,'/');assert.equal(r.status,200);assert(!r.body.includes(s.token));assert(r.headers['content-security-policy'].includes("frame-ancestors 'none'"));assert(!r.body.includes('https://'));});
test('API refuses requests lacking the per-launch bearer',async t=>{const s=await panel(t);assert.equal((await raw(s.origin,'/api/state')).status,403);assert.equal((await raw(s.origin,'/api/state',{Authorization:'Bearer bad'})).status,403);});
test('API bearer plus matching origin reads state',async t=>{const s=await panel(t),r=await raw(s.origin,'/api/state',{Authorization:'Bearer '+s.token,Origin:s.origin});assert.equal(r.status,200);assert.equal(JSON.parse(r.body).configured,false);});
test('DNS rebinding-style Host is refused even with bearer',async t=>{const s=await panel(t);assert.equal((await raw(s.origin,'/api/state',{Host:'evil.test',Authorization:'Bearer '+s.token})).status,403);});
test('mutating route requires Origin and JSON; GET never acts',async t=>{const s=await panel(t),h={Authorization:'Bearer '+s.token,'Content-Type':'application/json'};assert.equal((await raw(s.origin,'/api/action',h,'POST','{}')).status,403);assert.equal((await raw(s.origin,'/api/action',{...h,Origin:'https://evil.test'},'POST','{}')).status,403);assert.equal((await raw(s.origin,'/api/action',{...h,Origin:s.origin},'POST','{"id":"x","action":"run"}')).status,200);assert.notEqual((await raw(s.origin,'/api/action',h)).status,200);});
test('duplicate JSON, overlarge bodies, wrong binary type, unknown routes refused',async t=>{const s=await panel(t),h={Authorization:'Bearer '+s.token,Origin:s.origin,'Content-Type':'application/json'};assert.equal((await raw(s.origin,'/api/action',h,'POST','{"id":"x","id":"y"}')).status,400);assert.equal((await raw(s.origin,'/api/action',h,'POST','"'+'x'.repeat(66000)+'"')).status,400);assert.equal((await raw(s.origin,'/api/prepare',h,'POST','{}')).status,400);assert.equal((await raw(s.origin,'/api/shell',h,'POST','{}')).status,404);});
test('cross-origin static request and arbitrary path denied',async t=>{const s=await panel(t);assert.equal((await raw(s.origin,'/',{Origin:'https://evil.test'})).status,403);assert.equal((await raw(s.origin,'/../package.json')).status,404);});
test('diagnostics whitelist excludes paths, service output and unknown fields',()=>{const d=diagnosticTask(fake().store.get('sample'));const text=JSON.stringify(d);assert(!text.includes('PRIVATE'));assert(!text.includes('/private'));assert(!text.includes('not-for-export'));assert.equal(d.error.code,'TEST');});
test('launch sessions have independent tokens',async t=>{const a=await panel(t),b=await panel(t);assert.notEqual(a.token,b.token);assert.equal((await raw(b.origin,'/api/state',{Authorization:'Bearer '+a.token})).status,403);});
