// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{join}from'node:path';
import{publicAssetBytes,validateReleaseIndex,releaseCatalogue,downloadReleaseProduct}from'../src/releases.mjs';import{sha256}from'../src/common.mjs';import{temporary}from'./helpers.mjs';
const repo={repositoryId:'1370967185',fullName:'JaynOwO/siglum-ai',private:false};
const data=Buffer.from('synthetic release data'),product={product:'siglum',kind:'source-delivery',version:'0.0.9',assetId:12,sha256:sha256(data)};
const descriptor=Buffer.from(JSON.stringify({format:1,repositoryId:repo.repositoryId,products:[product]}));
const release={id:9,tag:'v0.0.9',prerelease:false,assets:[{id:11,name:'siglum-release.json',size:descriptor.length,digest:'sha256:'+sha256(descriptor),url:'https://github.com/x/index'},{id:12,name:'whatever.zip',size:data.length,digest:'sha256:'+sha256(data),url:'https://github.com/x/asset',updatedAt:'2026-01-01'}]};
const download=async url=>url.endsWith('/index')?descriptor:data;
const gh={releases:async()=>({repo,releases:[release]})};
test('renamed repo downloads by ID/asset identity, not historical name',async t=>{const c=await releaseCatalogue(gh,{download});assert.equal(c.products[0].repositoryName,'JaynOwO/siglum-ai');const d=await downloadReleaseProduct(gh,c.products[0],temporary(t),{download});assert.deepEqual(readFileSync(d.path),data);});
test('same Release filename replaced with new asset/update identity requires new preview',async t=>{const c=await releaseCatalogue(gh,{download}),g={releases:async()=>({repo,releases:[{...release,assets:release.assets.map(a=>a.id===12?{...a,updatedAt:'different'}:a)}]})};await assert.rejects(()=>downloadReleaseProduct(g,c.products[0],temporary(t),{download}),{code:'RELEASE_CHANGED'});});
test('wrong repository, digest, unknown kind and duplicate products refuse',()=>{for(const patch of[{repositoryId:'99'},{products:[{...product,sha256:'0'.repeat(64)}]},{products:[{...product,kind:'shell'}]},{products:[product,product]}])assert.throws(()=>validateReleaseIndex({format:1,repositoryId:repo.repositoryId,products:[product],...patch},repo,release));});
test('release without descriptor remains unrecognized, no auto install guess',async()=>{const c=await releaseCatalogue({releases:async()=>({repo,releases:[{...release,assets:[release.assets[1]]}]})},{download});assert.equal(c.products.length,0);assert.equal(c.unrecognized.length,1);});
test('download follows allowed public HTTPS redirects without any token',async()=>{let n=0;const fetcher=async(url,init)=>{assert.equal(init.redirect,'manual');assert.equal(init.credentials,'omit');assert.equal(init.headers.Authorization,undefined);n++;return n===1?new Response(null,{status:302,headers:{location:'https://release-assets.githubusercontent.com/x?public-download=1'}}):new Response(data);};assert.deepEqual(await publicAssetBytes('https://github.com/x',{fetcher}),data);assert.equal(n,2);});
for(const url of['http://github.com/x','https://github.com.evil/x','https://user:secret@github.com/x','https://localhost/x'])test('unapproved release URL rejected '+url,async()=>{await assert.rejects(()=>publicAssetBytes(url,{fetcher:()=>{throw new Error('should not call');}}),{code:'DOWNLOAD_TARGET'});});
test('redirect to arbitrary/private host refused, oversized or missing body fails',async()=>{await assert.rejects(()=>publicAssetBytes('https://github.com/x',{fetcher:async()=>new Response(null,{status:302,headers:{location:'http://127.0.0.1/admin'}})}),{code:'DOWNLOAD_TARGET'});await assert.rejects(()=>publicAssetBytes('https://github.com/x',{maxBytes:2,fetcher:async()=>new Response(data)}),{code:'DOWNLOAD_SIZE'});});
test('changed cached public asset is not accepted silently',async t=>{const c=await releaseCatalogue(gh,{download}),dir=temporary(t);writeFileSync(join(dir,product.sha256+'.zip'),'changed');await assert.rejects(()=>downloadReleaseProduct(gh,c.products[0],dir,{download}),{code:'CACHE_CHANGED'});});
