// SPDX-License-Identifier: Apache-2.0
/** User-level installation, deliberately separate from writing and source integration. */
import {dirname,join,relative,isAbsolute,sep} from 'node:path';
import {spawn} from 'node:child_process';
import {VERSION} from './contract.mjs';
import {readDesktopManifest,verifyDesktop,copyVersion} from './install-core.mjs';
const fail=message=>{throw Error(message);};
function powershell(script,extra={},detached=false){
 const exe=join(process.env.SystemRoot||'C:\\Windows','System32','WindowsPowerShell','v1.0','powershell.exe');
 return new Promise((resolve,reject)=>{const child=spawn(exe,['-NoProfile','-NonInteractive','-Command',script],{env:{...Object.fromEntries(['SystemRoot','SYSTEMROOT','WINDIR','PATH','TEMP','TMP','USERPROFILE','LOCALAPPDATA','APPDATA'].filter(k=>typeof process.env[k]==='string').map(k=>[k,process.env[k]])),...extra},shell:false,windowsHide:true,detached,stdio:detached?'ignore':['ignore','pipe','pipe']});if(detached){child.once('error',reject);child.once('spawn',()=>{child.unref();resolve('');});return;}let output='',error='';child.stdout.on('data',b=>{output+=b.toString('utf8');if(output.length>65536)child.kill();});child.stderr.on('data',b=>{error+=b.toString('utf8');if(error.length>65536)child.kill();});const timer=setTimeout(()=>child.kill(),30000);child.once('error',reject);child.once('close',code=>{clearTimeout(timer);code===0?resolve(output):reject(Error('Windows installation integration failed; copied program files and your writing were preserved.'));});});
}
async function knownFolders(){const result=await powershell("[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false); @{ local=[Environment]::GetFolderPath('LocalApplicationData'); desktop=[Environment]::GetFolderPath('DesktopDirectory'); programs=[Environment]::GetFolderPath('Programs') } | ConvertTo-Json -Compress");const f=JSON.parse(result);for(const p of Object.values(f))if(typeof p!=='string'||!isAbsolute(p))fail('Windows Known Folder could not be resolved.');return f;}
export async function installationInfo(){if(process.platform!=='win32')return {supported:false,reason:'This package implements user-level installation for Windows x64 only. / 此内置安装流程仅用于 Windows x64。'};const source=dirname(process.execPath);try{const m=await readDesktopManifest(source),f=await knownFolders(),root=join(f.local,'Programs','Siglum'),destination=join(root,'versions',`${VERSION}-${m.hash.slice(0,12)}`);return {supported:true,source,root,destination,desktop:f.desktop,programs:f.programs,manifestHash:m.hash,alreadyInInstallLocation:source.toLowerCase()===destination.toLowerCase()};}catch{return {supported:false,reason:'Use the complete, verified Windows portable package, including DESKTOP_MANIFEST.json. / 请使用包含 DESKTOP_MANIFEST.json 的完整 Windows 便携包。'};}}
const SHORTCUT_SCRIPT=`$ErrorActionPreference='Stop'; $key='HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Siglum'; if(Test-Path $key){$existing=(Get-ItemProperty $key).InstallLocation;if($existing -and $existing -ne $env:SIGLUM_ROOT){throw 'Existing registry item belongs to another installation'}}; $ws=New-Object -ComObject WScript.Shell; foreach($p in @($env:SIGLUM_DESKTOP_LINK,$env:SIGLUM_START_LINK)){ if(Test-Path -LiteralPath $p){ $old=$ws.CreateShortcut($p); if($old.TargetPath -and -not $old.TargetPath.StartsWith($env:SIGLUM_ROOT+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)){throw 'Existing shortcut is not owned by Siglum'} }; $s=$ws.CreateShortcut($p); $s.TargetPath=$env:SIGLUM_EXE; $s.WorkingDirectory=$env:SIGLUM_VERSION_DIR; $s.Description='Siglum local writing workspace'; $s.Save() }; $key='HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Siglum'; New-Item -Path $key -Force | Out-Null; New-ItemProperty -Path $key -Name DisplayName -Value 'Siglum' -Force | Out-Null; New-ItemProperty -Path $key -Name DisplayVersion -Value $env:SIGLUM_VERSION -Force | Out-Null; New-ItemProperty -Path $key -Name InstallLocation -Value $env:SIGLUM_ROOT -Force | Out-Null; New-ItemProperty -Path $key -Name UninstallString -Value ('"'+$env:SIGLUM_EXE+'" --uninstall-local') -Force | Out-Null; New-ItemProperty -Path $key -Name NoModify -PropertyType DWord -Value 1 -Force | Out-Null; New-ItemProperty -Path $key -Name NoRepair -PropertyType DWord -Value 1 -Force | Out-Null;`;
export async function installCurrentUser(){const i=await installationInfo();if(!i.supported)fail(i.reason);const m=await readDesktopManifest(i.source);await copyVersion(i.source,i.destination,m.bytes,m.manifest);await powershell(SHORTCUT_SCRIPT,{SIGLUM_ROOT:i.root,SIGLUM_VERSION_DIR:i.destination,SIGLUM_EXE:join(i.destination,'Siglum.exe'),SIGLUM_VERSION:VERSION,SIGLUM_DESKTOP_LINK:join(i.desktop,'Siglum.lnk'),SIGLUM_START_LINK:join(i.programs,'Siglum.lnk')});return {installed:true,destination:i.destination,version:VERSION,previousVersionsPreserved:true,userWritingUntouched:true};}
/** Uninstaller executes only from a verified owned installation and never deletes writing/config/keyring. */
export async function scheduleUninstall(){
 const i=await installationInfo();if(!i.supported||!i.alreadyInInstallLocation)fail('Uninstall must run from the installed, verified version.');const m=await readDesktopManifest(i.source);await verifyDesktop(i.source,m.manifest);
 const rel=relative(i.root,i.source);if(rel.startsWith('..')||isAbsolute(rel)||!rel.startsWith('versions'+sep))fail('Invalid installation location.');
 const answer=await (await import('electron')).dialog.showMessageBox({type:'warning',message:'Uninstall this Siglum program version? / 卸载此 Siglum 程序版本？',detail:'Writing workspaces, saved connections, keys, and older program versions are preserved. Modified or unknown program files are not removed.\n保留所有私稿、连接、密钥和旧程序版本；不删除被修改或未知文件。',buttons:['Cancel / 取消','Uninstall / 卸载'],defaultId:0,cancelId:0});if(answer.response!==1)return false;
 const script=`$ErrorActionPreference='Stop'; try { Wait-Process -Id ([int]$env:SIGLUM_PARENT_PID) -Timeout 30 -ErrorAction SilentlyContinue } catch {}; if(Get-Process -Id ([int]$env:SIGLUM_PARENT_PID) -ErrorAction SilentlyContinue){exit 1}; $dir=$env:SIGLUM_VERSION_DIR; if(((Get-Item -LiteralPath $dir).Attributes -band [IO.FileAttributes]::ReparsePoint)){exit 2}; if((Get-FileHash -LiteralPath (Join-Path $dir 'DESKTOP_MANIFEST.json') -Algorithm SHA256).Hash.ToLower() -ne $env:SIGLUM_MANIFEST_HASH){exit 2}; $manifest=Get-Content -LiteralPath (Join-Path $dir 'DESKTOP_MANIFEST.json') -Raw | ConvertFrom-Json; if($manifest.appId -ne 'org.siglum.writer'){exit 2}; foreach($f in $manifest.files){$p=[IO.Path]::GetFullPath((Join-Path $dir $f.path)); if(-not $p.StartsWith($dir+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)){exit 3}; if(Test-Path -LiteralPath $p){$parent=$p; while($parent -ne $dir){if((Get-Item -LiteralPath $parent).Attributes -band [IO.FileAttributes]::ReparsePoint){exit 3};$parent=[IO.Path]::GetDirectoryName($parent)}; $h=(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLower(); if($h -ne $f.sha256){exit 4}}}; $ws=New-Object -ComObject WScript.Shell; foreach($p in @($env:SIGLUM_DESKTOP_LINK,$env:SIGLUM_START_LINK)){if(Test-Path -LiteralPath $p){$s=$ws.CreateShortcut($p);if($s.TargetPath -eq $env:SIGLUM_EXE){Remove-Item -LiteralPath $p}}}; $key='HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Siglum'; if(Test-Path $key){$v=(Get-ItemProperty $key).UninstallString;if($v -eq ('"'+$env:SIGLUM_EXE+'" --uninstall-local')){Remove-Item -Path $key}}; foreach($f in $manifest.files){$p=[IO.Path]::GetFullPath((Join-Path $dir $f.path));if(Test-Path -LiteralPath $p){Remove-Item -LiteralPath $p -Force}}; Remove-Item -LiteralPath (Join-Path $dir 'DESKTOP_MANIFEST.json'); $dirs=@{}; foreach($f in $manifest.files){$p=[IO.Path]::GetDirectoryName([IO.Path]::GetFullPath((Join-Path $dir $f.path))); while($p -ne $dir -and $p.StartsWith($dir+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)){$dirs[$p]=$true;$p=[IO.Path]::GetDirectoryName($p)}}; $dirs.Keys | Sort-Object Length -Descending | ForEach-Object {if((Test-Path -LiteralPath $_) -and -not ((Get-Item -LiteralPath $_).Attributes -band [IO.FileAttributes]::ReparsePoint) -and -not (Get-ChildItem -LiteralPath $_ -Force)){Remove-Item -LiteralPath $_}}; if(-not (Get-ChildItem -LiteralPath $dir -Force)){Remove-Item -LiteralPath $dir};`;
 await powershell(script,{SIGLUM_PARENT_PID:String(process.pid),SIGLUM_MANIFEST_HASH:m.hash,SIGLUM_VERSION_DIR:i.source,SIGLUM_EXE:process.execPath,SIGLUM_DESKTOP_LINK:join(i.desktop,'Siglum.lnk'),SIGLUM_START_LINK:join(i.programs,'Siglum.lnk')},true);return true;
}
