// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';
import {readDesktopManifest,verifyDesktop,copyVersion,safePackagePath} from '../install-core.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex');
function fixture(t){const root=mkdtempSync(join(tmpdir(),'siglum-install-')),source=join(root,'source'),dest=join(root,'versions','0.0.9-fixture');mkdirSync(source);const files=Array.from({length:10},(_,i)=>{const path=i===0?'Siglum.exe':`file-${i}.txt`,text='synthetic-'+i;writeFileSync(join(source,path),text);return {path,bytes:Buffer.byteLength(text),sha256:hash(text)};});const m={format:1,kind:'siglum-desktop',appId:'org.siglum.writer',version:'0.0.9',platform:'win32',arch:'x64',files};writeFileSync(join(source,'DESKTOP_MANIFEST.json'),JSON.stringify(m));t.after(()=>rmSync(root,{recursive:true,force:true,maxRetries:4}));return {root,source,dest,m};}
for(const p of ['../x','a/../x','C:/x','a\\x','a:x','CON.txt','a/COM1','x.','x ','/root','a//b'])test('installer refuses path '+p,()=>assert.equal(safePackagePath(p),false));
test('verified version copy is exact and does not overwrite other data',async t=>{const f=fixture(t),m=await readDesktopManifest(f.source);await copyVersion(f.source,f.dest,m.bytes,m.manifest);assert(await verifyDesktop(f.dest,m.manifest));assert((await copyVersion(f.source,f.dest,m.bytes,m.manifest)).reused);});
test('modified binary refuses install before copy',async t=>{const f=fixture(t),m=await readDesktopManifest(f.source);writeFileSync(join(f.source,'Siglum.exe'),'changed');await assert.rejects(copyVersion(f.source,f.dest,m.bytes,m.manifest),/changed/);});
test('existing modified installation is retained',async t=>{const f=fixture(t),m=await readDesktopManifest(f.source);await copyVersion(f.source,f.dest,m.bytes,m.manifest);writeFileSync(join(f.dest,'file-1.txt'),'manual');await assert.rejects(copyVersion(f.source,f.dest,m.bytes,m.manifest),/changed/);assert.equal(readFileSync(join(f.dest,'file-1.txt'),'utf8'),'manual');});
test('wrong app identity is refused',async t=>{const f=fixture(t);writeFileSync(join(f.source,'DESKTOP_MANIFEST.json'),JSON.stringify({...f.m,appId:'other'}));await assert.rejects(readDesktopManifest(f.source),/expected/);});
